//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_APP_APPLICATION_VER
    /// </summary>
    public partial class T_APP_APPLICATION_VER
    {
        
    /// <summary>
    ///VERSION_NO
    /// </summary>
    public string VERSION_NO { get; set; }
        
    /// <summary>
    ///VERSION_DESC
    /// </summary>
    public string VERSION_DESC { get; set; }
        
    /// <summary>
    ///APP_ID
    /// </summary>
    public string APP_ID { get; set; }
        
    /// <summary>
    ///CREATED_BY
    /// </summary>
    public string CREATED_BY { get; set; }
        
    /// <summary>
    ///CREATED_TIME
    /// </summary>
    public System.DateTime CREATED_TIME { get; set; }
        
    /// <summary>
    ///COMPATIBLE_INFO
    /// </summary>
    public string COMPATIBLE_INFO { get; set; }
        
    /// <summary>
    ///FILE_ID
    /// </summary>
    public string FILE_ID { get; set; }
        
    /// <summary>
    ///MANDATORY_UPGRADE
    /// </summary>
    public decimal MANDATORY_UPGRADE { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_BY
    /// </summary>
    public string LAST_UPDATED_BY { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_TIME
    /// </summary>
    public System.DateTime LAST_UPDATED_TIME { get; set; }
        
    /// <summary>
    ///DEVICE_TYPE
    /// </summary>
    public decimal DEVICE_TYPE { get; set; }
    }
}
