//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_APP_DEVICE
    /// </summary>
    public partial class T_APP_DEVICE
    {
        
    /// <summary>
    ///DEVICE_ID
    /// </summary>
    public string DEVICE_ID { get; set; }
        
    /// <summary>
    ///DEVICE_NAME
    /// </summary>
    public string DEVICE_NAME { get; set; }
        
    /// <summary>
    ///DEVICE_TYPE
    /// </summary>
    public decimal DEVICE_TYPE { get; set; }
        
    /// <summary>
    ///DEVICE_ORDER
    /// </summary>
    public decimal DEVICE_ORDER { get; set; }
        
    /// <summary>
    ///DEVICE_TOKEN
    /// </summary>
    public string DEVICE_TOKEN { get; set; }
        
    /// <summary>
    ///USER_ID
    /// </summary>
    public string USER_ID { get; set; }
        
    /// <summary>
    ///ENABLED
    /// </summary>
    public decimal ENABLED { get; set; }
        
    /// <summary>
    ///CREATED_BY
    /// </summary>
    public string CREATED_BY { get; set; }
        
    /// <summary>
    ///CREATED_TIME
    /// </summary>
    public System.DateTime CREATED_TIME { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_BY
    /// </summary>
    public string LAST_UPDATED_BY { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_TIME
    /// </summary>
    public System.DateTime LAST_UPDATED_TIME { get; set; }
    }
}
