//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///自定义应用类型（基础数据表）
    /// </summary>
    public partial class T_CP_UI_CUSTOMERAPPTYPE
    {
        
    /// <summary>
    ///应用类型ID
    /// </summary>
    public byte APPTYPE_ID { get; set; }
        
    /// <summary>
    ///应用类型编码（key）
    /// </summary>
    public string APPTYPE_CODE { get; set; }
        
    /// <summary>
    ///应用类型名称
    /// </summary>
    public string APPTYPE_DESC { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATED_BY { get; set; }
        
    /// <summary>
    ///创建时间
    /// </summary>
    public System.DateTime CREATE_DATE { get; set; }
    }
}
