//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///活动分发记录表
    /// </summary>
    public partial class T_EAP_CALENDAR_SEND
    {
        
    /// <summary>
    ///ID
    /// </summary>
    public string SEND_ID { get; set; }
        
    /// <summary>
    ///用户ID
    /// </summary>
    public string USER_ID { get; set; }
        
    /// <summary>
    ///活动ID
    /// </summary>
    public string EVENT_ID { get; set; }
        
    /// <summary>
    ///颜色
    /// </summary>
    public string COLOR { get; set; }
        
    /// <summary>
    ///更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_TIME { get; set; }
        
    /// <summary>
    ///0：否（没有删除），1：是
    ///删除的原因：活动被删除，在参与人列表中被移除
    /// </summary>
    public decimal DELETED { get; set; }
        
    /// <summary>
    ///存储提醒信息，Json格式字符串，
    ///Json格式为：
    ///[
    ///    {
    ///        "remind_time": "提醒时间，开始时间多少分钟前,0为不提醒",
    ///        "remind_type": "提醒方式 0：lycc弹窗 1：邮件，2：短信 ,3 手机铃声"
    ///    }
    ///]
    /// </summary>
    public string REMIND { get; set; }
        
    /// <summary>
    ///存储提醒结果，Json格式字符串，
    ///Json格式为：
    ///[
    ///    {
    ///        "remind_time": "提醒时间，开始时间多少分钟前,0为不提醒",
    ///        "remind_type": "提醒方式 0：lycc弹窗 1：邮件，2：短信 ,3 手机铃声"，
    ///        "over": "提醒结果，已提醒 1"
    ///    }
    ///]
    /// </summary>
    public string REMINDINFO { get; set; }
        
    /// <summary>
    ///重要性， 0 一般，1重要
    /// </summary>
    public decimal IMPORTANCE { get; set; }
    }
}
