//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///编码规则数据表
    /// </summary>
    public partial class T_EAP_FORM_CODE_DATA_NO
    {
        
    /// <summary>
    ///编号
    /// </summary>
    public string ID { get; set; }
        
    /// <summary>
    ///代码规则类型
    /// </summary>
    public string CODE_RULE_TYPE { get; set; }
        
    /// <summary>
    ///代码规则格式
    /// </summary>
    public string CODE_RULE_FORMAT { get; set; }
        
    /// <summary>
    ///名称
    /// </summary>
    public string TABLE_NAME { get; set; }
        
    /// <summary>
    ///数据编号
    /// </summary>
    public string DATA_NO { get; set; }
        
    /// <summary>
    ///创建时间
    /// </summary>
    public System.DateTime CREATED_TIME { get; set; }
    }
}
