//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///路径运行表
    /// </summary>
    public partial class T_EAP_WF_STEPPATH_RUNTIME_H
    {
        
    /// <summary>
    ///路径编号
    /// </summary>
    public string STEP_PATH_GUID { get; set; }
        
    /// <summary>
    ///步骤名
    /// </summary>
    public string STEP_NAME { get; set; }
        
    /// <summary>
    ///步骤类型
    /// </summary>
    public decimal STEP_TYPE { get; set; }
        
    /// <summary>
    ///路径序号
    /// </summary>
    public decimal STEP_PATH_ID { get; set; }
        
    /// <summary>
    ///步骤编号
    /// </summary>
    public string STEP_GUID { get; set; }
        
    /// <summary>
    ///流程编号
    /// </summary>
    public string PROCESS_GUID { get; set; }
        
    /// <summary>
    ///路径状态
    /// </summary>
    public decimal STEP_STATUS { get; set; }
        
    /// <summary>
    ///0：否，1：是
    /// </summary>
    public decimal IS_HISTORY { get; set; }
        
    /// <summary>
    ///0：否，1：是
    /// </summary>
    public decimal IS_CURRENT { get; set; }
        
    /// <summary>
    ///路径权值
    /// </summary>
    public decimal THRESHODE_VALUE { get; set; }
        
    /// <summary>
    ///更新日期
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///业务单号
    /// </summary>
    public string BUSINESS_NO { get; set; }
        
    /// <summary>
    ///上一步骤id
    /// </summary>
    public string LAST_STEP_GUID { get; set; }
        
    /// <summary>
    ///上一步骤路径id
    /// </summary>
    public string LAST_STEP_PATH_GUID { get; set; }
        
    /// <summary>
    ///删除步骤用于分流合流
    /// </summary>
    public string DROP_STEPS { get; set; }
    }
}
