//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///附件访问运行表
    /// </summary>
    public partial class T_EAP_WF_FILEACCESS
    {
        
    /// <summary>
    ///编号
    /// </summary>
    public string FAC_GUID { get; set; }
        
    /// <summary>
    ///用户编号
    /// </summary>
    public string USER_ID { get; set; }
        
    /// <summary>
    ///附件路径
    /// </summary>
    public string FILE_PATH { get; set; }
        
    /// <summary>
    ///附件mime类型
    /// </summary>
    public string FILE_MIME { get; set; }
        
    /// <summary>
    ///下载有效时间
    /// </summary>
    public System.DateTime VALID_TIME { get; set; }
        
    /// <summary>
    ///下载输出文件名
    /// </summary>
    public string FILE_OUTPUT_NAME { get; set; }
    }
}
