//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///流程表单状态配置表
    /// </summary>
    public partial class T_EAP_WF_FORM_STATUS_CONFIG
    {
        
    /// <summary>
    ///编号
    /// </summary>
    public string ID { get; set; }
        
    /// <summary>
    ///状态编号
    /// </summary>
    public string STATUS { get; set; }
        
    /// <summary>
    ///状态名
    /// </summary>
    public string STATUS_NAME { get; set; }
        
    /// <summary>
    ///流程模版编号
    /// </summary>
    public string PROCESS_MODULE_GUID { get; set; }
        
    /// <summary>
    ///流程模版主版本
    /// </summary>
    public decimal PROCESS_MODULE_MAIN_VER { get; set; }
        
    /// <summary>
    ///流程模版子版本
    /// </summary>
    public decimal PROCESS_MODULE_SUB_VER { get; set; }
    }
}
