//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_EAP_SYS_EMPLOYEE_18410
    /// </summary>
    public partial class T_EAP_SYS_EMPLOYEE_18410
    {
        
    /// <summary>
    ///EMP_ID
    /// </summary>
    public string EMP_ID { get; set; }
        
    /// <summary>
    ///EMP_CODE
    /// </summary>
    public string EMP_CODE { get; set; }
        
    /// <summary>
    ///EMP_NAME
    /// </summary>
    public string EMP_NAME { get; set; }
        
    /// <summary>
    ///ORG_ID
    /// </summary>
    public string ORG_ID { get; set; }
        
    /// <summary>
    ///SEX
    /// </summary>
    public decimal SEX { get; set; }
        
    /// <summary>
    ///EMAIL
    /// </summary>
    public string EMAIL { get; set; }
        
    /// <summary>
    ///MOBILE
    /// </summary>
    public string MOBILE { get; set; }
        
    /// <summary>
    ///ENABLED
    /// </summary>
    public decimal ENABLED { get; set; }
        
    /// <summary>
    ///CREATED_BY
    /// </summary>
    public string CREATED_BY { get; set; }
        
    /// <summary>
    ///CREATED_TIME
    /// </summary>
    public System.DateTime CREATED_TIME { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_BY
    /// </summary>
    public string LAST_UPDATED_BY { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_TIME
    /// </summary>
    public System.DateTime LAST_UPDATED_TIME { get; set; }
        
    /// <summary>
    ///OFFICEPHONE
    /// </summary>
    public string OFFICEPHONE { get; set; }
        
    /// <summary>
    ///HOMEPHONE
    /// </summary>
    public string HOMEPHONE { get; set; }
        
    /// <summary>
    ///WORKSIGNATURE
    /// </summary>
    public string WORKSIGNATURE { get; set; }
        
    /// <summary>
    ///HEADPHOTO
    /// </summary>
    public string HEADPHOTO { get; set; }
    }
}
