//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///附件表
    /// </summary>
    public partial class T_EAP_WF_DOCUMENT
    {
        
    /// <summary>
    ///编号
    /// </summary>
    public string DOC_GUID { get; set; }
        
    /// <summary>
    ///关联流程编号
    /// </summary>
    public string FK_GUID { get; set; }
        
    /// <summary>
    ///文件类型
    /// </summary>
    public string DOC_TYPE { get; set; }
        
    /// <summary>
    ///服务器上文件名
    /// </summary>
    public string DOC_NAME { get; set; }
        
    /// <summary>
    ///用户文件名
    /// </summary>
    public string FILE_NAME { get; set; }
        
    /// <summary>
    ///文件路径
    /// </summary>
    public string LOCA_TION { get; set; }
        
    /// <summary>
    ///创建时间
    /// </summary>
    public System.DateTime CREATE_ON { get; set; }
        
    /// <summary>
    ///创建用户
    /// </summary>
    public string CREATE_BY { get; set; }
        
    /// <summary>
    ///是否导入
    /// </summary>
    public decimal IS_IMPOR_TANT { get; set; }
        
    /// <summary>
    ///锁定用户
    /// </summary>
    public string LOCKED_BY { get; set; }
        
    /// <summary>
    ///锁定日期
    /// </summary>
    public System.DateTime LOCKED_DATE_TIME { get; set; }
        
    /// <summary>
    ///修改用户
    /// </summary>
    public string MODI_FIED_BY { get; set; }
        
    /// <summary>
    ///修改日期
    /// </summary>
    public System.DateTime MODI_FIED_DATE_TIME { get; set; }
        
    /// <summary>
    ///关联节点
    /// </summary>
    public string NODE_GUID { get; set; }
        
    /// <summary>
    ///关联扩展节点
    /// </summary>
    public string NODE_EXTEND_GUID { get; set; }
        
    /// <summary>
    ///更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///文件mime类型
    /// </summary>
    public string FILE_MIME { get; set; }
    }
}
