//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_EAP_SYS_STATION_USER
    /// </summary>
    public partial class T_EAP_SYS_STATION_USER
    {
        
    /// <summary>
    ///表ID
    /// </summary>
    public string SU_ID { get; set; }
        
    /// <summary>
    ///岗位ID
    /// </summary>
    public string STATION_ID { get; set; }
        
    /// <summary>
    ///用户ID
    /// </summary>
    public string USER_ID { get; set; }
        
    /// <summary>
    ///创建时间
    /// </summary>
    public System.DateTime CREATED_TIME { get; set; }
    }
}
