//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///流程导入记录表
    /// </summary>
    public partial class T_EAP_WF_PROCESSIMPORTLOG
    {
        
    /// <summary>
    ///编号
    /// </summary>
    public string ID { get; set; }
        
    /// <summary>
    ///导入日期
    /// </summary>
    public System.DateTime IMPORT_DATE { get; set; }
        
    /// <summary>
    ///流程名
    /// </summary>
    public string PROCESS_NAME { get; set; }
        
    /// <summary>
    ///流程模版编号
    /// </summary>
    public string PROCESS_MODULE_GUID { get; set; }
        
    /// <summary>
    ///流程模版主版本
    /// </summary>
    public decimal PROCESS_MODULE_MAINVER { get; set; }
        
    /// <summary>
    ///流程模版子版本
    /// </summary>
    public decimal PROCESS_MODULE_SUBVER { get; set; }
        
    /// <summary>
    ///源数据库版本
    /// </summary>
    public string SOURCEDBVER { get; set; }
        
    /// <summary>
    ///目标数据库版本
    /// </summary>
    public string TARGETDBVER { get; set; }
        
    /// <summary>
    ///导入备注
    /// </summary>
    public string IMPORTINFO { get; set; }
    }
}
