//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///提醒模版表
    /// </summary>
    public partial class T_EAP_WF_REMIND_MODULE
    {
        
    /// <summary>
    ///编号
    /// </summary>
    public string REMIND_GUID { get; set; }
        
    /// <summary>
    ///步骤编号
    /// </summary>
    public string STEP_GUID { get; set; }
        
    /// <summary>
    ///提醒对象类型
    /// </summary>
    public decimal REMIND_USERTYPE { get; set; }
        
    /// <summary>
    ///提醒对象编号
    /// </summary>
    public string REMIND_USERID { get; set; }
        
    /// <summary>
    ///动作类型
    /// </summary>
    public decimal ACTIONTYPE { get; set; }
        
    /// <summary>
    ///0：否，1：是
    /// </summary>
    public decimal EMAIL { get; set; }
        
    /// <summary>
    ///邮件内容
    /// </summary>
    public string EMAIL_CONTENT { get; set; }
        
    /// <summary>
    ///邮件提醒次数
    /// </summary>
    public decimal EMAIL_TIME { get; set; }
        
    /// <summary>
    ///邮件提醒间隔
    /// </summary>
    public decimal EMAIL_INTERVAL { get; set; }
        
    /// <summary>
    ///0：否，1：是
    /// </summary>
    public decimal SMS { get; set; }
        
    /// <summary>
    ///短信提醒内容
    /// </summary>
    public string SMS_CONTENT { get; set; }
        
    /// <summary>
    ///短信提醒次数
    /// </summary>
    public decimal SMS_TIME { get; set; }
        
    /// <summary>
    ///短信提醒间隔
    /// </summary>
    public decimal SMS_INTERVAL { get; set; }
        
    /// <summary>
    ///单位：分钟
    /// </summary>
    public decimal EMAIL_DELAY { get; set; }
        
    /// <summary>
    ///单位：分钟
    /// </summary>
    public decimal SMS_DELAY { get; set; }
        
    /// <summary>
    ///提醒对象名
    /// </summary>
    public string REMIND_USERNAME { get; set; }
        
    /// <summary>
    ///邮件提醒标题
    /// </summary>
    public string EMAIL_TITLE { get; set; }
        
    /// <summary>
    ///催办对象类型
    /// </summary>
    public decimal URGE_USERTYPE { get; set; }
        
    /// <summary>
    ///催办对象编号
    /// </summary>
    public string URGE_USERID { get; set; }
        
    /// <summary>
    ///提醒类型默认为0动作触发
    /// </summary>
    public decimal REMIND_TYPE { get; set; }
        
    /// <summary>
    ///ISEMAILAUDIT
    /// </summary>
    public decimal ISEMAILAUDIT { get; set; }
        
    /// <summary>
    ///EXTEND_PROPERTY
    /// </summary>
    public string EXTEND_PROPERTY { get; set; }
    }
}
