//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///系统窗体数据记录表
    /// </summary>
    public partial class T_EAP_SYS_FORM_RECORD
    {
        
    /// <summary>
    ///数据记录ID
    /// </summary>
    public string RECORD_ID { get; set; }
        
    /// <summary>
    ///窗体ID
    /// </summary>
    public string FORM_ID { get; set; }
        
    /// <summary>
    ///表格对象ID
    /// </summary>
    public string CONTROL_ID { get; set; }
        
    /// <summary>
    ///表过滤名称
    /// </summary>
    public string TABLE_FILTER_NAME { get; set; }
        
    /// <summary>
    ///表过滤表达式
    /// </summary>
    public string TABLE_FILTER_EXPRESS { get; set; }
    }
}
