//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///流程模版修改权限表
    /// </summary>
    public partial class T_EAP_WF_CHANGE_PERMISSION
    {
        
    /// <summary>
    ///编号
    /// </summary>
    public string ID { get; set; }
        
    /// <summary>
    ///权限对象类型
    /// </summary>
    public decimal MEMBER_TYPE { get; set; }
        
    /// <summary>
    ///权限对象编号
    /// </summary>
    public string MEMBER_GUID { get; set; }
        
    /// <summary>
    ///流程模版编号
    /// </summary>
    public string PROCESS_MODULE_GUID { get; set; }
        
    /// <summary>
    ///更新日期
    /// </summary>
    public System.DateTime LAST_UPDATE_DATE { get; set; }
        
    /// <summary>
    ///权限0表示只读1表示可写
    /// </summary>
    public decimal PURVIEW { get; set; }
    }
}
