//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///驳回运行表
    /// </summary>
    public partial class T_EAP_WF_STEP_ROLLBACK_RUNTIME
    {
        
    /// <summary>
    ///编号
    /// </summary>
    public string ROLLBACK_RUN_ID { get; set; }
        
    /// <summary>
    ///驳回起始节点编号
    /// </summary>
    public string BACK_FROM_NODE_GUID { get; set; }
        
    /// <summary>
    ///驳回步骤编号
    /// </summary>
    public string BACK_TO_STEP_GUID { get; set; }
        
    /// <summary>
    ///0：否，1：是
    /// </summary>
    public decimal IS_JUMP { get; set; }
        
    /// <summary>
    ///0：初始，刚驳回，1：已重新审批过
    /// </summary>
    public decimal BACK_STATUS { get; set; }
        
    /// <summary>
    ///驳回时间
    /// </summary>
    public System.DateTime BACK_DATE { get; set; }
        
    /// <summary>
    ///流程编号
    /// </summary>
    public string PROCESS_GUID { get; set; }
        
    /// <summary>
    ///驳回起始步骤编号
    /// </summary>
    public string BACK_FROM_STEP_GUID { get; set; }
    }
}
