//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_EAP_MD_VIEWFIELDRELATION_H
    /// </summary>
    public partial class T_EAP_MD_VIEWFIELDRELATION_H
    {
        
    /// <summary>
    ///VFR_ID
    /// </summary>
    public string VFR_ID { get; set; }
        
    /// <summary>
    ///VR_ID
    /// </summary>
    public string VR_ID { get; set; }
        
    /// <summary>
    ///VFR_SRC_FLDID
    /// </summary>
    public string VFR_SRC_FLDID { get; set; }
        
    /// <summary>
    ///VFR_OBJ_FLDID
    /// </summary>
    public string VFR_OBJ_FLDID { get; set; }
        
    /// <summary>
    ///CREATED_BY
    /// </summary>
    public string CREATED_BY { get; set; }
        
    /// <summary>
    ///CREATED_TIME
    /// </summary>
    public System.DateTime CREATED_TIME { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_BY
    /// </summary>
    public string LAST_UPDATED_BY { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_TIME
    /// </summary>
    public System.DateTime LAST_UPDATED_TIME { get; set; }
        
    /// <summary>
    ///VER_ID
    /// </summary>
    public string VER_ID { get; set; }
        
    /// <summary>
    ///VFR_RELATION
    /// </summary>
    public string VFR_RELATION { get; set; }
    }
}
