//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///子流程运行表
    /// </summary>
    public partial class T_EAP_WF_CHILD_RUNTIME
    {
        
    /// <summary>
    ///编号
    /// </summary>
    public string ID { get; set; }
        
    /// <summary>
    ///子流程编号
    /// </summary>
    public string CHILD_PROCESS_ID { get; set; }
        
    /// <summary>
    ///父节点编号
    /// </summary>
    public string PARENT_NODE_GUID { get; set; }
        
    /// <summary>
    ///父步骤编号
    /// </summary>
    public string PARENT_STEP_GUID { get; set; }
        
    /// <summary>
    ///父路径序号
    /// </summary>
    public decimal PARENT_STEP_PATH_ID { get; set; }
        
    /// <summary>
    ///父路径编号
    /// </summary>
    public string PARENT_STEP_PATH_GUID { get; set; }
        
    /// <summary>
    ///是否历史数据
    /// </summary>
    public decimal IS_HISTORY { get; set; }
        
    /// <summary>
    ///父流程编号
    /// </summary>
    public string PARENT_PROCESS_ID { get; set; }
        
    /// <summary>
    ///子流程模版编号
    /// </summary>
    public string CHILD_PROCESS_MODULE_GUID { get; set; }
        
    /// <summary>
    ///子流程模版主版本
    /// </summary>
    public decimal CHILD_PROCESS_MODULE_MAIN_VER { get; set; }
        
    /// <summary>
    ///子流程模版子版本
    /// </summary>
    public decimal CHILD_PROCESS_MODULE_SUB_VER { get; set; }
    }
}
