//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///生产数据接口表
    /// </summary>
    public partial class T_IR_MIS_VECHILE
    {
        
    /// <summary>
    ///生产数据接口表ID
    /// </summary>
    public string IS_MIS_VECHILE_ID { get; set; }
        
    /// <summary>
    ///生产数据ID
    /// </summary>
    public string VECHILE_ID { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///品牌编码
    /// </summary>
    public string BRAND_CODE { get; set; }
        
    /// <summary>
    ///品牌描述
    /// </summary>
    public string BRAND_DESC { get; set; }
        
    /// <summary>
    ///销售汽车车系编码
    /// </summary>
    public string CAR_SERIES_CODE { get; set; }
        
    /// <summary>
    ///销售汽车车系名称
    /// </summary>
    public string CAR_SERIES_NAME { get; set; }
        
    /// <summary>
    ///服务车系编码
    /// </summary>
    public string S_CARSERIES_CODE { get; set; }
        
    /// <summary>
    ///服务车系名称
    /// </summary>
    public string S_CARSERIES_DESC { get; set; }
        
    /// <summary>
    ///车型配置ID
    /// </summary>
    public string CARCONFIGID { get; set; }
        
    /// <summary>
    ///销售汽车车型编码
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///销售汽车型名称
    /// </summary>
    public string CAR_TYPE_NAME { get; set; }
        
    /// <summary>
    ///服务车型编码
    /// </summary>
    public string S_CARTYPE_CODE { get; set; }
        
    /// <summary>
    ///服务车型名称
    /// </summary>
    public string S_CARTYPE_DESC { get; set; }
        
    /// <summary>
    ///车身颜色编码
    /// </summary>
    public string CAR_COLOR_CODE { get; set; }
        
    /// <summary>
    ///内饰色编码
    /// </summary>
    public string INNER_COLOR_CODE { get; set; }
        
    /// <summary>
    ///内饰色名称
    /// </summary>
    public string INNER_COLOR { get; set; }
        
    /// <summary>
    ///基准车系
    /// </summary>
    public string BBASE_SERIES_CODE { get; set; }
        
    /// <summary>
    ///18位码
    /// </summary>
    public string EIGTEEN_CODE { get; set; }
        
    /// <summary>
    ///租赁车设置时间
    /// </summary>
    public System.DateTime HOLD_TIME { get; set; }
        
    /// <summary>
    ///发动机号
    /// </summary>
    public string ENGINE_NO { get; set; }
        
    /// <summary>
    ///出厂日期
    /// </summary>
    public System.DateTime PRDDATE { get; set; }
        
    /// <summary>
    ///下线日期
    /// </summary>
    public System.DateTime OFFLINE_DATE { get; set; }
        
    /// <summary>
    ///最后行驶里程
    /// </summary>
    public decimal LAST_MILEAGE { get; set; }
        
    /// <summary>
    ///入库日期
    /// </summary>
    public System.DateTime IN_STORE_DATE { get; set; }
        
    /// <summary>
    ///销售交车日期
    /// </summary>
    public System.DateTime ACCDATE { get; set; }
        
    /// <summary>
    ///专营店购车日期
    /// </summary>
    public System.DateTime DLR_PURCHASE_DATE { get; set; }
        
    /// <summary>
    ///生产工厂
    /// </summary>
    public string PRODUCT_FACTORY { get; set; }
        
    /// <summary>
    ///是否迁移
    /// </summary>
    public string IS_FLAG { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///1
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///sys_guid()
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///88888
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///2
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建时间
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///修改人
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///修改时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
    }
}
