//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///保修单维护临时表
    /// </summary>
    public partial class T_MIS_BU_WARRANTY_CURSOR
    {
        
    /// <summary>
    ///保修单维护临时表ID
    /// </summary>
    public string CURSOR_ID { get; set; }
        
    /// <summary>
    ///保修单号
    /// </summary>
    public string GUARANTNO { get; set; }
        
    /// <summary>
    ///网点编码
    /// </summary>
    public string AGREE_NO { get; set; }
        
    /// <summary>
    ///是否参与MIS计算:0代表否、1代表是
    /// </summary>
    public string WHETHER_CALCULATION { get; set; }
        
    /// <summary>
    ///导入批次号
    /// </summary>
    public string BATCHNO { get; set; }
        
    /// <summary>
    ///报错备注
    /// </summary>
    public string ERROR { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
    }
}
