//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///对策履历业务表
    /// </summary>
    public partial class T_MIS_BU_MEASURES_RESUME
    {
        
    /// <summary>
    ///ID
    /// </summary>
    public string MIS_BU_MEASURES_RESUME_ID { get; set; }
        
    /// <summary>
    ///TPR NO
    /// </summary>
    public string TPR_NO { get; set; }
        
    /// <summary>
    ///KD TPR NO
    /// </summary>
    public string KD_TPR_NO { get; set; }
        
    /// <summary>
    ///输入类型
    /// </summary>
    public string INPUT_TYPE { get; set; }
        
    /// <summary>
    ///国家
    /// </summary>
    public string COUNTRY { get; set; }
        
    /// <summary>
    ///车系
    /// </summary>
    public string CAR_SERIES { get; set; }
        
    /// <summary>
    ///车型期间
    /// </summary>
    public string CAR_TYPE_PERIOD { get; set; }
        
    /// <summary>
    ///产量期间
    /// </summary>
    public string PRODUCE_PERIOD { get; set; }
        
    /// <summary>
    ///项目
    /// </summary>
    public string ITEM { get; set; }
        
    /// <summary>
    ///TCS担当
    /// </summary>
    public string TCS_DUTY { get; set; }
        
    /// <summary>
    ///重要度
    /// </summary>
    public string MPORTANCE_CODE { get; set; }
        
    /// <summary>
    ///担当部门
    /// </summary>
    public string DUTY_DEPT { get; set; }
        
    /// <summary>
    ///对策部门担当
    /// </summary>
    public string CMS_REPLY_USER { get; set; }
        
    /// <summary>
    ///目前进展
    /// </summary>
    public string NEXT_ACTION { get; set; }
        
    /// <summary>
    ///PFP
    /// </summary>
    public string PFP { get; set; }
        
    /// <summary>
    ///零件编码
    /// </summary>
    public string SPARE_PART_NO { get; set; }
        
    /// <summary>
    ///零件名称
    /// </summary>
    public string SPART_PART_NAME { get; set; }
        
    /// <summary>
    ///新/再发
    /// </summary>
    public string NEW_RE_SEND { get; set; }
        
    /// <summary>
    ///C-START区分
    /// </summary>
    public string C_START_DIFF { get; set; }
        
    /// <summary>
    ///WARRANTY C-START修理日
    /// </summary>
    public System.DateTime WARR_C_START_DAY { get; set; }
        
    /// <summary>
    ///C-START日
    /// </summary>
    public System.DateTime C_START_DATE { get; set; }
        
    /// <summary>
    ///设计/制造
    /// </summary>
    public string DES_OR_MADE { get; set; }
        
    /// <summary>
    ///发行日期
    /// </summary>
    public System.DateTime DISTRI_DATE { get; set; }
        
    /// <summary>
    ///REQ日期
    /// </summary>
    public System.DateTime REQ_DATE { get; set; }
        
    /// <summary>
    ///恒久对策采用日
    /// </summary>
    public System.DateTime APPL_DATE { get; set; }
        
    /// <summary>
    ///设通号
    /// </summary>
    public string DN_NO { get; set; }
        
    /// <summary>
    ///设通发行日
    /// </summary>
    public System.DateTime DN_ISSUE_DATE { get; set; }
        
    /// <summary>
    ///DNTC设通转发日
    /// </summary>
    public System.DateTime EXEC_DIS_DAY { get; set; }
        
    /// <summary>
    ///设计对策实绩日期
    /// </summary>
    public System.DateTime ACTU_APPL_DATE { get; set; }
        
    /// <summary>
    ///实际回答日期
    /// </summary>
    public System.DateTime REPLY_DATE { get; set; }
        
    /// <summary>
    ///结案时间
    /// </summary>
    public System.DateTime CASE_CLOSE_DATE { get; set; }
        
    /// <summary>
    ///CLOSE日
    /// </summary>
    public System.DateTime CLOSE_DAY { get; set; }
        
    /// <summary>
    ///DTR编号
    /// </summary>
    public string DTR_NO { get; set; }
        
    /// <summary>
    ///DTR提报日
    /// </summary>
    public System.DateTime DTR_ARR_DATE { get; set; }
        
    /// <summary>
    ///DTR接收日
    /// </summary>
    public System.DateTime DTR_RECE_DATE { get; set; }
        
    /// <summary>
    ///车辆VIN
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///生产日
    /// </summary>
    public System.DateTime PRODUCE_DAY { get; set; }
        
    /// <summary>
    ///销售日
    /// </summary>
    public System.DateTime SALE_DAY { get; set; }
        
    /// <summary>
    ///故障日
    /// </summary>
    public System.DateTime FAULT_DAY { get; set; }
        
    /// <summary>
    ///DTR修理日
    /// </summary>
    public System.DateTime DTR_REP_DAY { get; set; }
        
    /// <summary>
    ///故障里程(KM)
    /// </summary>
    public string FAULT_MILAGE { get; set; }
        
    /// <summary>
    ///专营店
    /// </summary>
    public string DLR { get; set; }
        
    /// <summary>
    ///调件依赖日
    /// </summary>
    public System.DateTime SP_DENP_DAY { get; set; }
        
    /// <summary>
    ///现品到达日
    /// </summary>
    public System.DateTime PART_ARR_DAY { get; set; }
        
    /// <summary>
    ///发生条件/发生现象
    /// </summary>
    public string HAP_PHE { get; set; }
        
    /// <summary>
    ///现车点检内容
    /// </summary>
    public string CAR_CHECK_CON { get; set; }
        
    /// <summary>
    ///发生原因
    /// </summary>
    public string HAP_SEASON { get; set; }
        
    /// <summary>
    ///流出防止日
    /// </summary>
    public System.DateTime EFFL_AVO_DAY { get; set; }
        
    /// <summary>
    ///流出防止对策
    /// </summary>
    public string EFFL_AVO_CMS { get; set; }
        
    /// <summary>
    ///暂定对策采用日
    /// </summary>
    public System.DateTime TEMP_CMS_APPL_DAY { get; set; }
        
    /// <summary>
    ///暂定对策
    /// </summary>
    public string TEMP_CMS { get; set; }
        
    /// <summary>
    ///暂定对策VIN
    /// </summary>
    public string TEMP_VIN { get; set; }
        
    /// <summary>
    ///恒久对策
    /// </summary>
    public string HAP_SEASON_CMS { get; set; }
        
    /// <summary>
    ///恒久对策VIN
    /// </summary>
    public string VIN_SND { get; set; }
        
    /// <summary>
    ///水平展开
    /// </summary>
    public string STANDAR_EXPAND { get; set; }
        
    /// <summary>
    ///本次对策适用车系
    /// </summary>
    public string CMS_CAR_TYPE { get; set; }
        
    /// <summary>
    ///对策采用日期
    /// </summary>
    public System.DateTime BEGIN_DO_TIME { get; set; }
        
    /// <summary>
    ///本次对策适用PFP
    /// </summary>
    public string CMS_CAR_PFP { get; set; }
        
    /// <summary>
    ///在库车辆处理完成日
    /// </summary>
    public System.DateTime IN_CAR_DEAL_DAY { get; set; }
        
    /// <summary>
    ///在库零件处理完成日
    /// </summary>
    public System.DateTime IN_MP_DEAL_DAY { get; set; }
        
    /// <summary>
    ///在库备件处理完成日
    /// </summary>
    public System.DateTime IN_PART_DEAL_DAY { get; set; }
        
    /// <summary>
    ///对策效果
    /// </summary>
    public decimal MEASURES_EFFECT { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///可用标记
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建时间:默认为系统时间；
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间:默认为系统时间；
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///SUPPLIER_SHORT_NAME
    /// </summary>
    public string SUPPLIER_SHORT_NAME { get; set; }
        
    /// <summary>
    ///SYS_DISTIN_CODE
    /// </summary>
    public string SYS_DISTIN_CODE { get; set; }
    }
}
