//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_PQ_BU_REJ_JUD_PART_BOX_V1
    /// </summary>
    public partial class T_PQ_BU_REJ_JUD_PART_BOX_V1
    {
        
    /// <summary>
    ///REJ_JUD_PART_BOX_ID
    /// </summary>
    public string REJ_JUD_PART_BOX_ID { get; set; }
        
    /// <summary>
    ///REJ_BILL_CODE
    /// </summary>
    public string REJ_BILL_CODE { get; set; }
        
    /// <summary>
    ///PART_BOX_CODE
    /// </summary>
    public string PART_BOX_CODE { get; set; }
        
    /// <summary>
    ///APPL_QTY
    /// </summary>
    public decimal APPL_QTY { get; set; }
        
    /// <summary>
    ///NG_QTY
    /// </summary>
    public decimal NG_QTY { get; set; }
        
    /// <summary>
    ///ORDER_NO
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///IS_ENABLE
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///CREATOR
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///CREATED_DATE
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///MODIFIER
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_DATE
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP_USER_ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP_ORG_ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///UPDATE_CONTROL_ID
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///REJ_BILL_CODE_APPL
    /// </summary>
    public string REJ_BILL_CODE_APPL { get; set; }
        
    /// <summary>
    ///DUTY_COMP_CODE
    /// </summary>
    public string DUTY_COMP_CODE { get; set; }
        
    /// <summary>
    ///DUTY_COMP_NAME
    /// </summary>
    public string DUTY_COMP_NAME { get; set; }
        
    /// <summary>
    ///BEAR_RATIO
    /// </summary>
    public decimal BEAR_RATIO { get; set; }
        
    /// <summary>
    ///BEAR_AMT_TOT
    /// </summary>
    public decimal BEAR_AMT_TOT { get; set; }
        
    /// <summary>
    ///DUTY_COMP_TYPE
    /// </summary>
    public string DUTY_COMP_TYPE { get; set; }
        
    /// <summary>
    ///CLAIM_TYPE
    /// </summary>
    public string CLAIM_TYPE { get; set; }
        
    /// <summary>
    ///DUTY_SEC_CODE
    /// </summary>
    public string DUTY_SEC_CODE { get; set; }
        
    /// <summary>
    ///BAD_DESC
    /// </summary>
    public string BAD_DESC { get; set; }
        
    /// <summary>
    ///CUR_STATUS
    /// </summary>
    public string CUR_STATUS { get; set; }
        
    /// <summary>
    ///DECI_MAN
    /// </summary>
    public string DECI_MAN { get; set; }
        
    /// <summary>
    ///DECI_TIME
    /// </summary>
    public System.DateTime DECI_TIME { get; set; }
        
    /// <summary>
    ///SCRAP_TYPE
    /// </summary>
    public string SCRAP_TYPE { get; set; }
        
    /// <summary>
    ///DUTY_COMP_TYPE_NAME
    /// </summary>
    public string DUTY_COMP_TYPE_NAME { get; set; }
        
    /// <summary>
    ///CLAIM_TYPE_NAME
    /// </summary>
    public string CLAIM_TYPE_NAME { get; set; }
        
    /// <summary>
    ///DUTY_SEC_NAME
    /// </summary>
    public string DUTY_SEC_NAME { get; set; }
        
    /// <summary>
    ///SUPPLIER_TYPE
    /// </summary>
    public string SUPPLIER_TYPE { get; set; }
    }
}
