//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_SQ_BU_SUP_IMP_ALERT_BAK1
    /// </summary>
    public partial class T_SQ_BU_SUP_IMP_ALERT_BAK1
    {
        
    /// <summary>
    ///SUP_IMP_ALERT_ID
    /// </summary>
    public string SUP_IMP_ALERT_ID { get; set; }
        
    /// <summary>
    ///CAR_BRAND
    /// </summary>
    public string CAR_BRAND { get; set; }
        
    /// <summary>
    ///ALERT_MON
    /// </summary>
    public string ALERT_MON { get; set; }
        
    /// <summary>
    ///SUPPLIER_CODE
    /// </summary>
    public string SUPPLIER_CODE { get; set; }
        
    /// <summary>
    ///SUPPLIER_NAME
    /// </summary>
    public string SUPPLIER_NAME { get; set; }
        
    /// <summary>
    ///SUPPLIER_RESP_MAN
    /// </summary>
    public string SUPPLIER_RESP_MAN { get; set; }
        
    /// <summary>
    ///POSITION_DESC
    /// </summary>
    public string POSITION_DESC { get; set; }
        
    /// <summary>
    ///EMAIL_ADD
    /// </summary>
    public string EMAIL_ADD { get; set; }
        
    /// <summary>
    ///TEL_NUM
    /// </summary>
    public string TEL_NUM { get; set; }
        
    /// <summary>
    ///ALERT_NOTICE_DATE
    /// </summary>
    public System.DateTime ALERT_NOTICE_DATE { get; set; }
        
    /// <summary>
    ///IMP_PLAN_RESP_DL
    /// </summary>
    public System.DateTime IMP_PLAN_RESP_DL { get; set; }
        
    /// <summary>
    ///IMP_PLAN_RESP_DATE
    /// </summary>
    public System.DateTime IMP_PLAN_RESP_DATE { get; set; }
        
    /// <summary>
    ///IMP_WAY
    /// </summary>
    public string IMP_WAY { get; set; }
        
    /// <summary>
    ///IMP_PLAN_CONF_DATE
    /// </summary>
    public System.DateTime IMP_PLAN_CONF_DATE { get; set; }
        
    /// <summary>
    ///IMP_CM_CONF_DATE
    /// </summary>
    public System.DateTime IMP_CM_CONF_DATE { get; set; }
        
    /// <summary>
    ///IMP_CM_CLOSE_DATE
    /// </summary>
    public System.DateTime IMP_CM_CLOSE_DATE { get; set; }
        
    /// <summary>
    ///IS_RELEASE
    /// </summary>
    public string IS_RELEASE { get; set; }
        
    /// <summary>
    ///ALERT_REL_NOTICE_DATE
    /// </summary>
    public System.DateTime ALERT_REL_NOTICE_DATE { get; set; }
        
    /// <summary>
    ///REMARK
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///AUDIT_TYPE
    /// </summary>
    public string AUDIT_TYPE { get; set; }
        
    /// <summary>
    ///AUDIT_UNIT
    /// </summary>
    public string AUDIT_UNIT { get; set; }
        
    /// <summary>
    ///APPROVAL_TIME
    /// </summary>
    public System.DateTime APPROVAL_TIME { get; set; }
        
    /// <summary>
    ///IMP_MAIN_CONT
    /// </summary>
    public string IMP_MAIN_CONT { get; set; }
        
    /// <summary>
    ///STATUS
    /// </summary>
    public string STATUS { get; set; }
        
    /// <summary>
    ///ORDER_NO
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///IS_ENABLE
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///CREATOR
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///CREATED_DATE
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///MODIFIER
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_DATE
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP_USER_ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP_ORG_ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///UPDATE_CONTROL_ID
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///ALERT_HAP_DATE
    /// </summary>
    public System.DateTime ALERT_HAP_DATE { get; set; }
        
    /// <summary>
    ///ALERT_BOOK_TYPE
    /// </summary>
    public string ALERT_BOOK_TYPE { get; set; }
        
    /// <summary>
    ///IMP_CONT_TYPE
    /// </summary>
    public string IMP_CONT_TYPE { get; set; }
        
    /// <summary>
    ///ISSUE_WAY
    /// </summary>
    public string ISSUE_WAY { get; set; }
        
    /// <summary>
    ///ALTER_ISSUE_MAN
    /// </summary>
    public string ALTER_ISSUE_MAN { get; set; }
        
    /// <summary>
    ///IMP_PLAN_RE_MAN
    /// </summary>
    public string IMP_PLAN_RE_MAN { get; set; }
        
    /// <summary>
    ///IMP_PLAN_COMF_MAN
    /// </summary>
    public string IMP_PLAN_COMF_MAN { get; set; }
        
    /// <summary>
    ///IMP_CM_COMF_MAN
    /// </summary>
    public string IMP_CM_COMF_MAN { get; set; }
        
    /// <summary>
    ///IMP_CM_CLOSE_MAN
    /// </summary>
    public string IMP_CM_CLOSE_MAN { get; set; }
        
    /// <summary>
    ///FACTORY_CODE
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///ALTER_TYPE_TIMES
    /// </summary>
    public decimal ALTER_TYPE_TIMES { get; set; }
        
    /// <summary>
    ///PRO_GROUP_MAN
    /// </summary>
    public string PRO_GROUP_MAN { get; set; }
        
    /// <summary>
    ///REJ_OPINION
    /// </summary>
    public string REJ_OPINION { get; set; }
        
    /// <summary>
    ///EVAL_TYPE
    /// </summary>
    public string EVAL_TYPE { get; set; }
    }
}
