//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///V3_T_BU_PQ_REJ_JG_APP_PRO
    /// </summary>
    public partial class V3_T_BU_PQ_REJ_JG_APP_PRO
    {
        
    /// <summary>
    ///所属工厂
    /// </summary>
    public string 所属工厂 { get; set; }
        
    /// <summary>
    ///不合格品单号
    /// </summary>
    public string 不合格品单号 { get; set; }
        
    /// <summary>
    ///主凶件号
    /// </summary>
    public string 主凶件号 { get; set; }
        
    /// <summary>
    ///主凶件名称
    /// </summary>
    public string 主凶件名称 { get; set; }
        
    /// <summary>
    ///供应商编码
    /// </summary>
    public string 供应商编码 { get; set; }
        
    /// <summary>
    ///是否有牵连件
    /// </summary>
    public string 是否有牵连件 { get; set; }
        
    /// <summary>
    ///保存用户
    /// </summary>
    public string 保存用户 { get; set; }
        
    /// <summary>
    ///保存时间
    /// </summary>
    public string 保存时间 { get; set; }
        
    /// <summary>
    ///UPDATE_CONTROL_ID
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///APP_MAN
    /// </summary>
    public string APP_MAN { get; set; }
        
    /// <summary>
    ///APP_DATE
    /// </summary>
    public System.DateTime APP_DATE { get; set; }
        
    /// <summary>
    ///REJ_BILL_CODE
    /// </summary>
    public string REJ_BILL_CODE { get; set; }
        
    /// <summary>
    ///BEL_FACT_CODE
    /// </summary>
    public string BEL_FACT_CODE { get; set; }
    }
}
