//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///V4_T_BU_PQ_REJ_JG_APP_PRO
    /// </summary>
    public partial class V4_T_BU_PQ_REJ_JG_APP_PRO
    {
        
    /// <summary>
    ///REJ_BILL_CODE
    /// </summary>
    public string REJ_BILL_CODE { get; set; }
        
    /// <summary>
    ///不合格品单号
    /// </summary>
    public string 不合格品单号 { get; set; }
        
    /// <summary>
    ///主凶件号
    /// </summary>
    public string 主凶件号 { get; set; }
        
    /// <summary>
    ///主凶件名称
    /// </summary>
    public string 主凶件名称 { get; set; }
        
    /// <summary>
    ///SUPPLIER_CODE
    /// </summary>
    public string SUPPLIER_CODE { get; set; }
        
    /// <summary>
    ///供应商编码
    /// </summary>
    public string 供应商编码 { get; set; }
        
    /// <summary>
    ///供应商名称
    /// </summary>
    public string 供应商名称 { get; set; }
        
    /// <summary>
    ///申请数量
    /// </summary>
    public string 申请数量 { get; set; }
        
    /// <summary>
    ///制造车系代码
    /// </summary>
    public string 制造车系代码 { get; set; }
        
    /// <summary>
    ///发生位置
    /// </summary>
    public string 发生位置 { get; set; }
        
    /// <summary>
    ///SAVE_POS
    /// </summary>
    public string SAVE_POS { get; set; }
        
    /// <summary>
    ///存放位置
    /// </summary>
    public string 存放位置 { get; set; }
        
    /// <summary>
    ///不良原因
    /// </summary>
    public string 不良原因 { get; set; }
        
    /// <summary>
    ///DUTY_COMP_CODE
    /// </summary>
    public string DUTY_COMP_CODE { get; set; }
        
    /// <summary>
    ///责任单位编码
    /// </summary>
    public string 责任单位编码 { get; set; }
        
    /// <summary>
    ///责任单位名称
    /// </summary>
    public string 责任单位名称 { get; set; }
        
    /// <summary>
    ///SECTION_ID
    /// </summary>
    public string SECTION_ID { get; set; }
        
    /// <summary>
    ///责任科室
    /// </summary>
    public string 责任科室 { get; set; }
        
    /// <summary>
    ///SCRAP_TYPE
    /// </summary>
    public string SCRAP_TYPE { get; set; }
        
    /// <summary>
    ///报废类型
    /// </summary>
    public string 报废类型 { get; set; }
        
    /// <summary>
    ///不良类别
    /// </summary>
    public string 不良类别 { get; set; }
        
    /// <summary>
    ///零部件NG数量
    /// </summary>
    public string 零部件NG数量 { get; set; }
        
    /// <summary>
    ///APP_TYPE
    /// </summary>
    public string APP_TYPE { get; set; }
        
    /// <summary>
    ///物料类型
    /// </summary>
    public string 物料类型 { get; set; }
        
    /// <summary>
    ///APP_DATE
    /// </summary>
    public System.DateTime APP_DATE { get; set; }
        
    /// <summary>
    ///申请日期
    /// </summary>
    public string 申请日期 { get; set; }
        
    /// <summary>
    ///申请人
    /// </summary>
    public string 申请人 { get; set; }
        
    /// <summary>
    ///判定日期
    /// </summary>
    public string 判定日期 { get; set; }
        
    /// <summary>
    ///判定人
    /// </summary>
    public string 判定人 { get; set; }
        
    /// <summary>
    ///RECY_DATE
    /// </summary>
    public System.DateTime RECY_DATE { get; set; }
        
    /// <summary>
    ///回收日期
    /// </summary>
    public string 回收日期 { get; set; }
        
    /// <summary>
    ///回收人
    /// </summary>
    public string 回收人 { get; set; }
        
    /// <summary>
    ///RECY_MAN_NAME
    /// </summary>
    public string RECY_MAN_NAME { get; set; }
        
    /// <summary>
    ///RECY_MAN
    /// </summary>
    public string RECY_MAN { get; set; }
        
    /// <summary>
    ///BEL_FACT_CODE
    /// </summary>
    public string BEL_FACT_CODE { get; set; }
        
    /// <summary>
    ///CUR_MAIN_PRO
    /// </summary>
    public string CUR_MAIN_PRO { get; set; }
        
    /// <summary>
    ///状态
    /// </summary>
    public string 状态 { get; set; }
    }
}
