//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///V6_T_BU_PQ_REJ_JG_APP_PRO
    /// </summary>
    public partial class V6_T_BU_PQ_REJ_JG_APP_PRO
    {
        
    /// <summary>
    ///REJ_JG_APP_PRO_ID
    /// </summary>
    public string REJ_JG_APP_PRO_ID { get; set; }
        
    /// <summary>
    ///PFP_CODE
    /// </summary>
    public string PFP_CODE { get; set; }
        
    /// <summary>
    ///PFP_NAME
    /// </summary>
    public string PFP_NAME { get; set; }
        
    /// <summary>
    ///SUPPLIER_CODE
    /// </summary>
    public string SUPPLIER_CODE { get; set; }
        
    /// <summary>
    ///CUR_MAIN_PRO
    /// </summary>
    public string CUR_MAIN_PRO { get; set; }
        
    /// <summary>
    ///编辑
    /// </summary>
    public string 编辑 { get; set; }
        
    /// <summary>
    ///提交申请
    /// </summary>
    public string 提交申请 { get; set; }
        
    /// <summary>
    ///申请单号
    /// </summary>
    public string 申请单号 { get; set; }
        
    /// <summary>
    ///主凶件号
    /// </summary>
    public string 主凶件号 { get; set; }
        
    /// <summary>
    ///主凶件名称
    /// </summary>
    public string 主凶件名称 { get; set; }
        
    /// <summary>
    ///数量
    /// </summary>
    public string 数量 { get; set; }
        
    /// <summary>
    ///物料类型
    /// </summary>
    public string 物料类型 { get; set; }
        
    /// <summary>
    ///返修工时费
    /// </summary>
    public string 返修工时费 { get; set; }
        
    /// <summary>
    ///返修工时费附件
    /// </summary>
    public string 返修工时费附件 { get; set; }
        
    /// <summary>
    ///停线费用
    /// </summary>
    public string 停线费用 { get; set; }
        
    /// <summary>
    ///停线费用附件
    /// </summary>
    public string 停线费用附件 { get; set; }
        
    /// <summary>
    ///其它费用
    /// </summary>
    public string 其它费用 { get; set; }
        
    /// <summary>
    ///其它费用附件
    /// </summary>
    public string 其它费用附件 { get; set; }
        
    /// <summary>
    ///FEE_ATTA_URLPATH1
    /// </summary>
    public string FEE_ATTA_URLPATH1 { get; set; }
        
    /// <summary>
    ///FEE_ATTA_URLPATH2
    /// </summary>
    public string FEE_ATTA_URLPATH2 { get; set; }
        
    /// <summary>
    ///FEE_ATTA_URLPATH3
    /// </summary>
    public string FEE_ATTA_URLPATH3 { get; set; }
        
    /// <summary>
    ///CUR_STATUS
    /// </summary>
    public string CUR_STATUS { get; set; }
        
    /// <summary>
    ///驳回原因
    /// </summary>
    public string 驳回原因 { get; set; }
        
    /// <summary>
    ///APP_DATE
    /// </summary>
    public System.DateTime APP_DATE { get; set; }
        
    /// <summary>
    ///JUDGE_DATE
    /// </summary>
    public System.DateTime JUDGE_DATE { get; set; }
        
    /// <summary>
    ///状态
    /// </summary>
    public string 状态 { get; set; }
        
    /// <summary>
    ///APP_MAN_NAME
    /// </summary>
    public string APP_MAN_NAME { get; set; }
        
    /// <summary>
    ///JUDGE_MAN_NAME
    /// </summary>
    public string JUDGE_MAN_NAME { get; set; }
        
    /// <summary>
    ///申请人
    /// </summary>
    public string 申请人 { get; set; }
        
    /// <summary>
    ///申请日期
    /// </summary>
    public string 申请日期 { get; set; }
        
    /// <summary>
    ///判定人
    /// </summary>
    public string 判定人 { get; set; }
        
    /// <summary>
    ///判定日期
    /// </summary>
    public System.DateTime 判定日期 { get; set; }
    }
}
