//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///V_COP_ASSEMBLY
    /// </summary>
    public partial class V_COP_ASSEMBLY
    {
        
    /// <summary>
    ///ASSEMBLY_ID
    /// </summary>
    public string ASSEMBLY_ID { get; set; }
        
    /// <summary>
    ///ASSEMBLY_CODE
    /// </summary>
    public string ASSEMBLY_CODE { get; set; }
        
    /// <summary>
    ///ASSEMBLY_NAME
    /// </summary>
    public string ASSEMBLY_NAME { get; set; }
        
    /// <summary>
    ///ORDER_NO
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///IS_ENABLE
    /// </summary>
    public string IS_ENABLE { get; set; }
    }
}
