//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///V_COP_PART_C_M_S_CODE
    /// </summary>
    public partial class V_COP_PART_C_M_S_CODE
    {
        
    /// <summary>
    ///PART_NO
    /// </summary>
    public string PART_NO { get; set; }
        
    /// <summary>
    ///PART_NAME_CN
    /// </summary>
    public string PART_NAME_CN { get; set; }
        
    /// <summary>
    ///PART_NAME_EN
    /// </summary>
    public string PART_NAME_EN { get; set; }
        
    /// <summary>
    ///CAR_TYPE_SERIAL
    /// </summary>
    public string CAR_TYPE_SERIAL { get; set; }
        
    /// <summary>
    ///CCC_CERT_ID
    /// </summary>
    public string CCC_CERT_ID { get; set; }
        
    /// <summary>
    ///CCC_CERT_CODE
    /// </summary>
    public string CCC_CERT_CODE { get; set; }
        
    /// <summary>
    ///MODEL_SPEC_ID
    /// </summary>
    public string MODEL_SPEC_ID { get; set; }
        
    /// <summary>
    ///SPECIF_MODEL
    /// </summary>
    public string SPECIF_MODEL { get; set; }
        
    /// <summary>
    ///SUPPLIER_ID
    /// </summary>
    public string SUPPLIER_ID { get; set; }
        
    /// <summary>
    ///SUPPLIER_NAME
    /// </summary>
    public string SUPPLIER_NAME { get; set; }
        
    /// <summary>
    ///IS_ENABLE
    /// </summary>
    public string IS_ENABLE { get; set; }
    }
}
