//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///V_COP_DUTY_SEC_EMP_USER
    /// </summary>
    public partial class V_COP_DUTY_SEC_EMP_USER
    {
        
    /// <summary>
    ///USER_ID
    /// </summary>
    public string USER_ID { get; set; }
        
    /// <summary>
    ///USER_NAME
    /// </summary>
    public string USER_NAME { get; set; }
        
    /// <summary>
    ///USER_ROLE
    /// </summary>
    public string USER_ROLE { get; set; }
        
    /// <summary>
    ///INNER_DUTY_COMP_ID
    /// </summary>
    public string INNER_DUTY_COMP_ID { get; set; }
        
    /// <summary>
    ///DUTY_COMP_NAME
    /// </summary>
    public string DUTY_COMP_NAME { get; set; }
        
    /// <summary>
    ///INNER_COMP_SEC_ID
    /// </summary>
    public string INNER_COMP_SEC_ID { get; set; }
        
    /// <summary>
    ///SECTION_NAME
    /// </summary>
    public string SECTION_NAME { get; set; }
        
    /// <summary>
    ///EMP_ID
    /// </summary>
    public string EMP_ID { get; set; }
        
    /// <summary>
    ///EMP_NAME
    /// </summary>
    public string EMP_NAME { get; set; }
    }
}
