//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///V_IQS_FOLLOW_UP
    /// </summary>
    public partial class V_IQS_FOLLOW_UP
    {
        
    /// <summary>
    ///FOLLOW_ITEM_ID
    /// </summary>
    public string FOLLOW_ITEM_ID { get; set; }
        
    /// <summary>
    ///BILL_NO
    /// </summary>
    public string BILL_NO { get; set; }
        
    /// <summary>
    ///BILL_DATE
    /// </summary>
    public string BILL_DATE { get; set; }
        
    /// <summary>
    ///ITEM_CODE
    /// </summary>
    public string ITEM_CODE { get; set; }
        
    /// <summary>
    ///ITEM_DETAIL_CODE
    /// </summary>
    public string ITEM_DETAIL_CODE { get; set; }
        
    /// <summary>
    ///DUTY_COMP_TYPE
    /// </summary>
    public string DUTY_COMP_TYPE { get; set; }
        
    /// <summary>
    ///DUTY_COMP_CODE
    /// </summary>
    public string DUTY_COMP_CODE { get; set; }
        
    /// <summary>
    ///IMPORTANCE
    /// </summary>
    public string IMPORTANCE { get; set; }
        
    /// <summary>
    ///INVEST_NUM
    /// </summary>
    public decimal INVEST_NUM { get; set; }
        
    /// <summary>
    ///INVEST_UNIT
    /// </summary>
    public string INVEST_UNIT { get; set; }
        
    /// <summary>
    ///INVEST_START_DATE
    /// </summary>
    public string INVEST_START_DATE { get; set; }
        
    /// <summary>
    ///INVEST_END_DATE
    /// </summary>
    public string INVEST_END_DATE { get; set; }
        
    /// <summary>
    ///ITEM_WINDOW_MAN
    /// </summary>
    public string ITEM_WINDOW_MAN { get; set; }
        
    /// <summary>
    ///PRESENTER
    /// </summary>
    public string PRESENTER { get; set; }
        
    /// <summary>
    ///BILL_STATUS
    /// </summary>
    public string BILL_STATUS { get; set; }
        
    /// <summary>
    ///BILL_CREATED_DATE
    /// </summary>
    public System.DateTime BILL_CREATED_DATE { get; set; }
        
    /// <summary>
    ///ITEM_DETAIL_NAME_CN
    /// </summary>
    public string ITEM_DETAIL_NAME_CN { get; set; }
        
    /// <summary>
    ///ITEM_DETAIL_NAME_EN
    /// </summary>
    public string ITEM_DETAIL_NAME_EN { get; set; }
        
    /// <summary>
    ///FOLLOW_DETAIL_ID
    /// </summary>
    public string FOLLOW_DETAIL_ID { get; set; }
        
    /// <summary>
    ///VIN
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///IS_UNITE
    /// </summary>
    public string IS_UNITE { get; set; }
        
    /// <summary>
    ///UNITE_VISIT_ID
    /// </summary>
    public string UNITE_VISIT_ID { get; set; }
        
    /// <summary>
    ///RESERVE_STATE
    /// </summary>
    public string RESERVE_STATE { get; set; }
        
    /// <summary>
    ///RESERVE_DATE
    /// </summary>
    public System.DateTime RESERVE_DATE { get; set; }
        
    /// <summary>
    ///REMARK
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///UNION_START_DATE
    /// </summary>
    public string UNION_START_DATE { get; set; }
        
    /// <summary>
    ///UNION_END_DATE
    /// </summary>
    public string UNION_END_DATE { get; set; }
        
    /// <summary>
    ///TCS_SURE_MAN
    /// </summary>
    public string TCS_SURE_MAN { get; set; }
        
    /// <summary>
    ///TCS_SURE_DATE
    /// </summary>
    public System.DateTime TCS_SURE_DATE { get; set; }
        
    /// <summary>
    ///AS_ACCEPT_DATE
    /// </summary>
    public System.DateTime AS_ACCEPT_DATE { get; set; }
        
    /// <summary>
    ///AS_BACK_DATE
    /// </summary>
    public System.DateTime AS_BACK_DATE { get; set; }
        
    /// <summary>
    ///AS_BACK_MAN
    /// </summary>
    public string AS_BACK_MAN { get; set; }
        
    /// <summary>
    ///CLIENT_DATE
    /// </summary>
    public string CLIENT_DATE { get; set; }
        
    /// <summary>
    ///CLIENT_DATE_END
    /// </summary>
    public string CLIENT_DATE_END { get; set; }
        
    /// <summary>
    ///DLR_ID
    /// </summary>
    public string DLR_ID { get; set; }
        
    /// <summary>
    ///DLR_CODE
    /// </summary>
    public string DLR_CODE { get; set; }
        
    /// <summary>
    ///DLR_FULL_NAME
    /// </summary>
    public string DLR_FULL_NAME { get; set; }
        
    /// <summary>
    ///DLR_NAME
    /// </summary>
    public string DLR_NAME { get; set; }
        
    /// <summary>
    ///LINK_MAN
    /// </summary>
    public string LINK_MAN { get; set; }
        
    /// <summary>
    ///LINK_TEL
    /// </summary>
    public string LINK_TEL { get; set; }
        
    /// <summary>
    ///ADDR
    /// </summary>
    public string ADDR { get; set; }
        
    /// <summary>
    ///PROVINCE
    /// </summary>
    public string PROVINCE { get; set; }
        
    /// <summary>
    ///BRAND
    /// </summary>
    public string BRAND { get; set; }
        
    /// <summary>
    ///CITY
    /// </summary>
    public string CITY { get; set; }
        
    /// <summary>
    ///IQS_INVEST_REPORT_ID
    /// </summary>
    public string IQS_INVEST_REPORT_ID { get; set; }
        
    /// <summary>
    ///INVEST_TYPE
    /// </summary>
    public string INVEST_TYPE { get; set; }
        
    /// <summary>
    ///INVEST_PERIOD_NO
    /// </summary>
    public string INVEST_PERIOD_NO { get; set; }
        
    /// <summary>
    ///INVEST_DATE
    /// </summary>
    public string INVEST_DATE { get; set; }
        
    /// <summary>
    ///CAR_SERIES_CODE
    /// </summary>
    public string CAR_SERIES_CODE { get; set; }
        
    /// <summary>
    ///CUST_DESCRIPTION
    /// </summary>
    public string CUST_DESCRIPTION { get; set; }
        
    /// <summary>
    ///FAULT_PART_CODE
    /// </summary>
    public string FAULT_PART_CODE { get; set; }
        
    /// <summary>
    ///SEX
    /// </summary>
    public string SEX { get; set; }
        
    /// <summary>
    ///AGE
    /// </summary>
    public decimal AGE { get; set; }
        
    /// <summary>
    ///REAL_CONFIRM
    /// </summary>
    public string REAL_CONFIRM { get; set; }
        
    /// <summary>
    ///ANSWER_REPORT
    /// </summary>
    public string ANSWER_REPORT { get; set; }
        
    /// <summary>
    ///SCORE_BRIFE
    /// </summary>
    public string SCORE_BRIFE { get; set; }
        
    /// <summary>
    ///METHOLD_DIR
    /// </summary>
    public string METHOLD_DIR { get; set; }
        
    /// <summary>
    ///INVEST_KM
    /// </summary>
    public decimal INVEST_KM { get; set; }
        
    /// <summary>
    ///CAR_OWNER_NAME
    /// </summary>
    public string CAR_OWNER_NAME { get; set; }
        
    /// <summary>
    ///DRIVER_TIME_QTY
    /// </summary>
    public decimal DRIVER_TIME_QTY { get; set; }
        
    /// <summary>
    ///DEGREE
    /// </summary>
    public string DEGREE { get; set; }
        
    /// <summary>
    ///JOB
    /// </summary>
    public string JOB { get; set; }
        
    /// <summary>
    ///IS_MARRY
    /// </summary>
    public string IS_MARRY { get; set; }
        
    /// <summary>
    ///PASSEN_NUM
    /// </summary>
    public decimal PASSEN_NUM { get; set; }
        
    /// <summary>
    ///CAR_CARUSE
    /// </summary>
    public string CAR_CARUSE { get; set; }
        
    /// <summary>
    ///INVEST_DEAL_MAN
    /// </summary>
    public string INVEST_DEAL_MAN { get; set; }
        
    /// <summary>
    ///RECORDOR
    /// </summary>
    public string RECORDOR { get; set; }
        
    /// <summary>
    ///FIRST_FAULT_DATE
    /// </summary>
    public string FIRST_FAULT_DATE { get; set; }
        
    /// <summary>
    ///REPAIR_DATE
    /// </summary>
    public string REPAIR_DATE { get; set; }
        
    /// <summary>
    ///IS_REPAIR
    /// </summary>
    public string IS_REPAIR { get; set; }
        
    /// <summary>
    ///REPAIR_KM
    /// </summary>
    public decimal REPAIR_KM { get; set; }
        
    /// <summary>
    ///IS_DISC_AGAIN
    /// </summary>
    public string IS_DISC_AGAIN { get; set; }
        
    /// <summary>
    ///DEAL_FUNC
    /// </summary>
    public string DEAL_FUNC { get; set; }
        
    /// <summary>
    ///FIR_DEAL_FUNC
    /// </summary>
    public string FIR_DEAL_FUNC { get; set; }
        
    /// <summary>
    ///NOW_DEAL_FUNC
    /// </summary>
    public string NOW_DEAL_FUNC { get; set; }
        
    /// <summary>
    ///DEAL_RET
    /// </summary>
    public string DEAL_RET { get; set; }
        
    /// <summary>
    ///DEAL_REMARK
    /// </summary>
    public string DEAL_REMARK { get; set; }
        
    /// <summary>
    ///SUBMIT_FLAG
    /// </summary>
    public string SUBMIT_FLAG { get; set; }
        
    /// <summary>
    ///FOLLOW_ANSWERS_ID
    /// </summary>
    public string FOLLOW_ANSWERS_ID { get; set; }
        
    /// <summary>
    ///ANSWER_CREATED_DATE
    /// </summary>
    public System.DateTime ANSWER_CREATED_DATE { get; set; }
        
    /// <summary>
    ///ANSWER_CREATOR
    /// </summary>
    public string ANSWER_CREATOR { get; set; }
        
    /// <summary>
    ///ANSWER_SEX
    /// </summary>
    public string ANSWER_SEX { get; set; }
        
    /// <summary>
    ///ANSWER_AGE
    /// </summary>
    public decimal ANSWER_AGE { get; set; }
        
    /// <summary>
    ///ANSWER_CITY
    /// </summary>
    public string ANSWER_CITY { get; set; }
        
    /// <summary>
    ///ANSWER_DLR_NAME
    /// </summary>
    public string ANSWER_DLR_NAME { get; set; }
        
    /// <summary>
    ///CUS_NO
    /// </summary>
    public string CUS_NO { get; set; }
        
    /// <summary>
    ///NDF
    /// </summary>
    public string NDF { get; set; }
        
    /// <summary>
    ///BI
    /// </summary>
    public string BI { get; set; }
    }
}
