//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///V_PTPQ_ASSECUSTOMINQUIRE01
    /// </summary>
    public partial class V_PTPQ_ASSECUSTOMINQUIRE01
    {
        
    /// <summary>
    ///PART_PROJ_ID
    /// </summary>
    public string PART_PROJ_ID { get; set; }
        
    /// <summary>
    ///FACTORY_CODE
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///FACTORY_NAME
    /// </summary>
    public string FACTORY_NAME { get; set; }
        
    /// <summary>
    ///PART_SORT
    /// </summary>
    public string PART_SORT { get; set; }
        
    /// <summary>
    ///PART_SORT_NAME
    /// </summary>
    public string PART_SORT_NAME { get; set; }
        
    /// <summary>
    ///PART_2D_CODE
    /// </summary>
    public string PART_2D_CODE { get; set; }
        
    /// <summary>
    ///PART_STATUS
    /// </summary>
    public string PART_STATUS { get; set; }
        
    /// <summary>
    ///PART_STATUS_NAME
    /// </summary>
    public string PART_STATUS_NAME { get; set; }
        
    /// <summary>
    ///PACK_LABEL_CODE
    /// </summary>
    public string PACK_LABEL_CODE { get; set; }
        
    /// <summary>
    ///ENGINE_NO
    /// </summary>
    public string ENGINE_NO { get; set; }
        
    /// <summary>
    ///MAC_TYPE
    /// </summary>
    public string MAC_TYPE { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///PRO_LINE_NAME
    /// </summary>
    public string PRO_LINE_NAME { get; set; }
        
    /// <summary>
    ///MOLD_CODE
    /// </summary>
    public string MOLD_CODE { get; set; }
        
    /// <summary>
    ///PART_NO
    /// </summary>
    public string PART_NO { get; set; }
        
    /// <summary>
    ///PART_NAME
    /// </summary>
    public string PART_NAME { get; set; }
        
    /// <summary>
    ///BAD_BIG_TYPE
    /// </summary>
    public string BAD_BIG_TYPE { get; set; }
        
    /// <summary>
    ///BAD_BIG_TYPE_NAME
    /// </summary>
    public string BAD_BIG_TYPE_NAME { get; set; }
        
    /// <summary>
    ///BAD_TYPE
    /// </summary>
    public string BAD_TYPE { get; set; }
        
    /// <summary>
    ///BAD_TYPE_NAME
    /// </summary>
    public string BAD_TYPE_NAME { get; set; }
        
    /// <summary>
    ///LOGIC_STATUS
    /// </summary>
    public short LOGIC_STATUS { get; set; }
        
    /// <summary>
    ///STATUS_CHANGE_NUM
    /// </summary>
    public int STATUS_CHANGE_NUM { get; set; }
        
    /// <summary>
    ///STATUS_CHANGE_SOURCE
    /// </summary>
    public string STATUS_CHANGE_SOURCE { get; set; }
        
    /// <summary>
    ///STATUS_CHANGE_MAN
    /// </summary>
    public string STATUS_CHANGE_MAN { get; set; }
        
    /// <summary>
    ///CHANGE_TIME
    /// </summary>
    public System.DateTime CHANGE_TIME { get; set; }
        
    /// <summary>
    ///CHANGE_BAT
    /// </summary>
    public string CHANGE_BAT { get; set; }
        
    /// <summary>
    ///CHANGE_REMARK
    /// </summary>
    public string CHANGE_REMARK { get; set; }
        
    /// <summary>
    ///DECI_PROCESS
    /// </summary>
    public string DECI_PROCESS { get; set; }
        
    /// <summary>
    ///DUTY_DEPT
    /// </summary>
    public string DUTY_DEPT { get; set; }
        
    /// <summary>
    ///DUTY_DEPT_NAME
    /// </summary>
    public string DUTY_DEPT_NAME { get; set; }
        
    /// <summary>
    ///DECI_LOGIC_PROCESS
    /// </summary>
    public string DECI_LOGIC_PROCESS { get; set; }
        
    /// <summary>
    ///DECI_LOGIC_PROCESS_NAME
    /// </summary>
    public string DECI_LOGIC_PROCESS_NAME { get; set; }
        
    /// <summary>
    ///PART_PROJ_ID100C
    /// </summary>
    public string PART_PROJ_ID100C { get; set; }
        
    /// <summary>
    ///PART_PROCESS_ID100C
    /// </summary>
    public string PART_PROCESS_ID100C { get; set; }
        
    /// <summary>
    ///PROCESS_CODE100C
    /// </summary>
    public string PROCESS_CODE100C { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS100C
    /// </summary>
    public string LOGIC_PROCESS100C { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS_N100C
    /// </summary>
    public string LOGIC_PROCESS_N100C { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE100C
    /// </summary>
    public string PRO_LINE_CODE100C { get; set; }
        
    /// <summary>
    ///PRO_LINE_NAME100C
    /// </summary>
    public string PRO_LINE_NAME100C { get; set; }
        
    /// <summary>
    ///PASS_MAC_TIME100C
    /// </summary>
    public System.DateTime PASS_MAC_TIME100C { get; set; }
        
    /// <summary>
    ///PROCESS_EQUIP_CODE100C
    /// </summary>
    public string PROCESS_EQUIP_CODE100C { get; set; }
        
    /// <summary>
    ///MOVE_OUT_TIME100C
    /// </summary>
    public System.DateTime MOVE_OUT_TIME100C { get; set; }
        
    /// <summary>
    ///BAT_BAR_CODE100C
    /// </summary>
    public string BAT_BAR_CODE100C { get; set; }
        
    /// <summary>
    ///PART_PROJ_ID200C
    /// </summary>
    public string PART_PROJ_ID200C { get; set; }
        
    /// <summary>
    ///PART_PROCESS_ID200C
    /// </summary>
    public string PART_PROCESS_ID200C { get; set; }
        
    /// <summary>
    ///PROCESS_CODE200C
    /// </summary>
    public string PROCESS_CODE200C { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS200C
    /// </summary>
    public string LOGIC_PROCESS200C { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS_N200C
    /// </summary>
    public string LOGIC_PROCESS_N200C { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE200C
    /// </summary>
    public string PRO_LINE_CODE200C { get; set; }
        
    /// <summary>
    ///PRO_LINE_NAME200C
    /// </summary>
    public string PRO_LINE_NAME200C { get; set; }
        
    /// <summary>
    ///PASS_MAC_TIME200C
    /// </summary>
    public System.DateTime PASS_MAC_TIME200C { get; set; }
        
    /// <summary>
    ///PROCESS_EQUIP_CODE200C
    /// </summary>
    public string PROCESS_EQUIP_CODE200C { get; set; }
        
    /// <summary>
    ///MOVE_IN_TIME200C
    /// </summary>
    public System.DateTime MOVE_IN_TIME200C { get; set; }
        
    /// <summary>
    ///CONN_ROD_HEAT_TIME200C
    /// </summary>
    public System.DateTime CONN_ROD_HEAT_TIME200C { get; set; }
        
    /// <summary>
    ///FLANGE_HEAT_TIME200C
    /// </summary>
    public System.DateTime FLANGE_HEAT_TIME200C { get; set; }
        
    /// <summary>
    ///SPINDLE_HEAT_TIME200C
    /// </summary>
    public System.DateTime SPINDLE_HEAT_TIME200C { get; set; }
        
    /// <summary>
    ///PART_PROJ_ID300C
    /// </summary>
    public string PART_PROJ_ID300C { get; set; }
        
    /// <summary>
    ///PART_PROCESS_ID300C
    /// </summary>
    public string PART_PROCESS_ID300C { get; set; }
        
    /// <summary>
    ///PROCESS_CODE300C
    /// </summary>
    public string PROCESS_CODE300C { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS300C
    /// </summary>
    public string LOGIC_PROCESS300C { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS_N300C
    /// </summary>
    public string LOGIC_PROCESS_N300C { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE300C
    /// </summary>
    public string PRO_LINE_CODE300C { get; set; }
        
    /// <summary>
    ///PRO_LINE_NAME300C
    /// </summary>
    public string PRO_LINE_NAME300C { get; set; }
        
    /// <summary>
    ///PASS_MAC_TIME300C
    /// </summary>
    public System.DateTime PASS_MAC_TIME300C { get; set; }
        
    /// <summary>
    ///PROCESS_EQUIP_CODE300C
    /// </summary>
    public string PROCESS_EQUIP_CODE300C { get; set; }
        
    /// <summary>
    ///MOVE_IN_TIME300C
    /// </summary>
    public System.DateTime MOVE_IN_TIME300C { get; set; }
        
    /// <summary>
    ///MOVE_OUT_TIME300C
    /// </summary>
    public System.DateTime MOVE_OUT_TIME300C { get; set; }
        
    /// <summary>
    ///PART_PROJ_ID400C
    /// </summary>
    public string PART_PROJ_ID400C { get; set; }
        
    /// <summary>
    ///PART_PROCESS_ID400C
    /// </summary>
    public string PART_PROCESS_ID400C { get; set; }
        
    /// <summary>
    ///PROCESS_CODE400C
    /// </summary>
    public string PROCESS_CODE400C { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS400C
    /// </summary>
    public string LOGIC_PROCESS400C { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS_N400C
    /// </summary>
    public string LOGIC_PROCESS_N400C { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE400C
    /// </summary>
    public string PRO_LINE_CODE400C { get; set; }
        
    /// <summary>
    ///PRO_LINE_NAME400C
    /// </summary>
    public string PRO_LINE_NAME400C { get; set; }
        
    /// <summary>
    ///PASS_MAC_TIME400C
    /// </summary>
    public System.DateTime PASS_MAC_TIME400C { get; set; }
        
    /// <summary>
    ///PROCESS_EQUIP_CODE400C
    /// </summary>
    public string PROCESS_EQUIP_CODE400C { get; set; }
        
    /// <summary>
    ///MOVE_IN_TIME400C
    /// </summary>
    public System.DateTime MOVE_IN_TIME400C { get; set; }
        
    /// <summary>
    ///MOVE_OUT_TIME400C
    /// </summary>
    public System.DateTime MOVE_OUT_TIME400C { get; set; }
        
    /// <summary>
    ///PART_PROJ_ID600C
    /// </summary>
    public string PART_PROJ_ID600C { get; set; }
        
    /// <summary>
    ///PART_PROCESS_ID600C
    /// </summary>
    public string PART_PROCESS_ID600C { get; set; }
        
    /// <summary>
    ///PROCESS_CODE600C
    /// </summary>
    public string PROCESS_CODE600C { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS600C
    /// </summary>
    public string LOGIC_PROCESS600C { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS_N600C
    /// </summary>
    public string LOGIC_PROCESS_N600C { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE600C
    /// </summary>
    public string PRO_LINE_CODE600C { get; set; }
        
    /// <summary>
    ///PRO_LINE_NAME600C
    /// </summary>
    public string PRO_LINE_NAME600C { get; set; }
        
    /// <summary>
    ///PASS_MAC_TIME600C
    /// </summary>
    public System.DateTime PASS_MAC_TIME600C { get; set; }
        
    /// <summary>
    ///PROCESS_EQUIP_CODE600C
    /// </summary>
    public string PROCESS_EQUIP_CODE600C { get; set; }
        
    /// <summary>
    ///MOVE_IN_TIME600C
    /// </summary>
    public System.DateTime MOVE_IN_TIME600C { get; set; }
        
    /// <summary>
    ///MOVE_OUT_TIME600C
    /// </summary>
    public System.DateTime MOVE_OUT_TIME600C { get; set; }
        
    /// <summary>
    ///PART_PROJ_ID700C
    /// </summary>
    public string PART_PROJ_ID700C { get; set; }
        
    /// <summary>
    ///PART_PROCESS_ID700C
    /// </summary>
    public string PART_PROCESS_ID700C { get; set; }
        
    /// <summary>
    ///PROCESS_CODE700C
    /// </summary>
    public string PROCESS_CODE700C { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS700C
    /// </summary>
    public string LOGIC_PROCESS700C { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS_N700C
    /// </summary>
    public string LOGIC_PROCESS_N700C { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE700C
    /// </summary>
    public string PRO_LINE_CODE700C { get; set; }
        
    /// <summary>
    ///PRO_LINE_NAME700C
    /// </summary>
    public string PRO_LINE_NAME700C { get; set; }
        
    /// <summary>
    ///PASS_MAC_TIME700C
    /// </summary>
    public System.DateTime PASS_MAC_TIME700C { get; set; }
        
    /// <summary>
    ///PROCESS_EQUIP_CODE700C
    /// </summary>
    public string PROCESS_EQUIP_CODE700C { get; set; }
        
    /// <summary>
    ///MOVE_IN_TIME700C
    /// </summary>
    public System.DateTime MOVE_IN_TIME700C { get; set; }
        
    /// <summary>
    ///MOVE_OUT_TIME700C
    /// </summary>
    public System.DateTime MOVE_OUT_TIME700C { get; set; }
        
    /// <summary>
    ///PART_PROJ_ID800C
    /// </summary>
    public string PART_PROJ_ID800C { get; set; }
        
    /// <summary>
    ///PART_PROCESS_ID800C
    /// </summary>
    public string PART_PROCESS_ID800C { get; set; }
        
    /// <summary>
    ///PROCESS_CODE800C
    /// </summary>
    public string PROCESS_CODE800C { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS800C
    /// </summary>
    public string LOGIC_PROCESS800C { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS_N800C
    /// </summary>
    public string LOGIC_PROCESS_N800C { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE800C
    /// </summary>
    public string PRO_LINE_CODE800C { get; set; }
        
    /// <summary>
    ///PRO_LINE_NAME800C
    /// </summary>
    public string PRO_LINE_NAME800C { get; set; }
        
    /// <summary>
    ///PASS_MAC_TIME800C
    /// </summary>
    public System.DateTime PASS_MAC_TIME800C { get; set; }
        
    /// <summary>
    ///PROCESS_EQUIP_CODE800C
    /// </summary>
    public string PROCESS_EQUIP_CODE800C { get; set; }
        
    /// <summary>
    ///PROD_2D_CODE800C
    /// </summary>
    public string PROD_2D_CODE800C { get; set; }
        
    /// <summary>
    ///PROCESS_STATUS800C
    /// </summary>
    public string PROCESS_STATUS800C { get; set; }
        
    /// <summary>
    ///PROCESS_STATUS_NAME800C
    /// </summary>
    public string PROCESS_STATUS_NAME800C { get; set; }
        
    /// <summary>
    ///DIAMETER_M1_POS1800C
    /// </summary>
    public decimal DIAMETER_M1_POS1800C { get; set; }
        
    /// <summary>
    ///DIAMETER_M1_POS2800C
    /// </summary>
    public decimal DIAMETER_M1_POS2800C { get; set; }
        
    /// <summary>
    ///DIAMETER_M1_POS3800C
    /// </summary>
    public decimal DIAMETER_M1_POS3800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_M1_POS1800C
    /// </summary>
    public decimal ROUNDNESS_M1_POS1800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_M1_POS2800C
    /// </summary>
    public decimal ROUNDNESS_M1_POS2800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_M1_POS3800C
    /// </summary>
    public decimal ROUNDNESS_M1_POS3800C { get; set; }
        
    /// <summary>
    ///STRAIGHTNESS_M1800C
    /// </summary>
    public decimal STRAIGHTNESS_M1800C { get; set; }
        
    /// <summary>
    ///TAPER_M1800C
    /// </summary>
    public decimal TAPER_M1800C { get; set; }
        
    /// <summary>
    ///DIAMETER_M2_POS1800C
    /// </summary>
    public decimal DIAMETER_M2_POS1800C { get; set; }
        
    /// <summary>
    ///DIAMETER_M2_POS2800C
    /// </summary>
    public decimal DIAMETER_M2_POS2800C { get; set; }
        
    /// <summary>
    ///DIAMETER_M2_POS3800C
    /// </summary>
    public decimal DIAMETER_M2_POS3800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_M2_POS1800C
    /// </summary>
    public decimal ROUNDNESS_M2_POS1800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_M2_POS2800C
    /// </summary>
    public decimal ROUNDNESS_M2_POS2800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_M2_POS3800C
    /// </summary>
    public decimal ROUNDNESS_M2_POS3800C { get; set; }
        
    /// <summary>
    ///STRAIGHTNESS_M2800C
    /// </summary>
    public decimal STRAIGHTNESS_M2800C { get; set; }
        
    /// <summary>
    ///TAPER_M2800C
    /// </summary>
    public decimal TAPER_M2800C { get; set; }
        
    /// <summary>
    ///DIAMETER_M3_POS1800C
    /// </summary>
    public decimal DIAMETER_M3_POS1800C { get; set; }
        
    /// <summary>
    ///DIAMETER_M3_POS2800C
    /// </summary>
    public decimal DIAMETER_M3_POS2800C { get; set; }
        
    /// <summary>
    ///DIAMETER_M3_POS3800C
    /// </summary>
    public decimal DIAMETER_M3_POS3800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_M3_POS1800C
    /// </summary>
    public decimal ROUNDNESS_M3_POS1800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_M3_POS2800C
    /// </summary>
    public decimal ROUNDNESS_M3_POS2800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_M3_POS3800C
    /// </summary>
    public decimal ROUNDNESS_M3_POS3800C { get; set; }
        
    /// <summary>
    ///STRAIGHTNESS_M3800C
    /// </summary>
    public decimal STRAIGHTNESS_M3800C { get; set; }
        
    /// <summary>
    ///TAPER_M3800C
    /// </summary>
    public decimal TAPER_M3800C { get; set; }
        
    /// <summary>
    ///RUNOUT_M3800C
    /// </summary>
    public decimal RUNOUT_M3800C { get; set; }
        
    /// <summary>
    ///DIAMETER_M4_POS1800C
    /// </summary>
    public decimal DIAMETER_M4_POS1800C { get; set; }
        
    /// <summary>
    ///DIAMETER_M4_POS2800C
    /// </summary>
    public decimal DIAMETER_M4_POS2800C { get; set; }
        
    /// <summary>
    ///DIAMETER_M4_POS3800C
    /// </summary>
    public decimal DIAMETER_M4_POS3800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_M4_POS1800C
    /// </summary>
    public decimal ROUNDNESS_M4_POS1800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_M4_POS2800C
    /// </summary>
    public decimal ROUNDNESS_M4_POS2800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_M4_POS3800C
    /// </summary>
    public decimal ROUNDNESS_M4_POS3800C { get; set; }
        
    /// <summary>
    ///STRAIGHTNESS_M4800C
    /// </summary>
    public decimal STRAIGHTNESS_M4800C { get; set; }
        
    /// <summary>
    ///TAPER_M4800C
    /// </summary>
    public decimal TAPER_M4800C { get; set; }
        
    /// <summary>
    ///DIAMETER_M5_POS1800C
    /// </summary>
    public decimal DIAMETER_M5_POS1800C { get; set; }
        
    /// <summary>
    ///DIAMETER_M5_POS2800C
    /// </summary>
    public decimal DIAMETER_M5_POS2800C { get; set; }
        
    /// <summary>
    ///DIAMETER_M5_POS3800C
    /// </summary>
    public decimal DIAMETER_M5_POS3800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_M5_POS1800C
    /// </summary>
    public decimal ROUNDNESS_M5_POS1800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_M5_POS2800C
    /// </summary>
    public decimal ROUNDNESS_M5_POS2800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_M5_POS3800C
    /// </summary>
    public decimal ROUNDNESS_M5_POS3800C { get; set; }
        
    /// <summary>
    ///STRAIGHTNESS_M5800C
    /// </summary>
    public decimal STRAIGHTNESS_M5800C { get; set; }
        
    /// <summary>
    ///TAPER_M5800C
    /// </summary>
    public decimal TAPER_M5800C { get; set; }
        
    /// <summary>
    ///DIAMETER_P1_POS1800C
    /// </summary>
    public decimal DIAMETER_P1_POS1800C { get; set; }
        
    /// <summary>
    ///DIAMETER_P1_POS2800C
    /// </summary>
    public decimal DIAMETER_P1_POS2800C { get; set; }
        
    /// <summary>
    ///DIAMETER_P1_POS3800C
    /// </summary>
    public decimal DIAMETER_P1_POS3800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_P1_POS1800C
    /// </summary>
    public decimal ROUNDNESS_P1_POS1800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_P1_POS2800C
    /// </summary>
    public decimal ROUNDNESS_P1_POS2800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_P1_POS3800C
    /// </summary>
    public decimal ROUNDNESS_P1_POS3800C { get; set; }
        
    /// <summary>
    ///STRAIGHTNESS_P1800C
    /// </summary>
    public decimal STRAIGHTNESS_P1800C { get; set; }
        
    /// <summary>
    ///TAPER_P1800C
    /// </summary>
    public decimal TAPER_P1800C { get; set; }
        
    /// <summary>
    ///PARAL_P1_TO_M1_M5800C
    /// </summary>
    public decimal PARAL_P1_TO_M1_M5800C { get; set; }
        
    /// <summary>
    ///DIAMETER_P2_POS1800C
    /// </summary>
    public decimal DIAMETER_P2_POS1800C { get; set; }
        
    /// <summary>
    ///DIAMETER_P2_POS2800C
    /// </summary>
    public decimal DIAMETER_P2_POS2800C { get; set; }
        
    /// <summary>
    ///DIAMETER_P2_POS3800C
    /// </summary>
    public decimal DIAMETER_P2_POS3800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_P2_POS1800C
    /// </summary>
    public decimal ROUNDNESS_P2_POS1800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_P2_POS2800C
    /// </summary>
    public decimal ROUNDNESS_P2_POS2800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_P2_POS3800C
    /// </summary>
    public decimal ROUNDNESS_P2_POS3800C { get; set; }
        
    /// <summary>
    ///STRAIGHTNESS_P2800C
    /// </summary>
    public decimal STRAIGHTNESS_P2800C { get; set; }
        
    /// <summary>
    ///TAPER_P2800C
    /// </summary>
    public decimal TAPER_P2800C { get; set; }
        
    /// <summary>
    ///PARAL_P2_TO_M1_M5800C
    /// </summary>
    public decimal PARAL_P2_TO_M1_M5800C { get; set; }
        
    /// <summary>
    ///DIAMETER_P3_POS1800C
    /// </summary>
    public decimal DIAMETER_P3_POS1800C { get; set; }
        
    /// <summary>
    ///DIAMETER_P3_POS2800C
    /// </summary>
    public decimal DIAMETER_P3_POS2800C { get; set; }
        
    /// <summary>
    ///DIAMETER_P3_POS3800C
    /// </summary>
    public decimal DIAMETER_P3_POS3800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_P3_POS1800C
    /// </summary>
    public decimal ROUNDNESS_P3_POS1800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_P3_POS2800C
    /// </summary>
    public decimal ROUNDNESS_P3_POS2800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_P3_POS3800C
    /// </summary>
    public decimal ROUNDNESS_P3_POS3800C { get; set; }
        
    /// <summary>
    ///STRAIGHTNESS_P3800C
    /// </summary>
    public decimal STRAIGHTNESS_P3800C { get; set; }
        
    /// <summary>
    ///TAPER_P3800C
    /// </summary>
    public decimal TAPER_P3800C { get; set; }
        
    /// <summary>
    ///PARAL_P3_TO_M1_M5800C
    /// </summary>
    public decimal PARAL_P3_TO_M1_M5800C { get; set; }
        
    /// <summary>
    ///DIAMETER_P4_POS1800C
    /// </summary>
    public decimal DIAMETER_P4_POS1800C { get; set; }
        
    /// <summary>
    ///DIAMETER_P4_POS2800C
    /// </summary>
    public decimal DIAMETER_P4_POS2800C { get; set; }
        
    /// <summary>
    ///DIAMETER_P4_POS3800C
    /// </summary>
    public decimal DIAMETER_P4_POS3800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_P4_POS1800C
    /// </summary>
    public decimal ROUNDNESS_P4_POS1800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_P4_POS2800C
    /// </summary>
    public decimal ROUNDNESS_P4_POS2800C { get; set; }
        
    /// <summary>
    ///ROUNDNESS_P4_POS3800C
    /// </summary>
    public decimal ROUNDNESS_P4_POS3800C { get; set; }
        
    /// <summary>
    ///STRAIGHTNESS_P4800C
    /// </summary>
    public decimal STRAIGHTNESS_P4800C { get; set; }
        
    /// <summary>
    ///TAPER_P4800C
    /// </summary>
    public decimal TAPER_P4800C { get; set; }
        
    /// <summary>
    ///PARAL_P4_TO_M1_M5800C
    /// </summary>
    public decimal PARAL_P4_TO_M1_M5800C { get; set; }
        
    /// <summary>
    ///DIAMETER_FLANGE800C
    /// </summary>
    public decimal DIAMETER_FLANGE800C { get; set; }
        
    /// <summary>
    ///M1_DIA_CLASS800C
    /// </summary>
    public decimal M1_DIA_CLASS800C { get; set; }
        
    /// <summary>
    ///M2_DIA_CLASS800C
    /// </summary>
    public decimal M2_DIA_CLASS800C { get; set; }
        
    /// <summary>
    ///M3_DIA_CLASS800C
    /// </summary>
    public decimal M3_DIA_CLASS800C { get; set; }
        
    /// <summary>
    ///M4_DIA_CLASS800C
    /// </summary>
    public decimal M4_DIA_CLASS800C { get; set; }
        
    /// <summary>
    ///M5_DIA_CLASS800C
    /// </summary>
    public decimal M5_DIA_CLASS800C { get; set; }
        
    /// <summary>
    ///P1_DIA_CLASS800C
    /// </summary>
    public decimal P1_DIA_CLASS800C { get; set; }
        
    /// <summary>
    ///P2_DIA_CLASS800C
    /// </summary>
    public decimal P2_DIA_CLASS800C { get; set; }
        
    /// <summary>
    ///P3_DIA_CLASS800C
    /// </summary>
    public decimal P3_DIA_CLASS800C { get; set; }
        
    /// <summary>
    ///P4_DIA_CLASS800C
    /// </summary>
    public decimal P4_DIA_CLASS800C { get; set; }
        
    /// <summary>
    ///RUNOUT_M2800C
    /// </summary>
    public decimal RUNOUT_M2800C { get; set; }
        
    /// <summary>
    ///RUNOUT_M4800C
    /// </summary>
    public decimal RUNOUT_M4800C { get; set; }
        
    /// <summary>
    ///RUNOUT_M1800C
    /// </summary>
    public decimal RUNOUT_M1800C { get; set; }
        
    /// <summary>
    ///RUNOUT_M5800C
    /// </summary>
    public decimal RUNOUT_M5800C { get; set; }
    }
}
