//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_PROD_GROUP_CM
    {
        public string PROD_GROUP_CM_ID { get; set; }
        public string QUES_DATA_TAB { get; set; }
        public string QUES_DATA_ID { get; set; }
        public string HAP_STAT { get; set; }
        public string DUTY_MAN { get; set; }
        public string REASON_DESC { get; set; }
        public string CM_DESC { get; set; }
        public string DUTY_TAKE_MAN { get; set; }
        public string IS_BASE_UPD { get; set; }
        public string IS_OPL_EDU { get; set; }
        public string IS_MANA_PROJ { get; set; }
        public string WORK_OBSERVE { get; set; }
        public Nullable<System.DateTime> PLAN_FINISHED_DATE { get; set; }
        public Nullable<System.DateTime> FINISHED_WARN_DATE { get; set; }
        public string EFFECT_CONF_SCHE { get; set; }
        public string EFFECT_CONF_MAN { get; set; }
        public string EFFECT_CONF_REMARK { get; set; }
        public string CM_RECORD_MAN { get; set; }
        public Nullable<System.DateTime> CM_RECORD_DATE { get; set; }
        public string DISTRI_MAN { get; set; }
        public Nullable<System.DateTime> DISTRI_DATE { get; set; }
        public string DISTRI_GROUP_CODE { get; set; }
        public string CUR_STATUS { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string TRACK_BEGIN_DATE { get; set; }
        public string TRACK_END_DATE { get; set; }
        public string EFFE_RECORD { get; set; }
    }
}
