//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_MAIL_RECORD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PQ_BU_MAIL_RECORD()
        {
            this.T_PQ_BU_MAIL_ATTA = new HashSet<T_PQ_BU_MAIL_ATTA>();
        }
    
        public string MAIL_RECORD_ID { get; set; }
        public string REC_EMAIL { get; set; }
        public string IS_SEND_EMAIL { get; set; }
        public System.DateTime SEND_TIME { get; set; }
        public string SEND_TOPIC { get; set; }
        public string MAIL_TYPE_CODE { get; set; }
        public string IS_ATTA { get; set; }
        public System.DateTime GENERATE_TIME { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string SEND_CONT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_BU_MAIL_ATTA> T_PQ_BU_MAIL_ATTA { get; set; }
    }
}
