//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_EMPTY_CARPORT
    {
        public string EMPTY_CARPORT_ID { get; set; }
        public string EMPTY_CODE { get; set; }
        public string TRIM_SERIAL_NO { get; set; }
        public string CTRLKEY { get; set; }
        public string RECEIVE_DATE { get; set; }
        public string VIN { get; set; }
        public string IS_EMPTY { get; set; }
        public string FACTORY_CODE { get; set; }
        public Nullable<System.DateTime> HZ_OUT_TIME { get; set; }
        public Nullable<System.DateTime> TZ_OUT_TIME { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string SERIAL_CODE { get; set; }
        public Nullable<System.DateTime> PBS_OUT_TIME { get; set; }
    }
}
