//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_COLLAPSE_MEAS_REP
    {
        public string COLLAPSE_MEAS_REP_ID { get; set; }
        public string COLLAPSE_MEAS_REP_CODE { get; set; }
        public string CRAFT_CODE { get; set; }
        public string COLLAPSE_TAR { get; set; }
        public Nullable<System.DateTime> COLLAPSE_BEGIN_DATE { get; set; }
        public Nullable<System.DateTime> COLLAPSE_END_DATE { get; set; }
        public string COLLAPSE_MAN { get; set; }
        public string MEASURE_TOOL { get; set; }
        public string CAR_TYPE_CODE { get; set; }
        public string WORKSHOP_CODE { get; set; }
        public Nullable<System.DateTime> PRODUCE_DATE { get; set; }
        public string ELECTRO_VOLTAGE { get; set; }
        public Nullable<decimal> NV_VAL { get; set; }
        public string ELECTRO_DATE { get; set; }
        public Nullable<decimal> MEQ_VAL { get; set; }
        public Nullable<decimal> CELL_TEMP { get; set; }
        public string ELEC_PAINT_TYPE { get; set; }
        public string ELEC_COND_RATE { get; set; }
        public string COLLAPSE_ELEC_THICK { get; set; }
        public string COLLAPSE_ELEC_PAINT { get; set; }
        public string ATTA_FILE { get; set; }
        public string MAINSEND_UNIT { get; set; }
        public string CHECK_UNIT { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
    }
}
