//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_CAR_PROD_PLAN_M
    {
        public string CAR_PROD_PLAN_M_ID { get; set; }
        public string FACTORY_CODE { get; set; }
        public string PROC_CODE { get; set; }
        public string MANAGE_CODE { get; set; }
        public string EIGTEEN_CODE { get; set; }
        public string PAINT_COLOR_CODE { get; set; }
        public string INNER_COLOR_CODE { get; set; }
        public Nullable<System.DateTime> MS_OFFLINE_DATE { get; set; }
        public string VIN { get; set; }
        public string ENGINE_NO { get; set; }
        public string BASE_SERIES_CODE { get; set; }
        public string CAR_SERIES_CODE { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string ACT_VAL { get; set; }
        public string RE_ORDER { get; set; }
        public string FACTORY_NOW_LOC { get; set; }
        public string SET_PLAN_DATE { get; set; }
        public string SET_PLAN_SCHEDULE { get; set; }
        public string SOLDER_PLAN_DATE { get; set; }
        public string SOLDER_PLAN_SCHEDULE { get; set; }
        public string PAINT_PLAN_DATE { get; set; }
        public string PAINT_PLAN_SCHEDULE { get; set; }
        public string INSTALL_PLAN_DATE { get; set; }
        public string INSTALL_PLAN_SCHEDULE { get; set; }
        public string OFFLINE_PLAN_DATE { get; set; }
        public string OFFLINE_PLAN_SCHEDULE { get; set; }
        public string FINAL_CHECK_DATE { get; set; }
        public string FINAL_CHECK_SCHEDULE { get; set; }
        public string DELIVERY_PLAN_DATE { get; set; }
        public string DELIVERY_PLAN_SCHEDULE { get; set; }
        public string ORDER_VAL { get; set; }
        public string ORDER_VAL1 { get; set; }
        public string MATCH_STATUS { get; set; }
    }
}
