//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_QUALITY_INDEX_IMP
    {
        public string QUALITY_INDEX_IMP_ID { get; set; }
        public string FACTORY_CODE { get; set; }
        public string CAR_TYPE_CODE { get; set; }
        public string DATE_VAL { get; set; }
        public string INDEX_TYPE { get; set; }
        public string PROJ_TYPE { get; set; }
        public string MANAGE_PROJ { get; set; }
        public Nullable<decimal> MOLECULAR_VAL { get; set; }
        public Nullable<decimal> DENOMINATOR_VAL { get; set; }
        public string CREATOR { get; set; }
        public string BATCHNO { get; set; }
        public string ERROR_MESSAGE { get; set; }
    }
}
