//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HD2_PART_POINT
    {
        public string PART_POS { get; set; }
        public string CAR_TYPE_CODE { get; set; }
        public string TEST_TYPE_PA { get; set; }
        public string TEST_TYPE_PT { get; set; }
        public string POS_ID { get; set; }
        public string POS_NAME { get; set; }
        public string RL_VAL { get; set; }
        public string DIRECTION { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> CHECK_SPEC_SUBTRA { get; set; }
        public Nullable<decimal> CHECK_SPEC_SUBTRA2 { get; set; }
        public Nullable<decimal> CHECK_SPEC_ADD { get; set; }
        public Nullable<decimal> CHECK_SPEC_ADD2 { get; set; }
        public Nullable<decimal> INNER_SPEC_ADD { get; set; }
        public Nullable<decimal> INNER_SPEC_SUBTRA { get; set; }
        public Nullable<decimal> INNER_SPEC_ADD2 { get; set; }
        public Nullable<decimal> INNER_SPEC_SUBTRA2 { get; set; }
        public string BA_POINT_MEAS_ID { get; set; }
        public string BA_PART_MEAS_ID { get; set; }
        public string ATTRIBUTE_VAL { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string BELONG_PART_CODE { get; set; }
        public string BELONG_PART_NAME { get; set; }
        public string BELONG_PART_SUPPLIER { get; set; }
        public string MANAGE_TEAM { get; set; }
        public string CLAMP_MANGE_CLAMP_NAME { get; set; }
        public string CLAMP_MANGE_MANGE_UNIT { get; set; }
        public string AFFECT_OBJ_MAIN { get; set; }
        public string AFFECT_OBJ_SEC { get; set; }
        public string PART_POS_R { get; set; }
    }
}
