//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DB_DB_IP_INFO2016
    {
        public string IP_INFO_ID { get; set; }
        public string VIN { get; set; }
        public string IP_CODE { get; set; }
        public string PART_NO { get; set; }
        public string PART_CODE_ORDER { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string PART_NAME { get; set; }
        public string ENTRY_DATE { get; set; }
        public string PLACE_CODE { get; set; }
        public string IN_STORE_DATE { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string SYS_MODULE { get; set; }
        public string ENTRY_CLERK { get; set; }
        public string IN_STORE_MAN { get; set; }
        public Nullable<int> SEQ_NUM { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string FACTORY_CODE { get; set; }
        public string TIRE_UNIF_STATUS { get; set; }
    }
}
