//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DB_DB_FACTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_DB_DB_FACTORY()
        {
            this.T_DB_DB_FAC_LINK_MAN_INFO = new HashSet<T_DB_DB_FAC_LINK_MAN_INFO>();
            this.T_DB_DB_FAC_SEC = new HashSet<T_DB_DB_FAC_SEC>();
        }
    
        public string FACTORY_ID { get; set; }
        public string SYSTEM_FAC_CODE { get; set; }
        public string SAP_FACTORY_CODE { get; set; }
        public string LOG_FAC_CODE { get; set; }
        public string FACTORY_S_NAME { get; set; }
        public string FACTORY_FULL_NAME { get; set; }
        public string TAXPAYER_ID { get; set; }
        public string ACCOUNT_BANK { get; set; }
        public string BANK_ACC { get; set; }
        public string FINAN_TEL { get; set; }
        public string INVOICE_REMARK { get; set; }
        public string COST_CENTER_CODE { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string FACTORY_S_NAME_EN { get; set; }
        public string FACTORY_CATE { get; set; }
        public string COP_FAC_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_DB_DB_FAC_LINK_MAN_INFO> T_DB_DB_FAC_LINK_MAN_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_DB_DB_FAC_SEC> T_DB_DB_FAC_SEC { get; set; }
    }
}
