//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DB_DB_ATTA_FILE
    {
        public string ATTA_FILE_ID { get; set; }
        public string FILE_SOURCE_BILL_TYPE { get; set; }
        public string FILE_SOURCE_BILL_ID { get; set; }
        public string FILE_SOURCE_TYPE { get; set; }
        public string FILE_PATH { get; set; }
        public string FILE_TYPE { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<decimal> FILE_SIZE { get; set; }
        public string ATTA_FILE_FLAG { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
    }
}
