//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DB_DB_PART_RANGE
    {
        public string PART_RANGE_ID { get; set; }
        public string KEY_FIVE_PART_NO { get; set; }
        public string KEY_PART_NAME_CN { get; set; }
        public string KEY_PART_NAME_EN { get; set; }
        public string IS_KEY_COMP { get; set; }
        public string CCC_SAME { get; set; }
        public string ENVIR_PROT_SAME { get; set; }
        public string NOTICE_SAME { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string EXPERIMENT_PROJ { get; set; }
        public string EXPERIMENT_FREQ { get; set; }
        public string EXPERIMENT_WAY { get; set; }
    }
}
