//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DB_BU_INSTRING_TMP
    {
        public string INSTRING_TMP_ID { get; set; }
        public string ITEM { get; set; }
        public string ITEM1 { get; set; }
        public string ITEM2 { get; set; }
        public string ITEM3 { get; set; }
        public string ITEM4 { get; set; }
        public string ITEM5 { get; set; }
        public string ITEM6 { get; set; }
        public string ITEM7 { get; set; }
        public string ITEM8 { get; set; }
        public string ITEM9 { get; set; }
        public string IS_DEL { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string GID { get; set; }
    }
}
