//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DB_DB_SUPPLIER
    {
        public string SUPPLIER_ID { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public string SUPPLIER_SHORT_NAME { get; set; }
        public string SUPPLIER_FULL_NAME { get; set; }
        public string SUPPLIER_TYPE { get; set; }
        public string SUPPLY_TYPE { get; set; }
        public string TAXPAYER_ID { get; set; }
        public string ACCOUNT_BANK { get; set; }
        public string BANK_ACC { get; set; }
        public string TEL_NUM { get; set; }
        public string INVOICE_REMARK { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string SAP_SUPPLIER_CODE { get; set; }
    }
}
