//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntiyForMeiCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_CONCURRENT_REQUESTS
    {
        public string ID { get; set; }
        public decimal REQUEST_ID { get; set; }
        public string BatchGuid { get; set; }
        public System.DateTime REQUEST_DATE { get; set; }
        public string REQUESTED_BY { get; set; }
        public string PHASE_CODE { get; set; }
        public string STATUS_CODE { get; set; }
        public decimal PRIORITY { get; set; }
        public System.DateTime REQUESTED_START_DATE { get; set; }
        public string HOLD_FLAG { get; set; }
        public string ALLOCATED_FLAG { get; set; }
        public string HAS_SUB_REQUEST { get; set; }
        public string IS_SUB_REQUEST { get; set; }
        public string RESPONSIBILITY_ID { get; set; }
        public string CONCURRENT_PROGRAM_ID { get; set; }
        public decimal NUMBER_OF_ARGUMENTS { get; set; }
        public string NLS_LANGUAGE { get; set; }
        public string NLS_TERRITORY { get; set; }
        public Nullable<decimal> PARENT_REQUEST_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> RESUBMIT_INTERVAL { get; set; }
        public string RESUBMIT_INTERVAL_UNIT_CODE { get; set; }
        public string RESUBMIT_INTERVAL_TYPE_CODE { get; set; }
        public string RESUBMITTED { get; set; }
        public Nullable<System.DateTime> SCHEDULE_START_DATE { get; set; }
        public Nullable<System.DateTime> SCHEDULE_END_DATE { get; set; }
        public string CONTROLLING_MANAGER { get; set; }
        public string NODE_NAME1 { get; set; }
        public Nullable<System.DateTime> ACTUAL_START_DATE { get; set; }
        public Nullable<System.DateTime> ACTUAL_COMPLETION_DATE { get; set; }
        public string COMPLETION_TEXT { get; set; }
        public string LOG_TEXT { get; set; }
        public string LOGFILE_NAME { get; set; }
        public string LOGFILE_NODE_NAME { get; set; }
        public string OUTPUT_TEXT { get; set; }
        public string OUTFILE_NAME { get; set; }
        public string OUTFILE_NODE_NAME { get; set; }
        public string ARGUMENT_TEXT { get; set; }
        public string ARGUMENT1 { get; set; }
        public string ARGUMENT2 { get; set; }
        public string ARGUMENT3 { get; set; }
        public string ARGUMENT4 { get; set; }
        public string ARGUMENT5 { get; set; }
        public string ARGUMENT6 { get; set; }
        public string ARGUMENT7 { get; set; }
        public string ARGUMENT8 { get; set; }
        public string ARGUMENT9 { get; set; }
        public string ARGUMENT10 { get; set; }
        public string ARGUMENT11 { get; set; }
        public string ARGUMENT12 { get; set; }
        public string ARGUMENT13 { get; set; }
        public string ARGUMENT14 { get; set; }
        public string ARGUMENT15 { get; set; }
        public string ARGUMENT16 { get; set; }
        public string ARGUMENT17 { get; set; }
        public string ARGUMENT18 { get; set; }
        public string ARGUMENT19 { get; set; }
        public string ARGUMENT20 { get; set; }
        public string ARGUMENT21 { get; set; }
        public string ARGUMENT22 { get; set; }
        public string ARGUMENT23 { get; set; }
        public string ARGUMENT24 { get; set; }
        public string ARGUMENT25 { get; set; }
        public string REQUEST_TYPE { get; set; }
        public string ORACLE_PROCESS_ID { get; set; }
        public string ORACLE_SESSION_ID { get; set; }
        public string OS_PROCESS_ID { get; set; }
        public string OUTPUT_FILE_TYPE { get; set; }
        public string INCREMENT_DATES { get; set; }
        public string ENABLE_TRACE { get; set; }
        public Nullable<decimal> RESUB_COUNT { get; set; }
        public string NLS_CODESET { get; set; }
        public Nullable<decimal> OFILE_SIZE { get; set; }
        public Nullable<decimal> LFILE_SIZE { get; set; }
        public Nullable<decimal> ROOT_REQUEST_ID { get; set; }
        public Nullable<decimal> RUNNING_TIME { get; set; }
        public Nullable<decimal> SID { get; set; }
        public Nullable<decimal> SERIAL_ { get; set; }
        public Nullable<decimal> INST_ID { get; set; }
        public string SCHEDULE_TYPE { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
    }
}
