//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntiyForMeiCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_REQUEST_SET_PROG_ARGS
    {
        public string ID { get; set; }
        public string REQUEST_SET_ID { get; set; }
        public string REQUEST_SET_PROGRAM_ID { get; set; }
        public string CONCURRENT_PARAMETER_ID { get; set; }
        public string DEFAULT_TYPE { get; set; }
        public string DEFAULT_VALUE { get; set; }
        public string UPDATE_FLAG { get; set; }
        public string SHARED_PARAMETER_NAME { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATED_BY { get; set; }
    }
}
