//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntiyForMeiCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_CONCURRENT_PROGRAMS_TL
    {
        public string ID { get; set; }
        public string CONCURRENT_PROGRAM_ID { get; set; }
        public string LANGUAGE { get; set; }
        public string SOURCE_LANG { get; set; }
        public string USER_CONCURRENT_PROGRAM_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
    }
}
