//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntiyForMeiCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_FLEX_VALUE_SETS
    {
        public string ID { get; set; }
        public string FLEX_VALUE_SET_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string VALIDATION_TYPE { get; set; }
        public string FORMAT_TYPE { get; set; }
        public decimal MAXIMUM_SIZE { get; set; }
        public string NUMBER_ONLY_FLAG { get; set; }
        public string UPPERCASE_ONLY_FLAG { get; set; }
        public string NUMERIC_MODE_ENABLED_FLAG { get; set; }
        public string MINIMUM_VALUE { get; set; }
        public string MAXIMUM_VALUE { get; set; }
        public Nullable<decimal> NUMBER_PRECISION { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATED_BY { get; set; }
    }
}
