//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntiyForMeiCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_MENUS_B
    {
        public string ID { get; set; }
        public string MENU_CODE { get; set; }
        public string MENU_TYPE { get; set; }
        public string PARENT_MENU_ID { get; set; }
        public string CHILD_MENU_FLAG { get; set; }
        public string FUNCTION_ID { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<int> MENU_SEQUENCE { get; set; }
        public string WINDOW_TYPE { get; set; }
        public Nullable<int> MENU_LEVEL_ID { get; set; }
        public string PARAMETERS { get; set; }
        public string APPLICATION_ID { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
    }
}
