//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntiyForMeiCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class PI_ITEM
    {
        public string ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public string SOURCE_BATCH_ID { get; set; }
        public Nullable<System.DateTime> INSERT_TIME { get; set; }
        public Nullable<System.DateTime> DEAL_TIME { get; set; }
        public string DEAL_FLAG { get; set; }
        public string GROUP_ID { get; set; }
        public string ACTION { get; set; }
        public string SUCCESS_FLAG { get; set; }
        public string FAIL_MESSAGE { get; set; }
        public string PLANT_CODE { get; set; }
        public string ITEM_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string DESCRIPTIONS_CN { get; set; }
        public string DESCRIPTIONS_US { get; set; }
        public string DRAWING_NO { get; set; }
        public string OLD_ITEM_CODE { get; set; }
        public string UNIT_OF_MEASURE { get; set; }
        public string ITEM_TYPE { get; set; }
        public string BUYER { get; set; }
        public string PLANNER { get; set; }
        public string ENABLE_FLAG { get; set; }
        public string ITEM_STATUS_CODE { get; set; }
        public string MAKE_BUY_CODE { get; set; }
        public string BONDED_FLAG { get; set; }
        public string IMPORT_LOCAL_FLAG { get; set; }
        public Nullable<int> GROSS_UNIT_WEIGHT { get; set; }
        public Nullable<int> NET_UNIT_WEIGHT { get; set; }
        public string WEIGHT_UOM { get; set; }
        public Nullable<int> UNIT_LENGTH { get; set; }
        public Nullable<int> UNIT_WIDTH { get; set; }
        public Nullable<int> UNIT_HEIGHT { get; set; }
        public string DIMENSION_UOM { get; set; }
        public Nullable<int> UNIT_VOLUME { get; set; }
        public string VOLUME_UOM { get; set; }
        public Nullable<int> PROCESSING_LEAD_TIME { get; set; }
        public Nullable<int> PREPROCESSING_LEAD_TIME { get; set; }
        public Nullable<int> POSTPROCESSING_LEAD_TIME { get; set; }
        public Nullable<int> FIXED_DAYS_SUPPLY { get; set; }
        public Nullable<int> MAXIMUM_ORDER_QUANTITY { get; set; }
        public Nullable<int> MINIMUM_ORDER_QUANTITY { get; set; }
        public Nullable<int> FIXED_LOT_MULTIPLIE { get; set; }
        public Nullable<int> FIXED_LEAD_TIME { get; set; }
        public string KEY_ITEM_FLAG { get; set; }
        public string DELIVERY_MODE { get; set; }
        public string INSPECTION_REQUIRED_FLAG { get; set; }
        public string DEFAULT_RECEIVING_SUBINV { get; set; }
        public Nullable<int> EXPIRATION_PERIOD { get; set; }
        public string ENABLE_LOT_CONTROL { get; set; }
        public string WIP_SUPPLY_TYPE { get; set; }
        public Nullable<int> SHRINKAGE_RATE { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
    }
}
