//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntiyForMeiCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class PI_MO_PROCESS_MOVE_TRAN
    {
        public string ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public string SOURCE_BATCH_ID { get; set; }
        public Nullable<System.DateTime> INSERT_TIME { get; set; }
        public Nullable<System.DateTime> DEAL_TIME { get; set; }
        public string DEAL_FLAG { get; set; }
        public string GROUP_ID { get; set; }
        public string ACTION { get; set; }
        public string SUCCESS_FLAG { get; set; }
        public string FAIL_MESSAGE { get; set; }
        public string PLANT_CODE { get; set; }
        public string MAKE_ORDER_NUM { get; set; }
        public string SOURCE { get; set; }
        public string PROCESS_CODE { get; set; }
        public string ITEM_CODE { get; set; }
        public int COMPLETED_QTY { get; set; }
        public System.DateTime COMPLETED_DATE { get; set; }
        public string REMARK { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
    }
}
