//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntiyForMeiCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class PP_SHRINKAGE_PLAN
    {
        public string ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public string SOURCE_CODE { get; set; }
        public string PlANT_CODE { get; set; }
        public string MAKE_ORDER_STATUS { get; set; }
        public string ITEM_ID { get; set; }
        public Nullable<int> SHRINKAGE_QTY { get; set; }
        public string SCHEDULE_GROUP_CODE { get; set; }
        public string RESOURCE_CODE { get; set; }
        public string PLANNER { get; set; }
        public Nullable<int> SUM_MO_QTY { get; set; }
        public Nullable<System.DateTime> FPC_TIME { get; set; }
        public Nullable<int> ORI_SHRINKAGE_QTY { get; set; }
        public string MO_NUMBER { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public string REMARK { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
    }
}
