//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntiyForMeiCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class PP_SHARE_PLAN
    {
        public string ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public string PLAN_CODE { get; set; }
        public string PLANT_CODE { get; set; }
        public string SOURCE_PLANT_CODE { get; set; }
        public string ITEM_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_DESC { get; set; }
        public System.DateTime FPC_TIME { get; set; }
        public int MO_QTY { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> ISSUED_DATE { get; set; }
        public string MAKE_ORDER_STATUS { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public string MO_NUMBER { get; set; }
        public string RESOURCE_CODE { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public string ATTRIBUTE11 { get; set; }
        public string ATTRIBUTE12 { get; set; }
        public string ATTRIBUTE13 { get; set; }
        public string ATTRIBUTE14 { get; set; }
        public string ATTRIBUTE15 { get; set; }
    }
}
