//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntiyForMeiCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_ITEM_ROUTINGS
    {
        public string ID { get; set; }
        public string PLANT_CODE { get; set; }
        public string ITEM_ID { get; set; }
        public string SCHEDULE_GROUP_CODE { get; set; }
        public string RESOURCE_TYPE { get; set; }
        public string RESOURCE_CODE { get; set; }
        public string RATE_TYPE { get; set; }
        public int RATE { get; set; }
        public int PRIORITY { get; set; }
        public string PROCESS_CODE { get; set; }
        public string SCHEDULE_FLAG { get; set; }
        public string SELECT_RESOURCE_FLAG { get; set; }
        public string ENABLE_FLAG { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
    }
}
