//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntiyForMeiCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_LEAD_TIME_PRODUCTION
    {
        public string Id { get; set; }
        public string SCHEDULE_REGION_CODE { get; set; }
        public string CATEGORY { get; set; }
        public string UPSTREAM_PLANT_CODE { get; set; }
        public string UPSTREAM_VALUES { get; set; }
        public string DOWNSTREAM_PLANT_CODE { get; set; }
        public string DOWNSTREAM_VALUES { get; set; }
        public int LEAD_TIME { get; set; }
        public int EARLIEST_LEAD_DAYS { get; set; }
        public string ENABLED_FLAG { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public string Attribute4 { get; set; }
        public string Attribute5 { get; set; }
        public string RELATION_TYPE { get; set; }
    }
}
