//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntiyForMeiCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_MO_TYPE
    {
        public string Id { get; set; }
        public string SCHEDULE_REGION_CODE { get; set; }
        public string PLANT_CODE { get; set; }
        public string MO_TYPE { get; set; }
        public int STANDARD_TYPE { get; set; }
        public string DESCRIPTIONS { get; set; }
        public string ENABLED_FLAG { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public string Attribute4 { get; set; }
        public string Attribute5 { get; set; }
    }
}
