//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntiyForMeiCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_MAKE_ORDER_INTERFACE
    {
        public string ID { get; set; }
        public Nullable<int> REQUEST_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public int GROUP_ID { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public Nullable<int> PROCESS_STATUS { get; set; }
        public string SOURCE_ORDER_ID { get; set; }
        public string SOURCE_CODE { get; set; }
        public string SCHEDULE_REGION_CODE { get; set; }
        public string PLANT_CODE { get; set; }
        public string SCHEDULE_GROUP_CODE { get; set; }
        public string RESOURCE_CODE { get; set; }
        public string MAKE_ORDER_TYPE { get; set; }
        public string MAKE_ORDER_NUM { get; set; }
        public string MAKE_ORDER_STATUS { get; set; }
        public string PROJECT_NUMBER { get; set; }
        public string ITEM_ID { get; set; }
        public int MO_QTY { get; set; }
        public Nullable<int> PLAN_QTY { get; set; }
        public Nullable<System.DateTime> DEMAND_DATE { get; set; }
        public string ALTERNATE_BOM_DESIGNATOR { get; set; }
        public Nullable<int> LEVEL_NUM { get; set; }
        public Nullable<System.DateTime> EARLIEST_START_TIME { get; set; }
        public Nullable<System.DateTime> FIX_SCHEDULE_TIME { get; set; }
        public Nullable<System.DateTime> FPS_TIME { get; set; }
        public System.DateTime FPC_TIME { get; set; }
        public Nullable<System.DateTime> LPS_TIME { get; set; }
        public System.DateTime LPC_TIME { get; set; }
        public Nullable<System.DateTime> INSPECTION_TIME { get; set; }
        public Nullable<int> PRE_PROCESSING_TIME { get; set; }
        public Nullable<int> POST_PROCESSING_TIME { get; set; }
        public Nullable<System.DateTime> FULFILL_TIME { get; set; }
        public Nullable<int> OFFSET_LEAD_TIME { get; set; }
        public Nullable<int> SWITCH_TIME { get; set; }
        public Nullable<int> MANF_LEAD_TIME { get; set; }
        public int PRIORITY { get; set; }
        public string PROD_RATE_TYPE { get; set; }
        public Nullable<int> PROD_RATE { get; set; }
        public string SCHEDULE_FLAG { get; set; }
        public string BACKLOG_FLAG { get; set; }
        public string BACKLOG_REASON { get; set; }
        public string DEMAND_CLASS { get; set; }
        public string STANDARD_FLAG { get; set; }
        public string BONDED_FLAG { get; set; }
        public string COMPLETION_SUBINVENTORY { get; set; }
        public string MOULD_CODE { get; set; }
        public string MO_WARNNING_FLAG { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<System.DateTime> ISSUED_DATE { get; set; }
        public Nullable<System.DateTime> RELEASED_DATE { get; set; }
        public string RELEASED_BY { get; set; }
        public Nullable<System.DateTime> COMPLETED_DATE { get; set; }
        public Nullable<System.DateTime> CLOSED_DATE { get; set; }
        public string CLOSED_BY { get; set; }
        public string REQ_SOURCE_PLANT { get; set; }
        public string REQ_NUMBER { get; set; }
        public string REQ_LINE_NUM { get; set; }
        public string REQ_TYPE { get; set; }
        public string REQ_COMMENTS { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string TOP_MO_PLANT_CODE { get; set; }
        public string TOP_MO_NUM { get; set; }
        public string PARENT_MO_PLANT_CODE { get; set; }
        public string PARENT_MO_NUM { get; set; }
        public Nullable<int> CHANGED_SEQ { get; set; }
        public string DERIVED_FLAG { get; set; }
        public string ORI_MO_NUMBER { get; set; }
        public Nullable<int> ORI_MO_QTY { get; set; }
        public string CHOOSE_PROD_LINE_FLAG { get; set; }
        public string DERIVED_PROCESS_FLAG { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public string ATTRIBUTE11 { get; set; }
        public string ATTRIBUTE12 { get; set; }
        public string ATTRIBUTE13 { get; set; }
        public string ATTRIBUTE14 { get; set; }
        public string ATTRIBUTE15 { get; set; }
    }
}
