//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntiyForMeiCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_REQ_NONSTD_REQUIREMENT
    {
        public string ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public string PLANT_CODE { get; set; }
        public string REQ_NUMBER { get; set; }
        public string REQ_LINE_NO { get; set; }
        public string COMPONENT_LINE_NUM { get; set; }
        public string ITEM_ID { get; set; }
        public string SUPPLY_TYPE { get; set; }
        public string SUPPLY_SUBINVENTORY { get; set; }
        public string UNIT_OF_MEASURE { get; set; }
        public int QUANTITY { get; set; }
        public string MRP_NET_FLAG { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
    }
}
