//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOADFILEOPHISTORY
    {
        public int ID { get; set; }
        public string UPLOADFILECODE { get; set; }
        public int OPTYPE { get; set; }
        public System.DateTime CREATEON { get; set; }
        public System.DateTime LASTUPDATEON { get; set; }
        public string CREATEBY { get; set; }
        public string LASTUPDATEBY { get; set; }
        public int ORDERNO { get; set; }
    }
}
