//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BU_PQ_REJ_JG_APP_PRO
    {
        public string REJ_JG_APP_PRO_ID { get; set; }
        public string REJ_BILL_CODE { get; set; }
        public string PFP_CODE { get; set; }
        public string PFP_NAME { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public string IS_INDEM { get; set; }
        public string IS_U_PART { get; set; }
        public Nullable<decimal> FAULT_QTY { get; set; }
        public string MFGSERIES_CODE { get; set; }
        public string HAP_POS { get; set; }
        public string SAVE_POS { get; set; }
        public string RESTOCK_POS { get; set; }
        public string BAD_CAUSE { get; set; }
        public string BAD_DESC { get; set; }
        public string BALE_CODE { get; set; }
        public string CONTRACT_CODE { get; set; }
        public Nullable<decimal> FULL_PACK_QTY { get; set; }
        public Nullable<decimal> MATE_QTY_SEMI { get; set; }
        public string SEMI_CODE { get; set; }
        public Nullable<decimal> SEMI_QTY { get; set; }
        public Nullable<decimal> MATE_QTY_SCRAP { get; set; }
        public Nullable<decimal> SCRAP_KG { get; set; }
        public string MATERIAL_UNIT { get; set; }
        public string SCRAP_TYPE { get; set; }
        public string BAD_TYPE_CODE { get; set; }
        public Nullable<decimal> PART_NG_QTY { get; set; }
        public string IS_BATCH { get; set; }
        public string IS_RE_SEND { get; set; }
        public string IS_STOP_LINE { get; set; }
        public string IS_PPM { get; set; }
        public string IS_LOGO_NOT_MATCH { get; set; }
        public Nullable<decimal> COEF { get; set; }
        public string RAN_NO { get; set; }
        public Nullable<decimal> COMP_PACK_QYT_NG { get; set; }
        public Nullable<decimal> MATE_QTY_SEMI_NG { get; set; }
        public Nullable<decimal> MATE_QTY_SCRAP_NG { get; set; }
        public string REJ_REASON { get; set; }
        public string CUR_MAIN_PRO { get; set; }
        public string CUR_RESTOCK_PRO { get; set; }
        public string CUR_STATUS { get; set; }
        public string APP_TYPE { get; set; }
        public Nullable<System.DateTime> APP_DATE { get; set; }
        public string APP_MAN { get; set; }
        public Nullable<System.DateTime> JUDGE_DATE { get; set; }
        public string JUDGE_MAN { get; set; }
        public string RESTOCK_MAN { get; set; }
        public Nullable<System.DateTime> RESTOCK_CONF_DATE { get; set; }
        public string RESTOCK_CONF_MAN { get; set; }
        public string RECY_MAN { get; set; }
        public Nullable<System.DateTime> RECY_DATE { get; set; }
        public string RECY_CONF_MAN { get; set; }
        public Nullable<System.DateTime> RECY_CONF_DATE { get; set; }
        public string REJ_MAN { get; set; }
        public string APP_DEAL_LOG { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public Nullable<System.DateTime> LAST_OPT_TIME { get; set; }
        public string DEFECT_ID { get; set; }
        public string DEFECT_DIS_VAL { get; set; }
        public string DEFECT_DUTY_UNIT { get; set; }
        public string REC_REMARK_INFO { get; set; }
        public string IS_HAVE_SAME { get; set; }
        public Nullable<System.DateTime> REJ_DATE { get; set; }
        public string BEL_FACT_CODE { get; set; }
        public string REJ_SEG { get; set; }
        public string P_BILL_CODE { get; set; }
        public string TYPE_VAL { get; set; }
        public string OK_BACK_CONF_MAN { get; set; }
        public Nullable<System.DateTime> OK_BACK_CONF_TIME { get; set; }
        public string OK_CONF_STATUS { get; set; }
        public string OK_BACK_POS { get; set; }
    }
}
