//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CP_UI_SYSTEMUSERAPPCONTROL
    {
        public int APP_ID { get; set; }
        public string USER_ID { get; set; }
        public string SHOWINDESKTOP { get; set; }
        public Nullable<short> SHOWMESSAGE { get; set; }
        public Nullable<short> PLAYVOICE { get; set; }
        public System.DateTime LASTUPDATE { get; set; }
        public string ICOPOSITION { get; set; }
        public Nullable<short> SHOWEMAIL { get; set; }
        public Nullable<short> SHOWSMS { get; set; }
        public string FOLDER_ID { get; set; }
        public string MENUICO { get; set; }
        public string MENUNAME { get; set; }
    }
}
