//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EAP_WF_PENDING_FORM
    {
        public string ID { get; set; }
        public string PENDING_ID { get; set; }
        public Nullable<decimal> FORMTYPE { get; set; }
        public Nullable<decimal> PLATFORM { get; set; }
        public string FORMINFO { get; set; }
    }
}
