//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EAP_MD_OTHERINFO
    {
        public string OTHER_ID { get; set; }
        public string OBJ_ID { get; set; }
        public string OWNER { get; set; }
        public Nullable<decimal> S_MIN { get; set; }
        public Nullable<decimal> S_MAX { get; set; }
        public Nullable<int> S_INIT { get; set; }
        public Nullable<int> S_CRE_BY { get; set; }
        public Nullable<int> S_CACH_SIZE { get; set; }
        public string S_CYCLE { get; set; }
        public string S_ORDER { get; set; }
        public string DB_USER { get; set; }
        public string DB_PSW { get; set; }
        public string DB_NAME { get; set; }
        public string DB_PUBLIC { get; set; }
        public string DB_SHARED { get; set; }
        public string SY_PUBLIC { get; set; }
        public string SY_O_OWNER { get; set; }
        public string SY_O_OBJNAME { get; set; }
        public string SY_DBLINK { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_TIME { get; set; }
    }
}
