//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EAP_WF_PROCESS_CHILD_MODULE
    {
        public string ID { get; set; }
        public string CHILD_PROCESS_MODULE_GUID { get; set; }
        public Nullable<decimal> CHILD_AUDITOR_TYPE { get; set; }
        public string CHILD_AUDITOR_ID { get; set; }
        public Nullable<decimal> HANDLE_TYPE { get; set; }
        public string PARENT_PROCESS_GUID { get; set; }
        public string PARENT_STEP_ID { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> CHILD_PROCESS_MODULE_MAIN_VER { get; set; }
        public Nullable<decimal> CHILD_PROCESS_MODULE_SUB_VER { get; set; }
        public Nullable<decimal> CHILD_CREATE_MODE { get; set; }
    }
}
