//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EAP_MD_LOG
    {
        public string LOG_ID { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string LOG_OBJNAME { get; set; }
        public string LOG_RECORDID { get; set; }
        public string LOG_RECORDNAME { get; set; }
        public string LOG_ACTION { get; set; }
        public string LOG_EDITOR { get; set; }
        public string LOG_IP { get; set; }
        public string LOG_DESC { get; set; }
        public string LOG_USERID { get; set; }
    }
}
