//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EAP_WF_ELECSEAL_RUNTIME
    {
        public string SEAL_ID { get; set; }
        public string USER_ID { get; set; }
        public Nullable<System.DateTime> SEALTIME { get; set; }
        public string PROCESS_GUID { get; set; }
        public string NODE_GUID { get; set; }
        public Nullable<decimal> ACTIONTYPE { get; set; }
        public string SEALPARAM { get; set; }
    }
}
