//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EAP_WF_NODE_EXTEND_RUNTIME
    {
        public string NODE_EXTEND_GUID { get; set; }
        public string PROCESS_GUID { get; set; }
        public Nullable<decimal> STEP_PATH_ID { get; set; }
        public string STEP_PATH_GUID { get; set; }
        public string STEP_GUID { get; set; }
        public string NODE_GUID { get; set; }
        public string AUDITOR { get; set; }
        public string AUDITOR_NAME { get; set; }
        public Nullable<System.DateTime> HANDLE_DATETIME { get; set; }
        public string HANDLE_TEXT { get; set; }
        public Nullable<decimal> NODE_STATUS { get; set; }
        public Nullable<System.DateTime> ACTIVE_DATETIME { get; set; }
        public Nullable<decimal> STALL_HOUR { get; set; }
        public Nullable<decimal> NODE_TYPE { get; set; }
        public Nullable<System.DateTime> SYS_ACTIVE_DATETIME { get; set; }
        public string STATION_GUID { get; set; }
        public string REQUEST_USER_GUID { get; set; }
        public string REQUEST_USER_NAME { get; set; }
        public string REQUEST_HANDLE_TEXT { get; set; }
        public string APPROVE_GUID { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> PROCESS_PT { get; set; }
        public Nullable<System.DateTime> STARTHANDLE_TIME { get; set; }
    }
}
