//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EAP_WF_PENDING_H
    {
        public string PENDING_ID { get; set; }
        public string PENDING_TITLE { get; set; }
        public string FROM_USER { get; set; }
        public string TO_USER { get; set; }
        public string DESCRIPTION { get; set; }
        public string NODE_GUID { get; set; }
        public string AUTOR_GUID { get; set; }
        public string AUTOR_NAME { get; set; }
        public string PEND_AUTOR { get; set; }
        public Nullable<decimal> PENDING_TYPE { get; set; }
        public Nullable<decimal> PENDING_STATUS { get; set; }
        public Nullable<System.DateTime> PROCESSING_TIME { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string PROCESS_GUID { get; set; }
        public Nullable<decimal> DELETED { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public Nullable<decimal> NODE_FROM { get; set; }
        public string PENDING_TYPENAME { get; set; }
        public string STEP_PATH_GUID { get; set; }
        public Nullable<System.DateTime> ACTIVE_DATE { get; set; }
    }
}
