//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EAP_MD_USER_DB
    {
        public string UD_ID { get; set; }
        public string UD_NAME { get; set; }
        public Nullable<int> UD_DBTYPE { get; set; }
        public string UD_USERID { get; set; }
        public string UD_DBIP { get; set; }
        public string UD_DBNAME { get; set; }
        public string UD_DBUSER { get; set; }
        public string UD_PASSWORD { get; set; }
        public string UD_INSTANCE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_TIME { get; set; }
    }
}
