//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EAP_FORM_LANGUAGE
    {
        public string LAN_ID { get; set; }
        public string FORM_ID { get; set; }
        public string OBJECT_ID { get; set; }
        public decimal OBJECT_TYPE { get; set; }
        public string FIELD_NAME { get; set; }
        public string ZH_CN { get; set; }
        public string EN_US { get; set; }
        public string JA_JP { get; set; }
        public string ZH_TW { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_TIME { get; set; }
        public string LAN_CODE { get; set; }
        public string LAN_DESC { get; set; }
    }
}
