//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EAP_WF_AGENT_PERMISSION
    {
        public string ID { get; set; }
        public Nullable<decimal> MEMBER_TYPE { get; set; }
        public string MEMBER_GUID { get; set; }
        public string PROCESS_MODULE_GUID { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
    }
}
