//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EAP_FORM_STEP_EXECHISTORY
    {
        public string ID { get; set; }
        public string RULE_ID { get; set; }
        public string STEP_ID { get; set; }
        public byte[] STEP_PARAMS { get; set; }
        public string STEP_CONTENT { get; set; }
        public Nullable<decimal> COUNT { get; set; }
        public Nullable<decimal> EXECUTE_TIME { get; set; }
        public string RULE_FORMRULE_ID { get; set; }
        public string STEP_TYPE { get; set; }
        public string STEP_RESULT { get; set; }
        public Nullable<decimal> STEP_EXEC_ORDER { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
    }
}
