//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EAP_MD_VIEWFIELD
    {
        public string VF_ID { get; set; }
        public string V_ID { get; set; }
        public string VF_FLDID { get; set; }
        public string VF_COLOTHERNAME { get; set; }
        public string VF_SORT { get; set; }
        public Nullable<int> VF_ORDER { get; set; }
        public string VF_SELECT { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIME { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_TIME { get; set; }
    }
}
