//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EAP_WF_DOCUMENT
    {
        public string DOC_GUID { get; set; }
        public string FK_GUID { get; set; }
        public string DOC_TYPE { get; set; }
        public string DOC_NAME { get; set; }
        public string FILE_NAME { get; set; }
        public string LOCA_TION { get; set; }
        public Nullable<System.DateTime> CREATE_ON { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<decimal> IS_IMPOR_TANT { get; set; }
        public string LOCKED_BY { get; set; }
        public Nullable<System.DateTime> LOCKED_DATE_TIME { get; set; }
        public string MODI_FIED_BY { get; set; }
        public Nullable<System.DateTime> MODI_FIED_DATE_TIME { get; set; }
        public string NODE_GUID { get; set; }
        public string NODE_EXTEND_GUID { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string FILE_MIME { get; set; }
    }
}
