//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EAP_SYS_USER_TEMP
    {
        public string USER_ID { get; set; }
        public string EMP_ID { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public decimal USER_TYPE { get; set; }
        public string USER_DESC { get; set; }
        public string ORG_ID { get; set; }
        public System.DateTime ACTIVE_DATE { get; set; }
        public System.DateTime DISABLE_DATE { get; set; }
        public decimal ENABLED { get; set; }
        public decimal BUILT_IN { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime LAST_UPDATED_TIME { get; set; }
        public string USER_NICKNAME { get; set; }
        public string LYCCUSER_ID { get; set; }
        public string LYCC_NO { get; set; }
    }
}
