//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EAP_WF_AUTOAUDIT_RUNTIME
    {
        public string AUTOAUDIT_ID { get; set; }
        public string PROCESS_GUID { get; set; }
        public string STEP_PATH_GUID { get; set; }
        public string STEP_GUID { get; set; }
        public string NODE_GUID { get; set; }
        public Nullable<decimal> AUTOAUDIT_STATUS { get; set; }
        public Nullable<System.DateTime> AUTOAUDIT_TIME { get; set; }
        public string BUSINESS_DATA { get; set; }
        public string BUSINESS_NO { get; set; }
    }
}
