//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EAP_WF_FORMPERMISSION_MODULE
    {
        public string ID { get; set; }
        public string STEP_GUID { get; set; }
        public Nullable<decimal> PROCESS_MODULE_MAIN_VER { get; set; }
        public Nullable<decimal> PROCESS_MODULE_SUB_VER { get; set; }
        public string FORM_ID { get; set; }
        public Nullable<decimal> MEMBER_TYPE { get; set; }
        public string MEMBER_ID { get; set; }
        public Nullable<decimal> FORM_CAN_READ { get; set; }
        public string EXCEPT_CAN_READ { get; set; }
        public Nullable<decimal> FORM_CAN_WRITE { get; set; }
        public string EXCEPT_CAN_WRITE { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public Nullable<decimal> ACTION_TYPE { get; set; }
    }
}
