//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_IFR_IQS_BU_DISPATCH_E3S
    {
        public string ID { get; set; }
        public string BILL_NO { get; set; }
        public string PART_CODE { get; set; }
        public Nullable<decimal> REAL_QTY { get; set; }
        public string RETURN_TYPE { get; set; }
        public string POST_COMP { get; set; }
        public string POST_NO { get; set; }
        public Nullable<System.DateTime> DATE_AS_SEND { get; set; }
        public Nullable<System.DateTime> DATE_DLR_SEND { get; set; }
        public Nullable<System.DateTime> DATE_AS_ANSWER { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> HANDLED_TIME { get; set; }
        public string HANDLE_FLAG { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_TIME { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
    }
}
