//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_IQS_BU_IQS_SCORE
    {
        public string IQS_SCORE_ID { get; set; }
        public string YEARS { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_NAME_CN { get; set; }
        public string ITEM_NAME_EN { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public string CAR_SERIES_CODE { get; set; }
        public string CAR_TYPE_CODE { get; set; }
        public string BRAND_NAME { get; set; }
        public string DETAIL_MARKET { get; set; }
        public Nullable<decimal> UNWEIGHTED_SAMPLE_SIZE { get; set; }
        public Nullable<decimal> WEIGHTED_SAMPLE_SIZE { get; set; }
        public string BAD_UNSATISFIED_CODE { get; set; }
        public string QLT_CODE { get; set; }
        public string DUTY_COMP_CODE { get; set; }
        public string DUTY_COMP_TYPE { get; set; }
        public string DUTY_COMP_NAME { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public Nullable<decimal> SCORE_AVG { get; set; }
        public Nullable<decimal> SCORE_RANK { get; set; }
        public string BI { get; set; }
    }
}
