//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_IQS_BU_DTR
    {
        public string DTR_ID { get; set; }
        public string TR_CODE { get; set; }
        public string NET_CODE { get; set; }
        public string VIN { get; set; }
        public string ENGINE { get; set; }
        public string PFP_CODE { get; set; }
        public string PFP_NAME { get; set; }
        public string CAR_SERIES_NAME { get; set; }
        public string CAR_TYPE_NAME { get; set; }
        public string NET_SHOR_NAME { get; set; }
        public Nullable<System.DateTime> SALE_DATE { get; set; }
        public string REKARK { get; set; }
        public string CAR_SERIES { get; set; }
        public string CAR_TYPE { get; set; }
        public string TOPIC { get; set; }
        public string BELONG_SYSTEM { get; set; }
        public Nullable<System.DateTime> TR_OUT_DATE { get; set; }
        public string IMPORT_DEGREE { get; set; }
        public string DLR_PART_INFO { get; set; }
        public string USER_COMPLAIN { get; set; }
        public string CUST_COMPLAIN { get; set; }
        public string FAULT_NOTE { get; set; }
        public string REPAIR_NOTE { get; set; }
        public Nullable<System.DateTime> OFF_LINE_DATE { get; set; }
        public Nullable<System.DateTime> FAULT_DATE { get; set; }
        public Nullable<System.DateTime> REPAIR_DATE { get; set; }
        public Nullable<decimal> FALUT_MILGS { get; set; }
        public string FIRS_FALUT_MAIL { get; set; }
        public string FIRST_FALUT_DAY { get; set; }
        public string FIRST_FALUT { get; set; }
        public string FIRST_FALUT_REIPAIR_NOTE { get; set; }
        public string TR_COMMENT { get; set; }
        public string CHECK_NOTE { get; set; }
        public string CONFIRM_NOTE { get; set; }
        public Nullable<decimal> CONTACT_FPF_TIMES { get; set; }
        public string CS_CODE { get; set; }
        public string CT_CODE { get; set; }
        public string OLD_PART_INFO { get; set; }
        public Nullable<System.DateTime> RETURN_TIME { get; set; }
        public string RETURN_REASON { get; set; }
        public string MAINSEND_UNIT { get; set; }
        public string MAINSEND_MAN { get; set; }
        public string MAINSEND_FAX { get; set; }
        public string COPYSEND_UNIT { get; set; }
        public string COPYSNED_MAN { get; set; }
        public string COPYSEND_FAX { get; set; }
        public string REPORT_TYPE { get; set; }
        public string SENDMAN { get; set; }
        public string SERVERMGR { get; set; }
        public string LINK_FAX { get; set; }
        public string RESULT_ACCESS { get; set; }
        public string FAULT_INFO { get; set; }
        public string VERDICT_ACCESS { get; set; }
        public string REQUEST { get; set; }
        public Nullable<System.DateTime> NET_TIME { get; set; }
        public string WORK_MAN { get; set; }
        public Nullable<System.DateTime> WORK_TIME { get; set; }
        public string VERDICT_LINK { get; set; }
        public string SING1 { get; set; }
        public string RESULT_LIN { get; set; }
        public string SIGN2 { get; set; }
        public string FS_MAN { get; set; }
        public string NET_MAN { get; set; }
        public Nullable<decimal> REPLY_FLAG { get; set; }
        public Nullable<decimal> VISIBLE_FLAG { get; set; }
        public Nullable<decimal> REPLYID { get; set; }
        public Nullable<decimal> END_CASE { get; set; }
        public Nullable<decimal> GOTO_FLAG { get; set; }
        public string COPYSNED_UNIT2 { get; set; }
        public string COPYSEND_MAN2 { get; set; }
        public string FIRST_FAULT_PART { get; set; }
        public string SECOND_FAULT_PART { get; set; }
        public string SELECT_RESULT { get; set; }
        public string REPAIR_PAPER { get; set; }
        public string SELECT_REQUST { get; set; }
        public Nullable<System.DateTime> GOTO_TIME { get; set; }
        public string GOTO_MAN { get; set; }
        public string CHECK_FAULT_INFO { get; set; }
        public string RETURN_REASON_ACCESS { get; set; }
        public string RETURN_REASON_LINK { get; set; }
        public Nullable<decimal> ISFOLLOW { get; set; }
        public string EVALUCATE { get; set; }
        public Nullable<System.DateTime> WORK_DATE { get; set; }
        public string PZBZK { get; set; }
        public string KHZYK { get; set; }
        public Nullable<System.DateTime> READ_DATE { get; set; }
        public string SENDMAN_TEL { get; set; }
        public string MALFUNCTION_LOG { get; set; }
        public string REUSLT_LOG { get; set; }
        public string RETURNREASON_C { get; set; }
        public string RETURN_REASON_CONTACT { get; set; }
        public string BRAND_CODE { get; set; }
        public string NET_BRAND { get; set; }
        public Nullable<decimal> RSPEED { get; set; }
        public Nullable<decimal> SPEED { get; set; }
        public string GEAR_BOX { get; set; }
        public string SHELF_LOCATION { get; set; }
        public string OUT_COLOUR { get; set; }
        public string NAME { get; set; }
        public string TEL { get; set; }
        public string CAR_MARK { get; set; }
        public string ROAD_CIRCS { get; set; }
        public Nullable<decimal> PEOPLE { get; set; }
        public Nullable<decimal> GOODS_WEIGHT { get; set; }
        public string FIRST_GREPAIR { get; set; }
        public string SECOND_GREPAIR { get; set; }
        public string OTHER_GREPAIR { get; set; }
        public string WEATHER { get; set; }
        public Nullable<decimal> TEMPERATURE { get; set; }
        public Nullable<decimal> PARTOIL { get; set; }
        public Nullable<decimal> OILCIRCS { get; set; }
        public string ENGINEOIL { get; set; }
        public string GEARBOXOIL { get; set; }
        public string DIFFOIL { get; set; }
        public string PID { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string CREATOR { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public string FAULT_PART { get; set; }
        public string TR_SERVICE { get; set; }
    }
}
