//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_IQS_BU_FOLLOW_CLIENT
    {
        public string FOLLOW_DETAIL_ID { get; set; }
        public string FOLLOW_ITEM_ID { get; set; }
        public string IQS_INVEST_REPORT_ID { get; set; }
        public string VIN { get; set; }
        public string ITEM_DETAIL_CODE { get; set; }
        public string IS_UNITE { get; set; }
        public string UNITE_VISIT_ID { get; set; }
        public string DLR_ID { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string CAR_SERIES_CODE { get; set; }
        public string FOLLOW_ANSWERS_ID { get; set; }
        public string IS_CLOSE { get; set; }
        public string CUS_NO { get; set; }
    
        public virtual T_IQS_BU_DLR_INFO T_IQS_BU_DLR_INFO { get; set; }
        public virtual T_IQS_BU_FOLLOW_ITEM T_IQS_BU_FOLLOW_ITEM { get; set; }
        public virtual T_IQS_BU_REPEAT_CLIENT T_IQS_BU_REPEAT_CLIENT { get; set; }
    }
}
