//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_IQS_DB_ITEM_INFO_TMP
    {
        public string IQS_ITEM_INFO_TMP_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string PROBLEM_CODE { get; set; }
        public string ITEM_NAME_CN { get; set; }
        public string ITEM_NAME_EN { get; set; }
        public string QLT_CODE { get; set; }
        public string REMARK { get; set; }
        public string MODIFY_DESC { get; set; }
        public string TEMPLATE_VERSION_NO { get; set; }
        public string STATUS { get; set; }
        public string PRESENTER { get; set; }
        public Nullable<System.DateTime> SUBMIT_TIME { get; set; }
        public string SC_AUDITOR { get; set; }
        public Nullable<System.DateTime> SC_AUDIT_TIME { get; set; }
        public string SC_OPINION { get; set; }
        public string MST_AUDITOR { get; set; }
        public Nullable<System.DateTime> MST_AUDIT_TIME { get; set; }
        public string MST_OPINION { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
    }
}
