//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_IQS_BU_DEST_CONTACT
    {
        public T_IQS_BU_DEST_CONTACT()
        {
            this.T_IQS_BU_RECOVERY_REPORTS = new HashSet<T_IQS_BU_RECOVERY_REPORTS>();
        }
    
        public string CONTACT_ID { get; set; }
        public string LINK_MAN { get; set; }
        public string POST_ADDR { get; set; }
        public string ZIP { get; set; }
        public string LINK_TEL { get; set; }
        public string PART_ADDRESS_NAME { get; set; }
        public string PART_ADDRESS_VALUE { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
    
        public virtual ICollection<T_IQS_BU_RECOVERY_REPORTS> T_IQS_BU_RECOVERY_REPORTS { get; set; }
    }
}
