//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MIS_DB_CAR_SERIES
    {
        public string CAR_SERIES_ID { get; set; }
        public string CAR_SERIES_CODE { get; set; }
        public string CAR_SERIES_NAME { get; set; }
        public string BRAND_CODE { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string CAR_SERIES_CODE_SALE { get; set; }
        public string DETAIL_MARKET { get; set; }
        public string IQS_CAR_SERIES_CODE { get; set; }
        public string IQS_CAR_SERIES_NAME { get; set; }
    }
}
