//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_MONITOR_PROBLEM
    {
        public string MONITOR_PROBLEM_ID { get; set; }
        public string FACTORY_CODE { get; set; }
        public string WORKSHOP_CODE { get; set; }
        public string SCHEDULE_TYPE { get; set; }
        public System.DateTime CHECK_TIME { get; set; }
        public string INSPECT_ITEM { get; set; }
        public string CHECK_MAN { get; set; }
        public string CAR_TYPE_CODE { get; set; }
        public string VIN { get; set; }
        public string BAD_DESC { get; set; }
        public string CLASS_VAL { get; set; }
        public string PFP_SID { get; set; }
        public string PROD_CONF_MAN { get; set; }
        public Nullable<int> BAD_QTY { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string TEAM_CODE { get; set; }
    }
}
