//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_COMB_COLOR_MEAS_M
    {
        public T_PQ_BU_COMB_COLOR_MEAS_M()
        {
            this.T_PQ_BU_COMB_COLOR_MEAS_D = new HashSet<T_PQ_BU_COMB_COLOR_MEAS_D>();
        }
    
        public string COMB_COLOR_MEAS_M_ID { get; set; }
        public string FACTORY_CODE { get; set; }
        public System.DateTime MEASURE_DATE { get; set; }
        public string CAR_TYPE_CODE { get; set; }
        public string CAR_COLOR_CODE { get; set; }
        public string WORKSHOP_CODE { get; set; }
        public string PRO_LINE_CODE { get; set; }
        public string VIN { get; set; }
        public string VE_CHECK_MAN { get; set; }
        public string PAINT_CHECK_MAN { get; set; }
        public string TECH_SEC { get; set; }
        public string BASF_VAL { get; set; }
        public string JOINT_RST { get; set; }
        public string TECH_ADJUST_SCHEME { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string CT_TYPE { get; set; }
    
        public virtual ICollection<T_PQ_BU_COMB_COLOR_MEAS_D> T_PQ_BU_COMB_COLOR_MEAS_D { get; set; }
    }
}
