//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_TATGET_ACTUAL
    {
        public string TATGET_ACTUAL_ID { get; set; }
        public string FACTORY_CODE { get; set; }
        public string WORKSHOP_CODE { get; set; }
        public string PROJECT_TYPE_CODE { get; set; }
        public string MANAGE_PROJECT_ID { get; set; }
        public string CAR_TYPE_CODE { get; set; }
        public string YEAR_VAL { get; set; }
        public Nullable<decimal> PILDASH_JAN { get; set; }
        public Nullable<decimal> PILDASH_FEB { get; set; }
        public Nullable<decimal> PILDASH_MAR { get; set; }
        public Nullable<decimal> PILDASH_APR { get; set; }
        public Nullable<decimal> PILDASH_MAY { get; set; }
        public Nullable<decimal> PILDASH_JUN { get; set; }
        public Nullable<decimal> PILDASH_JUL { get; set; }
        public Nullable<decimal> PILDASH_AUG { get; set; }
        public Nullable<decimal> PILDASH_SEP { get; set; }
        public Nullable<decimal> PILDASH_OCT { get; set; }
        public Nullable<decimal> PILDASH_NOV { get; set; }
        public Nullable<decimal> PILDASH_DEC { get; set; }
        public Nullable<decimal> CHALLENGE_ONE_JAN { get; set; }
        public Nullable<decimal> CHALLENGE_ONE_FEB { get; set; }
        public Nullable<decimal> CHALLENGE_ONE_MAR { get; set; }
        public Nullable<decimal> CHALLENGE_ONE_APR { get; set; }
        public Nullable<decimal> CHALLENGE_ONE_MAY { get; set; }
        public Nullable<decimal> CHALLENGE_ONE_JUN { get; set; }
        public Nullable<decimal> CHALLENGE_ONE_JUL { get; set; }
        public Nullable<decimal> CHALLENGE_ONE_AUG { get; set; }
        public Nullable<decimal> CHALLENGE_ONE_SEP { get; set; }
        public Nullable<decimal> CHALLENGE_ONE_OCT { get; set; }
        public Nullable<decimal> CHALLENGE_ONE_NOV { get; set; }
        public Nullable<decimal> CHALLENGE_ONE_DEC { get; set; }
        public Nullable<decimal> CHALLENGE_TWO_JAN { get; set; }
        public Nullable<decimal> CHALLENGE_TWO_FEB { get; set; }
        public Nullable<decimal> CHALLENGE_TWO_MAR { get; set; }
        public Nullable<decimal> CHALLENGE_TWO_APR { get; set; }
        public Nullable<decimal> CHALLENGE_TWO_MAY { get; set; }
        public Nullable<decimal> CHALLENGE_TWO_JUN { get; set; }
        public Nullable<decimal> CHALLENGE_TWO_JUL { get; set; }
        public Nullable<decimal> CHALLENGE_TWO_AUG { get; set; }
        public Nullable<decimal> CHALLENGE_TWO_SEP { get; set; }
        public Nullable<decimal> CHALLENGE_TWO_OCT { get; set; }
        public Nullable<decimal> CHALLENGE_TWO_NOV { get; set; }
        public Nullable<decimal> CHALLENGE_TWO_DEC { get; set; }
        public Nullable<decimal> ACTUAL_JAN { get; set; }
        public Nullable<decimal> ACTUAL_FEB { get; set; }
        public Nullable<decimal> ACTUAL_MAR { get; set; }
        public Nullable<decimal> ACTUAL_APR { get; set; }
        public Nullable<decimal> ACTUAL_MAY { get; set; }
        public Nullable<decimal> ACTUAL_JUN { get; set; }
        public Nullable<decimal> ACTUAL_JUL { get; set; }
        public Nullable<decimal> ACTUAL_AUG { get; set; }
        public Nullable<decimal> ACTUAL_SEP { get; set; }
        public Nullable<decimal> ACTUAL_OCT { get; set; }
        public Nullable<decimal> ACTUAL_NOV { get; set; }
        public Nullable<decimal> ACTUAL_DEC { get; set; }
        public string MON_ASSESS { get; set; }
        public Nullable<decimal> HALF_A_YEAR_MEAN { get; set; }
        public string HALF_A_YEAR_ASSESS { get; set; }
        public Nullable<decimal> YEARLY_MEAN { get; set; }
        public string YEARLY_ASSESS { get; set; }
        public string IS_STATUS { get; set; }
        public string REMARKS { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string YY_REMARKS { get; set; }
    }
}
