//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_V_DEVI_WEAR
    {
        public string V_DEVI_WEAR_ID { get; set; }
        public string FACTORY_CODE { get; set; }
        public string CAR_TYPE_CODE { get; set; }
        public string VIN { get; set; }
        public string CCR_CODE { get; set; }
        public Nullable<System.DateTime> MEASURE_DATE { get; set; }
        public string MEASURE_MAN { get; set; }
        public string TIRE_MODEL { get; set; }
        public string CHECK_LINE_TYPE { get; set; }
        public Nullable<decimal> FINE_FW_KCA_LR_DIFF { get; set; }
        public Nullable<decimal> FINE_FW_KCA_LF { get; set; }
        public Nullable<decimal> FINE_FW_KCA_RF { get; set; }
        public Nullable<decimal> FINE_FW_CA_LR_DIFF { get; set; }
        public Nullable<decimal> FINE_FW_CA_LF { get; set; }
        public Nullable<decimal> FINE_FW_CA_RF { get; set; }
        public Nullable<decimal> FINE_BW_CA_LR_DIFF { get; set; }
        public Nullable<decimal> FINE_BW_CA_LF { get; set; }
        public Nullable<decimal> FINE_BW_CA_RF { get; set; }
        public Nullable<decimal> FINE_FW_TA { get; set; }
        public Nullable<decimal> FINE_FW_FB_LF { get; set; }
        public Nullable<decimal> FINE_FW_FB_RF { get; set; }
        public Nullable<decimal> FINE_BW_TA { get; set; }
        public Nullable<decimal> FINE_BW_FB_LF { get; set; }
        public Nullable<decimal> FINE_BW_FB_RF { get; set; }
        public Nullable<decimal> FINE_KIA { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public Nullable<decimal> FINE_FWN_LF { get; set; }
        public Nullable<decimal> FINE_FWN_RF { get; set; }
    }
}
