//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_CLAIM_AMT_D
    {
        public string CLAIM_AMT_D_ID { get; set; }
        public string REJ_BILL_ID { get; set; }
        public string MATERIAL_CODE { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public Nullable<decimal> MATERIAL_QTY { get; set; }
        public Nullable<decimal> COEF { get; set; }
        public Nullable<decimal> BEAR_RATIO { get; set; }
        public Nullable<decimal> PUR_PRICE { get; set; }
        public string DUTY_COMP_CODE { get; set; }
        public string DUTY_COMP_NAME { get; set; }
        public Nullable<int> SCRAP_QTY { get; set; }
        public Nullable<decimal> SCRAP_PRICE { get; set; }
        public Nullable<decimal> SCRAP_PRICE_TOT { get; set; }
        public string CONTRACT_CODE { get; set; }
        public string FUTURES_MON { get; set; }
        public string BALE_CODE { get; set; }
        public Nullable<System.DateTime> IN_STORE_DATE { get; set; }
        public Nullable<decimal> MATERIAL_FEE { get; set; }
        public Nullable<long> REWORK_WORK_FEE { get; set; }
        public Nullable<decimal> OTHER_FEE { get; set; }
        public Nullable<decimal> TOTAL_FEE { get; set; }
        public string CLAIM_MON { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string CLAIM_AMT_D_RELE_FLAG { get; set; }
        public string FACTORY_TYPE { get; set; }
        public Nullable<decimal> LOG_FEE { get; set; }
        public Nullable<decimal> LOG_UNIT_PRICE { get; set; }
        public string RPT_TYPE { get; set; }
        public string COMP_CODE { get; set; }
        public string BRAND_CODE { get; set; }
    }
}
