//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_FX_DISPLAY_SET
    {
        public string FX_DISPLAY_SET_ID { get; set; }
        public decimal DISPLAY_NUM { get; set; }
        public decimal REFRESH_INTERVAL { get; set; }
        public decimal CRWA_BEGIN_TORED { get; set; }
        public decimal CRWA_END_TORED { get; set; }
        public decimal WSRA_BEGIN_TORED { get; set; }
        public decimal WSRA_AEND_TORED { get; set; }
        public decimal CRWA_BEGIN_TOYELLOW { get; set; }
        public decimal CRWA_END_TOYELLOW { get; set; }
        public decimal WSRA_BEGIN_TOYELLOW { get; set; }
        public decimal WSRA_END_TOYELLOW { get; set; }
        public string HIDDENFIELDS { get; set; }
        public string USER_ID { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public decimal DESCENDINGPRIORITY { get; set; }
        public string FACTORY_CODE { get; set; }
        public string HIDDENFIELDS_NAME { get; set; }
    }
}
