//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_MEAS_MOLD_D
    {
        public string MEAS_MOLD_D_ID { get; set; }
        public string MEAS_MOLD_M_ID { get; set; }
        public Nullable<decimal> ITEM_NO { get; set; }
        public string MEASURE_ITEM { get; set; }
        public Nullable<decimal> UPPER_DEVIATION { get; set; }
        public Nullable<decimal> LOWER_DEVIATION { get; set; }
        public Nullable<decimal> THEORY_VAL { get; set; }
        public string UNIT { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string MEASURE_POINT { get; set; }
    }
}
