//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_DB_BA_POINT_MEAS
    {
        public string BA_POINT_MEAS_ID { get; set; }
        public string CAR_TYPE_CODE { get; set; }
        public string POS_ID { get; set; }
        public string POS_NAME { get; set; }
        public string RL_VAL { get; set; }
        public string DIRECTION { get; set; }
        public string ATTRIBUTE_VAL { get; set; }
        public string AFFECT_OBJ_MAIN { get; set; }
        public string AFFECT_OBJ_SEC { get; set; }
        public decimal THEORY_STAN_VAL { get; set; }
        public Nullable<decimal> CHECK_SPEC_ADD { get; set; }
        public Nullable<decimal> CHECK_SPEC_SUBTRA { get; set; }
        public Nullable<decimal> INNER_SPEC_ADD { get; set; }
        public Nullable<decimal> INNER_SPEC_SUBTRA { get; set; }
        public string BELONG_PART_CODE { get; set; }
        public string BELONG_PART_NAME { get; set; }
        public string BELONG_PART_SUPPLIER { get; set; }
        public string MANAGE_TEAM { get; set; }
        public string CLAMP_MANGE_CLAMP_NAME { get; set; }
        public string CLAMP_MANGE_MANGE_UNIT { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string TEST_TYPE { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> THEORY_STAN_VAL2 { get; set; }
        public Nullable<decimal> CHECK_SPEC_ADD2 { get; set; }
        public Nullable<decimal> CHECK_SPEC_SUBTRA2 { get; set; }
        public Nullable<decimal> INNER_SPEC_ADD2 { get; set; }
        public Nullable<decimal> INNER_SPEC_SUBTRA2 { get; set; }
        public string COLLECTOR { get; set; }
        public string COLL_STATUS { get; set; }
    }
}
