//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_DB_PROC_WASTE_UPPER
    {
        public string PROC_WASTE_UPPER_ID { get; set; }
        public string FACTORY_CODE { get; set; }
        public string TYPE { get; set; }
        public string PART_NAME { get; set; }
        public string PRO_LINE_CODE { get; set; }
        public string PRO_LINE_NAME { get; set; }
        public string ENGINE_TYPE { get; set; }
        public string PROC_WASTE_TYPE { get; set; }
        public Nullable<decimal> SET_VAL { get; set; }
        public System.DateTime BEGIN_MON { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string PART_NO { get; set; }
        public string FACTORY_NAME { get; set; }
        public string TARGET_TYPE { get; set; }
    }
}
