//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_CAMSHAFT_PROC
    {
        public T_PQ_BU_CAMSHAFT_PROC()
        {
            this.T_PQ_BU_CAMSHAFT_MID_MAC = new HashSet<T_PQ_BU_CAMSHAFT_MID_MAC>();
        }
    
        public string CAMSHAFT_PROC_ID { get; set; }
        public string PART_NAME { get; set; }
        public string PART_STATUS { get; set; }
        public string FACTORY_CODE { get; set; }
        public string PRO_LINE_CODE { get; set; }
        public string MAC_TYPE { get; set; }
        public string QR_CODE { get; set; }
        public string ONLINE_PROCESS { get; set; }
        public string ONLINE_EQUIP_CODE { get; set; }
        public System.DateTime ONLINE_TIME { get; set; }
        public string FORGE_LOT_BAR_CODE { get; set; }
        public string ONLINE_STATUS { get; set; }
        public string SHAFT_MAC_PROCESS { get; set; }
        public string SHAFT_MAC_EQUIP_CODE { get; set; }
        public System.DateTime SHAFT_MAC_TIME { get; set; }
        public string SHAFT_MAC_STATUS { get; set; }
        public string CAM_GRINDER_PROCESS { get; set; }
        public string CAM_GRINDER_EQUIP_CODE { get; set; }
        public System.DateTime CAM_GRINDER_TIME { get; set; }
        public string CAM_GRINDER_STATUS { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string ON_BAD_B_TYPE { get; set; }
        public string SHAFT_MAC_BAD_B_TYPE { get; set; }
        public string CAM_GRINDER_BAD_B_TYPE { get; set; }
        public string PART_NO { get; set; }
        public string FACTORY_NAME { get; set; }
    
        public virtual ICollection<T_PQ_BU_CAMSHAFT_MID_MAC> T_PQ_BU_CAMSHAFT_MID_MAC { get; set; }
    }
}
