//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_DB_BU_VIN_CARTYPE
    {
        public string ID { get; set; }
        public string VIN_EIGHT { get; set; }
        public string CAR_TYPE_CODE { get; set; }
        public string CREATOR { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
