//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_DEFECT_QUES_BAK
    {
        public string DEFECT_QUES_ID { get; set; }
        public string FACTORY_CODE { get; set; }
        public string PROC_CODE { get; set; }
        public string MANAGE_CODE { get; set; }
        public string CAR_TYPE { get; set; }
        public string CAR_COLOR { get; set; }
        public string ENGINE_NO { get; set; }
        public string CAR_TYPE_CODE { get; set; }
        public string VIN { get; set; }
        public Nullable<System.DateTime> OFFLINE_DATE { get; set; }
        public string CAR_CONFIG { get; set; }
        public string EIGTEEN_CODE { get; set; }
        public string USER_TYPE { get; set; }
        public string OTHER_DESC { get; set; }
        public string BAD_PHE_PIC { get; set; }
        public string LEVEL_VAL { get; set; }
        public string PFP_SID { get; set; }
        public string IS_CLAIM { get; set; }
        public string IS_POP_UP { get; set; }
        public System.DateTime OPER_DATE { get; set; }
        public string ENTRY_CLERK { get; set; }
        public string TEAM_CODE { get; set; }
        public string SCHEDULE_TYPE { get; set; }
        public string PART_1 { get; set; }
        public string PART_2 { get; set; }
        public string POS_STATUS { get; set; }
        public string DEFECT_VAL { get; set; }
        public string BAD_DESC { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string WORKSHOP_CODE { get; set; }
        public string ONLINE_DISTINCT { get; set; }
    }
}
