//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_TORQUE_DATA_0517
    {
        public string TORQUE_DATA_ID { get; set; }
        public Nullable<System.DateTime> MEASURE_DATE { get; set; }
        public string MEASURE_MAN { get; set; }
        public string EQUIP_CODE { get; set; }
        public string FACTORY_CODE { get; set; }
        public string WORKSHOP_CODE { get; set; }
        public string PRO_LINE_CODE { get; set; }
        public string CAR_TYPE_CODE { get; set; }
        public string VIN { get; set; }
        public string CCR_CODE { get; set; }
        public string MANAGE_CODE { get; set; }
        public string EIGTEEN_CODE { get; set; }
        public string CABINET_NAME { get; set; }
        public string WORK_STATION_CODE { get; set; }
        public string JOB_NAME { get; set; }
        public Nullable<long> TOT_TIMES { get; set; }
        public Nullable<long> LEFT_TIMES { get; set; }
        public string CTRL_CODE { get; set; }
        public string APP_CODE { get; set; }
        public string DEAL_STATUS { get; set; }
        public string ANGLE_VAL { get; set; }
        public Nullable<decimal> ACTUAL_TORQUE_VAL { get; set; }
        public Nullable<decimal> TORQUE_SET_VAL { get; set; }
        public Nullable<decimal> TORQUE_MIN_VAL { get; set; }
        public Nullable<decimal> TORQUE_MAX_VAL { get; set; }
        public string FINISH_STATUS { get; set; }
        public string CPK_CALCU { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public Nullable<System.DateTime> COMPLETE_DATE { get; set; }
        public Nullable<long> HIT_TIMES { get; set; }
    }
}
