//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_CONN_ROD_PROC
    {
        public string CONN_ROD_PROC_ID { get; set; }
        public string PART_NAME { get; set; }
        public string PART_STATUS { get; set; }
        public string FACTORY_CODE { get; set; }
        public string PRO_LINE_CODE { get; set; }
        public string MAC_TYPE { get; set; }
        public string QR_CODE { get; set; }
        public string ONLINE_PROCESS { get; set; }
        public string ONLINE_EQUIP_CODE { get; set; }
        public System.DateTime ONLINE_TIME { get; set; }
        public string FORGE_LOT_BAR_CODE { get; set; }
        public string ONLINE_STATUS { get; set; }
        public string BIG_OIL_MAC_PROCESS { get; set; }
        public string BIG_OIL_MAC_EQUIP_CODE { get; set; }
        public System.DateTime BIG_OIL_MAC_TIME { get; set; }
        public string BIG_OIL_MAC_STATUS { get; set; }
        public string LASER_MAC_PROCESS { get; set; }
        public string LASER_MAC_EQUIP_CODE { get; set; }
        public System.DateTime LASER_MAC_TIME { get; set; }
        public string LASER_MAC_STATUS { get; set; }
        public string BORING_MAC_PROCESS { get; set; }
        public string BORING_MAC_EQUIP_CODE { get; set; }
        public System.DateTime BORING_MAC_TIME { get; set; }
        public string BORING_MAC_STATUS { get; set; }
        public string PRO_FINAL_MEAS_PROCESS { get; set; }
        public string PRO_FINAL_MEAS_EQUIP_CODE { get; set; }
        public System.DateTime PRO_FINAL_MEAS_TIME { get; set; }
        public string CONN_ROD_PROD_2D_CODE { get; set; }
        public string BIG_HOLE_LEVEL { get; set; }
        public string PRO_FINAL_MEAS_STATUS { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string ON_BAD_B_TYPE { get; set; }
        public string BIG_OIL_MAC_BAD_B_TYPE { get; set; }
        public string LASER_MAC_BAD_B_TYPE { get; set; }
        public string BORING_MAC_BAD_B_TYPE { get; set; }
        public string PRO_FINAL_MEAS_BAD_B_TYPE { get; set; }
        public string PART_NO { get; set; }
        public string FACTORY_NAME { get; set; }
    }
}
