//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_TATGET
    {
        public string TATGET_ACTUAL_ID { get; set; }
        public string FACTORY_CODE { get; set; }
        public string WORKSHOP_CODE { get; set; }
        public string PROJECT_TYPE_CODE { get; set; }
        public string MANAGE_PROJECT_ID { get; set; }
        public string CAR_TYPE_CODE { get; set; }
        public string YEAR_VAL { get; set; }
        public Nullable<decimal> PILDASH { get; set; }
        public Nullable<decimal> CHALLENGE_ONE { get; set; }
        public Nullable<decimal> CHALLENGE_TWO { get; set; }
        public Nullable<decimal> CHALLENGE_FEB { get; set; }
        public string REMARKS { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
    }
}
