//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_MATE_PRICE_MAINT
    {
        public string MATE_PRICE_MAINT_ID { get; set; }
        public string MATERIAL_CODE { get; set; }
        public string MATERIAL_TYPE { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public Nullable<decimal> MATERIAL_PRICE { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string FACTORY_CODE { get; set; }
        public string MATERIAL_UNIT { get; set; }
        public string CURRENCY { get; set; }
        public string MATERIAL_NAME { get; set; }
    }
}
