//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_BAD_DATA
    {
        public string BAD_DATA_ID { get; set; }
        public string PART_2D_CODE { get; set; }
        public string PART_NO { get; set; }
        public string PRO_LINE_CODE { get; set; }
        public string PROCESS_CODE { get; set; }
        public string EQUIP_POS { get; set; }
        public System.DateTime DECI_CHAN_TIME { get; set; }
        public string DUTY_DEPT { get; set; }
        public string BAD_PART_SOURCE { get; set; }
        public string CHANGE_BAT { get; set; }
        public int CHANGE_QTY { get; set; }
        public string PART_CHAN_TYPE { get; set; }
        public string STATUS_CHAN_DECI_MAN { get; set; }
        public string BAD_BIG_TYPE { get; set; }
        public string BAD_TYPE { get; set; }
        public string CHANGE_REMARK { get; set; }
        public string IS_EFFE { get; set; }
        public string APPROVAL_MAN { get; set; }
        public Nullable<System.DateTime> APPROVAL_TIME { get; set; }
        public string APPROVAL_OPIN { get; set; }
        public string APPROVAL_ATTI { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string MAC_TYPE { get; set; }
        public Nullable<System.DateTime> PROCESS_TIME { get; set; }
        public string FACTORY_CODE { get; set; }
        public string PART_TYPE { get; set; }
        public string FACTORY_NAME { get; set; }
        public string BAD_PART_TYPE { get; set; }
        public string LOGIC_PROCESS { get; set; }
        public string IS_DEAL { get; set; }
        public string DEAL_REMARK { get; set; }
        public string RELATED_BAD_DATA_ID { get; set; }
    }
}
