//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SQ_BU_SUP_IMP_ALERT_BAK1
    {
        public string SUP_IMP_ALERT_ID { get; set; }
        public string CAR_BRAND { get; set; }
        public string ALERT_MON { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string SUPPLIER_RESP_MAN { get; set; }
        public string POSITION_DESC { get; set; }
        public string EMAIL_ADD { get; set; }
        public string TEL_NUM { get; set; }
        public Nullable<System.DateTime> ALERT_NOTICE_DATE { get; set; }
        public Nullable<System.DateTime> IMP_PLAN_RESP_DL { get; set; }
        public Nullable<System.DateTime> IMP_PLAN_RESP_DATE { get; set; }
        public string IMP_WAY { get; set; }
        public Nullable<System.DateTime> IMP_PLAN_CONF_DATE { get; set; }
        public Nullable<System.DateTime> IMP_CM_CONF_DATE { get; set; }
        public Nullable<System.DateTime> IMP_CM_CLOSE_DATE { get; set; }
        public string IS_RELEASE { get; set; }
        public Nullable<System.DateTime> ALERT_REL_NOTICE_DATE { get; set; }
        public string REMARK { get; set; }
        public string AUDIT_TYPE { get; set; }
        public string AUDIT_UNIT { get; set; }
        public Nullable<System.DateTime> APPROVAL_TIME { get; set; }
        public string IMP_MAIN_CONT { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public Nullable<System.DateTime> ALERT_HAP_DATE { get; set; }
        public string ALERT_BOOK_TYPE { get; set; }
        public string IMP_CONT_TYPE { get; set; }
        public string ISSUE_WAY { get; set; }
        public string ALTER_ISSUE_MAN { get; set; }
        public string IMP_PLAN_RE_MAN { get; set; }
        public string IMP_PLAN_COMF_MAN { get; set; }
        public string IMP_CM_COMF_MAN { get; set; }
        public string IMP_CM_CLOSE_MAN { get; set; }
        public string FACTORY_CODE { get; set; }
        public Nullable<decimal> ALTER_TYPE_TIMES { get; set; }
        public string PRO_GROUP_MAN { get; set; }
        public string REJ_OPINION { get; set; }
        public string EVAL_TYPE { get; set; }
    }
}
