//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SQ_BU_SUP_IMP_ALERT_D_BAK
    {
        public string SUP_IMP_ALERT_DETAIL_ID { get; set; }
        public string SUP_IMP_ALERT_ID { get; set; }
        public string IS_ISSUE { get; set; }
        public string ALERT_TYPE { get; set; }
        public Nullable<int> ALERT_TIMES { get; set; }
        public string TAR_VAL { get; set; }
        public string ACTUAL_VAL { get; set; }
        public string RED_YELLOW_CARD_STATUS { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
    }
}
