//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SQ_BU_EIGHT_D_RPT0920
    {
        public string EIGHT_D_RPT_ID { get; set; }
        public string INSPECT_RPT_ID { get; set; }
        public string FACTORY_CODE { get; set; }
        public string SUPPLIER_SHORT_NAME { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public string PART_NO { get; set; }
        public string BAD_CONTENT { get; set; }
        public string RPT_BOOK_NO { get; set; }
        public string IMPORT_DEGREE { get; set; }
        public Nullable<System.DateTime> HAP_DATE { get; set; }
        public string CAR_TYPE { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string FIVE_W_ONE_H { get; set; }
        public string PHOTO_PATH { get; set; }
        public string IS_RE_SEND { get; set; }
        public string SIMILAR_PART_SITU { get; set; }
        public string SUP_OUTFLOW_INIT_ANA { get; set; }
        public string SUP_PRELI_INVEST_REA { get; set; }
        public string INTERIM_CMS { get; set; }
        public string OK_PART_IDENTIFY_WAY { get; set; }
        public string OK_PART_INIT_NO { get; set; }
        public Nullable<System.DateTime> SHIPMENT_DATE { get; set; }
        public string REMARK_1 { get; set; }
        public Nullable<System.DateTime> ANA_COMPLETE_DATE { get; set; }
        public string FINAL_ANA_REASON { get; set; }
        public Nullable<System.DateTime> PERM_CMS_IMP_DATE { get; set; }
        public string PERM_CMS_CONT { get; set; }
        public Nullable<System.DateTime> CMS_CONF_DATE { get; set; }
        public string IS_CONF_PERM_CMS { get; set; }
        public string CONF_WAY { get; set; }
        public Nullable<int> PART_QTY_1 { get; set; }
        public Nullable<int> PART_QTY_2 { get; set; }
        public string RELATED_DATA { get; set; }
        public Nullable<System.DateTime> TRACK_ACTION_COMP_DATE { get; set; }
        public string TAKE_STEPS { get; set; }
        public string APPROVE_MAN { get; set; }
        public string AUDIT_ENGINEER { get; set; }
        public string AUDIT_MONITOR { get; set; }
        public string AUDIT_RESP { get; set; }
        public string EDIT_MAN { get; set; }
        public string EDIT_DUTY { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
        public string MODIFY_MAN { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string APPROVE_MAN2 { get; set; }
        public string APPROVE_MAN_DUTY { get; set; }
        public Nullable<System.DateTime> APPROVE_DATE { get; set; }
        public string EIGHT_D_ANA_ATTA { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string SUPPLIER_EMAIL { get; set; }
        public string SUPPLIER_FACT_NAME { get; set; }
        public string DRAW_UP { get; set; }
        public string SUPPLIER_TEL { get; set; }
        public string USER_CAR_TYPE_ASSEM { get; set; }
        public string NISSAN_IMP_PART { get; set; }
        public string RENAULT_CSR { get; set; }
        public Nullable<System.DateTime> ORI_TAB_DRAW_UP_DATE { get; set; }
        public Nullable<System.DateTime> TAB_MOD_DATE { get; set; }
        public string PART_NAME { get; set; }
        public string DESI_NO_DEVO { get; set; }
        public string MOD_NO { get; set; }
        public string SUPPLIER_APPR_MAN { get; set; }
        public string POSITION_VAL { get; set; }
        public Nullable<System.DateTime> ADMIT_DATE { get; set; }
        public string CM_COMF { get; set; }
        public string AUDIT_STATUS { get; set; }
        public Nullable<System.DateTime> FIR_CONF_TIME { get; set; }
        public string RPT_SCORE { get; set; }
        public string IS_DUTY_JUDGE { get; set; }
        public string SUP_STRONG_HOLD_CODE { get; set; }
        public string NOT_SUP_DUTY_REASON { get; set; }
    }
}
