//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_RSPROJECT_INFO
    {
        public string RSPROJECT_INFO_ID { get; set; }
        public string PROJECT_CODE { get; set; }
        public string ITEM_NAME { get; set; }
        public string PROJECT_TYPE { get; set; }
        public string CAR_BRAND { get; set; }
        public string PROJECT_LEVEL { get; set; }
        public string PROJECT_RESOURCE { get; set; }
        public string SYS_DISTIN { get; set; }
        public string PFP_FIVE_CODE { get; set; }
        public string MFGSERIES_CODE { get; set; }
        public string DUTY_COMP_TYPE { get; set; }
        public string DUTY_COMP_CODE { get; set; }
        public string ENG_ACT { get; set; }
        public string EVENT_DESC { get; set; }
        public string EVENT_REASON { get; set; }
        public string EVENT_METHOD { get; set; }
        public string RELATED_FAC_SER { get; set; }
        public string RELATED_RANGE_CNT { get; set; }
        public string RE_DUTY_ORG { get; set; }
        public string DECIDED_DESC { get; set; }
        public string PROJECT_CLO_DESC { get; set; }
        public Nullable<System.DateTime> TM_DATE { get; set; }
        public Nullable<System.DateTime> TC_DATE { get; set; }
        public string CASE_CODE { get; set; }
        public Nullable<System.DateTime> EXPAND_DATE { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public Nullable<decimal> SUP_RESP_RATIO { get; set; }
        public Nullable<System.DateTime> RESP_DECI_DATE { get; set; }
        public string INFLUENCE_SITUATION { get; set; }
        public Nullable<decimal> DEDUCT_POINTS { get; set; }
        public string MAINTAIN_DUTY_MAN { get; set; }
        public string DUTY_D_STATUS { get; set; }
        public Nullable<decimal> DISPOSAL_UNITS { get; set; }
    }
}
