//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_ASSE_MEAS_LEAK
    {
        public string ASSE_MEAS_LEAK_ID { get; set; }
        public string FACTORY_CODE { get; set; }
        public string MEAS_LEAK_PART { get; set; }
        public string MEAS_LEAK_RESULT { get; set; }
        public string MEAS_LEAK_VAL { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public Nullable<decimal> MEAS_LEAK_PRE { get; set; }
        public string PRO_LINE_CODE { get; set; }
        public string ENGINEERING_TYPE { get; set; }
        public string EQUIP_CODE { get; set; }
        public string ENGINE_NO { get; set; }
        public string PART_NO { get; set; }
        public Nullable<System.DateTime> SWEEP_TIME_VAL { get; set; }
        public string LOGIC_CODE { get; set; }
    }
}
