//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_QIC_EXCE_EXP_20160826
    {
        public string QIC_EXCE_EXP_ID { get; set; }
        public string QIC_EXCE_M_ID { get; set; }
        public string DEAL_TYPE { get; set; }
        public string DEAL_MAN { get; set; }
        public string DEAL_PERSON { get; set; }
        public Nullable<System.DateTime> DEAL_DATE { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string DEAL_OPINION { get; set; }
    }
}
