//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_FX_RFID_CAR_PAS
    {
        public string RFID_CAR_PAS_ID { get; set; }
        public string DATA_STATE { get; set; }
        public string DATA_RESULT { get; set; }
        public string VIN { get; set; }
        public string PROCESS_ID { get; set; }
        public string PASS_DATE { get; set; }
        public string PLANT_CODE { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string RE_STATUS { get; set; }
    }
}
