//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_CAR_PROD_PLAN_IMP
    {
        public string CAR_PROD_PLAN_IMP_ID { get; set; }
        public string FACTORY_CODE { get; set; }
        public string PROC_CODE { get; set; }
        public string MANAGE_CODE1 { get; set; }
        public string MANAGE_CODE2 { get; set; }
        public string EIGTEEN_CODE1 { get; set; }
        public string EIGTEEN_CODE2 { get; set; }
        public string EIGTEEN_CODE3 { get; set; }
        public string PAINT_COLOR_CODE { get; set; }
        public string INNER_COLOR_CODE { get; set; }
        public string MS_OFFLINE_DATE { get; set; }
        public string VIN1 { get; set; }
        public string VIN2 { get; set; }
        public string SET_PLAN_DATE { get; set; }
        public string SET_PLAN_SCHEDULE { get; set; }
        public string SET_PLAN_TIME { get; set; }
        public string SOLDER_PLAN_DATE { get; set; }
        public string SOLDER_PLAN_SCHEDULE { get; set; }
        public string SOLDER_PLAN_TIME { get; set; }
        public string PAINT_PLAN_DATE { get; set; }
        public string PAINT_PLAN_SCHEDULE { get; set; }
        public string PAINT_PLAN_TIME { get; set; }
        public string INSTALL_PLAN_DATE { get; set; }
        public string INSTALL_PLAN_SCHEDULE { get; set; }
        public string INSTALL_PLAN_TIME { get; set; }
        public string OFFLINE_PLAN_DATE { get; set; }
        public string OFFLINE_PLAN_SCHEDULE { get; set; }
        public string OFFLINE_PLAN_TIME { get; set; }
        public string FINAL_CHECK_DATE { get; set; }
        public string FINAL_CHECK_SCHEDULE { get; set; }
        public string FINAL_CHECK_TIME { get; set; }
        public string DELIVERY_PLAN_DATE { get; set; }
        public string DELIVERY_PLAN_SCHEDULE { get; set; }
        public string DELIVERY_PLAN_TIME { get; set; }
        public string ORDER_VAL { get; set; }
        public string ORDER_VAL1 { get; set; }
        public string ENGINE_NO { get; set; }
        public string BASE_SERIES_CODE { get; set; }
        public string CAR_SERIES_CODE { get; set; }
        public string ACT_VAL { get; set; }
        public string RE_ORDER { get; set; }
        public string FACTORY_NOW_LOC1 { get; set; }
        public string FACTORY_NOW_LOC2 { get; set; }
        public string CREATOR { get; set; }
        public string BATCHNO { get; set; }
        public string ERR_MSG { get; set; }
    }
}
