//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_INSUR_REGI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PQ_BU_INSUR_REGI()
        {
            this.T_PQ_BU_INSUR_REJ_BILL = new HashSet<T_PQ_BU_INSUR_REJ_BILL>();
            this.T_PQ_BU_INSUR_SUP_INDEM = new HashSet<T_PQ_BU_INSUR_SUP_INDEM>();
        }
    
        public string INSUR_REGI_ID { get; set; }
        public string INSUR_REGI_CODE { get; set; }
        public Nullable<System.DateTime> CASE_HAP_DATE { get; set; }
        public Nullable<System.DateTime> REGI_DATE { get; set; }
        public string LOG_COMP_CODE { get; set; }
        public string INSUR_BROKER_CODE { get; set; }
        public string INSUR_COMP_CODE { get; set; }
        public string REGI_DESC { get; set; }
        public string DEAL_OPINION { get; set; }
        public string INSUR_REGI_STATUS { get; set; }
        public Nullable<System.DateTime> AUDIT_TIME { get; set; }
        public Nullable<System.DateTime> SUBMIT_DATA_TIME { get; set; }
        public Nullable<System.DateTime> RECEIVE_DATA_TIME { get; set; }
        public Nullable<System.DateTime> INDEM_TIME { get; set; }
        public Nullable<decimal> CLAIM_AMT { get; set; }
        public Nullable<int> OTHER_AMOUNT { get; set; }
        public Nullable<decimal> INDEM_AMT { get; set; }
        public string REMARK { get; set; }
        public string INSUR_REMARK { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string REGI_TYPE { get; set; }
        public string REJ_REASON { get; set; }
        public string SEND_STATUS { get; set; }
        public string COMP_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_BU_INSUR_REJ_BILL> T_PQ_BU_INSUR_REJ_BILL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_BU_INSUR_SUP_INDEM> T_PQ_BU_INSUR_SUP_INDEM { get; set; }
    }
}
