//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_STOCK_STATUS
    {
        public string STOCK_ID { get; set; }
        public string VIN { get; set; }
        public string CAR_STATUS { get; set; }
        public string ALL_NAME { get; set; }
        public string CAR_HOUSE_NAME { get; set; }
        public string DATA_STATUS { get; set; }
        public string CREATOR { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public string ATTRBUIT1 { get; set; }
        public string ATTRBUIT2 { get; set; }
        public string ATTRBUIT3 { get; set; }
        public string ATTRBUIT4 { get; set; }
        public string ATTRBUIT5 { get; set; }
    }
}
