//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_CLAIM_AMT_TOT
    {
        public string CLAIM_AMT_TOT_ID { get; set; }
        public string DUTY_COMP_TYPE { get; set; }
        public string DUTY_COMP_CODE { get; set; }
        public string MATERIAL_CODE { get; set; }
        public Nullable<decimal> MATERIAL_QTY { get; set; }
        public Nullable<decimal> MATERIAL_FEE { get; set; }
        public Nullable<decimal> REWORK_WORK_FEE { get; set; }
        public Nullable<decimal> OTHER_FEE { get; set; }
        public Nullable<decimal> TOTAL_FEE { get; set; }
        public string REMARK { get; set; }
        public string CLAIM_MON { get; set; }
        public string SEND_STATUS { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
        public string MATERIAL_NAME { get; set; }
        public string FACTORY_TYPE { get; set; }
        public string COMP_CODE { get; set; }
        public string BRAND_CODE { get; set; }
    }
}
