//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_DB_VESV3_TEMP2
    {
        public Nullable<decimal> ZZJS { get; set; }
        public string VIN_CODE { get; set; }
        public System.DateTime APPRAISE_DATE { get; set; }
        public string BAD_DESC { get; set; }
        public string IQS_SCORE { get; set; }
        public string WK { get; set; }
        public string WEEKHEADER { get; set; }
        public string PFP_SID { get; set; }
        public string DISTIN_TYPE { get; set; }
        public string EVAL_TYPE { get; set; }
    }
}
