//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_FSC_MSD
    {
        public string FSC_MSD_ID { get; set; }
        public string FACTORY_CODE { get; set; }
        public string QR_CODE { get; set; }
        public Nullable<System.DateTime> FSC_DATE { get; set; }
        public Nullable<decimal> FSC_MSD_DATE { get; set; }
        public Nullable<decimal> FSC_SPEED { get; set; }
        public Nullable<decimal> FSC_SPEED_TO { get; set; }
        public Nullable<decimal> FSC_VOLTAGE { get; set; }
        public Nullable<decimal> FSC_ET_CURRENT { get; set; }
        public Nullable<decimal> FSC_NITROGEN { get; set; }
        public Nullable<decimal> FSC_NITROGEN_TO { get; set; }
        public Nullable<decimal> FSC_PRESSURE { get; set; }
        public Nullable<decimal> FSC_PRESSURE_TO { get; set; }
        public Nullable<decimal> FSC_SPRAY { get; set; }
        public Nullable<decimal> FSC_WORKPIECE { get; set; }
        public Nullable<decimal> FSC_MOVING_SPEED { get; set; }
        public string FSC_FILE_PATH { get; set; }
        public Nullable<decimal> ORDER_NO { get; set; }
        public string IS_ENABLE { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public string SDP_USER_ID { get; set; }
        public string SDP_ORG_ID { get; set; }
        public string UPDATE_CONTROL_ID { get; set; }
    }
}
