//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.PQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PQ_BU_FMEA_DATA
    {
        public string FMEA_DATA_ID { get; set; }
        public string QIC_EXCE_M_ID { get; set; }
        public Nullable<decimal> SEVERITY_VALUE { get; set; }
        public string SEVERITY_REASON { get; set; }
        public Nullable<decimal> OCCURRENCE_VALUE { get; set; }
        public string OCCURRENCE_REASON { get; set; }
        public Nullable<decimal> DETECTIVITY_VALUE { get; set; }
        public string DETECTIVITY_REASON { get; set; }
        public string MARKET_RISK { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIER { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
    }
}
