//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///PP100TEST02
    /// </summary>
    public partial class PP100TEST02
    {
        
    /// <summary>
    ///YEARS
    /// </summary>
    public string YEARS { get; set; }
        
    /// <summary>
    ///CAR_SERIES_CODE
    /// </summary>
    public string CAR_SERIES_CODE { get; set; }
        
    /// <summary>
    ///INVEST_PERIOD_NO
    /// </summary>
    public string INVEST_PERIOD_NO { get; set; }
        
    /// <summary>
    ///INVEST_TYPE
    /// </summary>
    public string INVEST_TYPE { get; set; }
        
    /// <summary>
    ///YANGBEN
    /// </summary>
    public string YANGBEN { get; set; }
        
    /// <summary>
    ///PP100_OVERALL
    /// </summary>
    public string PP100_OVERALL { get; set; }
    }
}
