//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_CP_UI_FOLDERREFUSER
    /// </summary>
    public partial class T_CP_UI_FOLDERREFUSER
    {
        
    /// <summary>
    ///文件夹ID
    /// </summary>
    public string FOLDER_ID { get; set; }
        
    /// <summary>
    ///关联用户ID
    /// </summary>
    public string USER_ID { get; set; }
        
    /// <summary>
    ///显示在哪一屏
    /// </summary>
    public byte SHOWINDESKTOP { get; set; }
        
    /// <summary>
    ///文件夹图标
    /// </summary>
    public string FOLDER_ICO { get; set; }
        
    /// <summary>
    ///子文件夹
    /// </summary>
    public string CHILDREN_FOLDER { get; set; }
        
    /// <summary>
    ///文件夹位置
    /// </summary>
    public string ICOPOSITION { get; set; }
        
    /// <summary>
    ///父级文件夹
    /// </summary>
    public string CURRENTPARENT { get; set; }
        
    /// <summary>
    ///用户自定义文件夹名称
    /// </summary>
    public string FOLDER_NAME { get; set; }
    }
}
