//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_DB_DB_PART_BAK
    /// </summary>
    public partial class T_DB_DB_PART_BAK
    {
        
    /// <summary>
    ///PART_ID
    /// </summary>
    public string PART_ID { get; set; }
        
    /// <summary>
    ///PART_NO
    /// </summary>
    public string PART_NO { get; set; }
        
    /// <summary>
    ///PART_NAME
    /// </summary>
    public string PART_NAME { get; set; }
        
    /// <summary>
    ///MAC_TYPE
    /// </summary>
    public string MAC_TYPE { get; set; }
        
    /// <summary>
    ///SNP_NUM
    /// </summary>
    public int SNP_NUM { get; set; }
        
    /// <summary>
    ///SUPPLIER_CODE
    /// </summary>
    public string SUPPLIER_CODE { get; set; }
        
    /// <summary>
    ///SUPPLIER_NAME
    /// </summary>
    public string SUPPLIER_NAME { get; set; }
        
    /// <summary>
    ///PART_SOURCE
    /// </summary>
    public string PART_SOURCE { get; set; }
        
    /// <summary>
    ///SYS_MODULE
    /// </summary>
    public string SYS_MODULE { get; set; }
        
    /// <summary>
    ///ORDER_NO
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///IS_ENABLE
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///CREATOR
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///CREATED_DATE
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///MODIFIER
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_DATE
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP_USER_ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP_ORG_ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///UPDATE_CONTROL_ID
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    }
}
