//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///表单读写权限模版表
    /// </summary>
    public partial class T_EAP_WF_FORMPERMISSION_MODULE
    {
        
    /// <summary>
    ///编号
    /// </summary>
    public string ID { get; set; }
        
    /// <summary>
    ///步骤编号
    /// </summary>
    public string STEP_GUID { get; set; }
        
    /// <summary>
    ///流程模版主版本
    /// </summary>
    public decimal PROCESS_MODULE_MAIN_VER { get; set; }
        
    /// <summary>
    ///流程模版子版本
    /// </summary>
    public decimal PROCESS_MODULE_SUB_VER { get; set; }
        
    /// <summary>
    ///表单编号
    /// </summary>
    public string FORM_ID { get; set; }
        
    /// <summary>
    ///0:组织，6：用户组，7：角色，5：用户，2：岗位
    /// </summary>
    public decimal MEMBER_TYPE { get; set; }
        
    /// <summary>
    ///权限对象编号
    /// </summary>
    public string MEMBER_ID { get; set; }
        
    /// <summary>
    ///0：否，1：是
    /// </summary>
    public decimal FORM_CAN_READ { get; set; }
        
    /// <summary>
    ///多个控件编号用,隔开
    /// </summary>
    public string EXCEPT_CAN_READ { get; set; }
        
    /// <summary>
    ///0：否，1：是
    /// </summary>
    public decimal FORM_CAN_WRITE { get; set; }
        
    /// <summary>
    ///多个控件编号用,隔开
    /// </summary>
    public string EXCEPT_CAN_WRITE { get; set; }
        
    /// <summary>
    ///数字越小权限越高
    /// </summary>
    public decimal PRIORITY { get; set; }
        
    /// <summary>
    ///动作类型
    /// </summary>
    public decimal ACTION_TYPE { get; set; }
    }
}
