//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///数据库表字典表
    /// </summary>
    public partial class T_EAP_FORM_DB_TABLE
    {
        
    /// <summary>
    ///编号GUID
    /// </summary>
    public string TABLE_ID { get; set; }
        
    /// <summary>
    ///表名
    /// </summary>
    public string TABLE_NAME { get; set; }
        
    /// <summary>
    ///名称
    /// </summary>
    public string TABLE_CHINESE_NAME { get; set; }
        
    /// <summary>
    ///表类型
    /// </summary>
    public decimal OBJECT_BTYPE { get; set; }
        
    /// <summary>
    ///表单类型
    /// </summary>
    public decimal OBJECT_MTYPE { get; set; }
        
    /// <summary>
    ///数据库类型
    /// </summary>
    public decimal OBJECT_STYPE { get; set; }
        
    /// <summary>
    ///目标数据库
    /// </summary>
    public string DB { get; set; }
        
    /// <summary>
    ///说明
    /// </summary>
    public string TABLE_DESC { get; set; }
        
    /// <summary>
    ///视图名称
    /// </summary>
    public string VIEW_NAME { get; set; }
    }
}
