//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///表单XML库表
    /// </summary>
    public partial class T_EAP_FORM
    {
        
    /// <summary>
    ///编号
    /// </summary>
    public string FORM_ID { get; set; }
        
    /// <summary>
    ///名称
    /// </summary>
    public string FORM_NAME { get; set; }
        
    /// <summary>
    ///说明
    /// </summary>
    public string FORM_DESC { get; set; }
        
    /// <summary>
    ///是否业务表单
    /// </summary>
    public decimal IS_BUSINESS { get; set; }
        
    /// <summary>
    ///是否禁用
    /// </summary>
    public decimal IS_DISABLED { get; set; }
        
    /// <summary>
    ///表单XML
    /// </summary>
    public byte[] XML_STRING { get; set; }
        
    /// <summary>
    ///创建SQL
    /// </summary>
    public byte[] SQL_BUILD_STRING { get; set; }
        
    /// <summary>
    ///是否创建表
    /// </summary>
    public decimal IS_CREATE_TABLE { get; set; }
        
    /// <summary>
    ///表单修改标志
    /// </summary>
    public decimal IS_UPDATE { get; set; }
        
    /// <summary>
    ///是否绑定表
    /// </summary>
    public decimal IS_TABLE_BINDING { get; set; }
        
    /// <summary>
    ///树结构信息
    /// </summary>
    public byte[] TREE_INFO_STRING { get; set; }
        
    /// <summary>
    ///表关联信息
    /// </summary>
    public byte[] TABLEINFOSTRING { get; set; }
        
    /// <summary>
    ///按钮权限
    /// </summary>
    public string BUTTON_GRANT_STRING { get; set; }
        
    /// <summary>
    ///表单URL
    /// </summary>
    public string FORM_URL { get; set; }
        
    /// <summary>
    ///系统视图SQL
    /// </summary>
    public byte[] VIEW_SQL_STRING { get; set; }
        
    /// <summary>
    ///编码规则编号
    /// </summary>
    public string CODERULEID { get; set; }
        
    /// <summary>
    ///源数据库
    /// </summary>
    public string DB { get; set; }
        
    /// <summary>
    ///表单帮助说明
    /// </summary>
    public byte[] FORM_HELP { get; set; }
        
    /// <summary>
    ///按钮集合串
    /// </summary>
    public string BUTTON_STRING { get; set; }
        
    /// <summary>
    ///是否使用
    /// </summary>
    public decimal IS_USING { get; set; }
        
    /// <summary>
    ///原表单XML
    /// </summary>
    public byte[] OLD_XML_STRING { get; set; }
        
    /// <summary>
    ///公共属性
    /// </summary>
    public string PUBLIC_PROPERTIE { get; set; }
        
    /// <summary>
    ///表单生成DLL路径
    /// </summary>
    public string FORM_DLL_PATH { get; set; }
        
    /// <summary>
    ///表单生成类型
    /// </summary>
    public string FORM_TYPE { get; set; }
        
    /// <summary>
    ///表单类别編号
    /// </summary>
    public string CATEGORY_ID { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATED_BY { get; set; }
        
    /// <summary>
    ///创建时间
    /// </summary>
    public System.DateTime CREATED_TIME { get; set; }
        
    /// <summary>
    ///修改人
    /// </summary>
    public string LAST_UPDATED_BY { get; set; }
        
    /// <summary>
    ///修改时间
    /// </summary>
    public System.DateTime LAST_UPDATED_TIME { get; set; }
    }
}
