//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_EAP_MD_VERATTACH
    /// </summary>
    public partial class T_EAP_MD_VERATTACH
    {
        
    /// <summary>
    ///VA_ID
    /// </summary>
    public string VA_ID { get; set; }
        
    /// <summary>
    ///VER_ID
    /// </summary>
    public string VER_ID { get; set; }
        
    /// <summary>
    ///VA_PATH
    /// </summary>
    public string VA_PATH { get; set; }
        
    /// <summary>
    ///VA_NAME
    /// </summary>
    public string VA_NAME { get; set; }
        
    /// <summary>
    ///CREATED_BY
    /// </summary>
    public string CREATED_BY { get; set; }
        
    /// <summary>
    ///CREATED_TIME
    /// </summary>
    public System.DateTime CREATED_TIME { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_BY
    /// </summary>
    public string LAST_UPDATED_BY { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_TIME
    /// </summary>
    public System.DateTime LAST_UPDATED_TIME { get; set; }
    }
}
