//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///用户配置表
    /// </summary>
    public partial class T_EAP_CALENDAR_SETTING
    {
        
    /// <summary>
    ///用户ID
    /// </summary>
    public string USER_ID { get; set; }
        
    /// <summary>
    ///存储用户配置信息，Json格式字符串，
    ///Json格式为：
    ///      {
    ///        "leader_id": "领导id",
    ///        "default_view": "默认视图",
    ///        "week_begin" : "周开始于",
    ///        "base_type" : "基础数据分类",
    ///        "listdaycount" : "日程显示天数",
    ///        "remind_type" : "提醒方式",
    ///        "remind_time" : "提醒时间",
    ///        "week_mode" : "周显示方式"
    ///    }
    ///default_view 0 日程 1 天 2 星期 3 月 4 年
    ///week_begin 0 星期天 1 星期1
    ///base_type 花都 武汉等
    ///listdaycount 默认值为7, 值可以为2,3,4,5,6,7,14,21,28
    ///remind_type 提醒方式, lycc 0, email 1, sms 2, 手机铃声 3
    ///remind_time 活动开始前多少分钟提醒
    ///week_mode 星期 0 早中晚 1
    /// </summary>
    public string USER_CONF { get; set; }
    }
}
