//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///活动表
    /// </summary>
    public partial class T_EAP_CALENDAR_EVENT
    {
        
    /// <summary>
    ///活动ID
    /// </summary>
    public string EVENT_ID { get; set; }
        
    /// <summary>
    ///发起人
    /// </summary>
    public string USER_ID { get; set; }
        
    /// <summary>
    ///活动分类
    /// </summary>
    public decimal CATEGORY_ID { get; set; }
        
    /// <summary>
    ///活动标题
    /// </summary>
    public string TITLE { get; set; }
        
    /// <summary>
    ///内容
    /// </summary>
    public string EVENT_CONTENT { get; set; }
        
    /// <summary>
    ///地点
    /// </summary>
    public string LOCATION { get; set; }
        
    /// <summary>
    ///开始时间
    /// </summary>
    public System.DateTime START_TIME { get; set; }
        
    /// <summary>
    ///结束时间
    /// </summary>
    public System.DateTime END_TIME { get; set; }
        
    /// <summary>
    ///0待定，1确定
    /// </summary>
    public decimal STATUS { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATED_BY { get; set; }
        
    /// <summary>
    ///创建时间
    /// </summary>
    public System.DateTime CREATED_TIME { get; set; }
        
    /// <summary>
    ///更新人
    /// </summary>
    public string LAST_UPDATED_BY { get; set; }
        
    /// <summary>
    ///最后更改时间
    /// </summary>
    public System.DateTime LAST_UPDATED_TIME { get; set; }
        
    /// <summary>
    ///召集人
    /// </summary>
    public string COLLECTOR { get; set; }
        
    /// <summary>
    ///重复活动ID
    /// </summary>
    public string REPEATE_EVENT_ID { get; set; }
        
    /// <summary>
    ///重复活动规则，Json格式字符串
    /// </summary>
    public string REPEAT_RULE { get; set; }
        
    /// <summary>
    ///outlook唯一标识
    /// </summary>
    public string OUTLOOK_ID { get; set; }
    }
}
