//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_EAP_WF_FILING_LOG
    /// </summary>
    public partial class T_EAP_WF_FILING_LOG
    {
        
    /// <summary>
    ///LOG_ID
    /// </summary>
    public string LOG_ID { get; set; }
        
    /// <summary>
    ///FILING_TABLE
    /// </summary>
    public string FILING_TABLE { get; set; }
        
    /// <summary>
    ///FILING_TABLE_RECORD_ID
    /// </summary>
    public string FILING_TABLE_RECORD_ID { get; set; }
        
    /// <summary>
    ///LOG_DATE
    /// </summary>
    public System.DateTime LOG_DATE { get; set; }
        
    /// <summary>
    ///PROCESS_GUID
    /// </summary>
    public string PROCESS_GUID { get; set; }
    }
}
