//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///流程状态运行表
    /// </summary>
    public partial class T_EAP_WF_PROCESSSTATUS_RUNTIME
    {
        
    /// <summary>
    ///编号
    /// </summary>
    public string ID { get; set; }
        
    /// <summary>
    ///流程编号
    /// </summary>
    public string PROCESS_GUID { get; set; }
        
    /// <summary>
    ///状态
    /// </summary>
    public decimal STATUS { get; set; }
        
    /// <summary>
    ///变更时间
    /// </summary>
    public System.DateTime UPDATE_DATE { get; set; }
        
    /// <summary>
    ///附加参数
    /// </summary>
    public string PARAM { get; set; }
    }
}
