//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_EAP_WF_UI_Module
    /// </summary>
    public partial class T_EAP_WF_UI_MODULE
    {
        
    /// <summary>
    ///编号
    /// </summary>
    public string ID { get; set; }
        
    /// <summary>
    ///步骤编号
    /// </summary>
    public string STEP_GUID { get; set; }
        
    /// <summary>
    ///动作类型
    /// </summary>
    public decimal ACTION_TYPE { get; set; }
        
    /// <summary>
    ///0：否 1：是
    /// </summary>
    public bool SHOWATTACH { get; set; }
        
    /// <summary>
    ///0：否 1：是
    /// </summary>
    public bool SHOWOPTION { get; set; }
        
    /// <summary>
    ///0：否 1：是
    /// </summary>
    public bool SHOWNEXTSTEP { get; set; }
        
    /// <summary>
    ///0：否 1：是
    /// </summary>
    public bool SHOWSUBCONFIRM { get; set; }
        
    /// <summary>
    ///0：否 1：是
    /// </summary>
    public bool SHOWCC { get; set; }
        
    /// <summary>
    ///动作说明信息
    /// </summary>
    public string ACTIONDESC { get; set; }
        
    /// <summary>
    ///快速意见，有多个意见用|隔开
    /// </summary>
    public string QUICKOPTIONLIST { get; set; }
        
    /// <summary>
    ///提交确认提示信息
    /// </summary>
    public string CONFIRMTEXT { get; set; }
        
    /// <summary>
    ///0：否 1：是
    /// </summary>
    public bool SHOWACTIONDIALOG { get; set; }
        
    /// <summary>
    ///EXTEND_PROPERTY
    /// </summary>
    public string EXTEND_PROPERTY { get; set; }
    }
}
