//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///表单模板库表
    /// </summary>
    public partial class T_EAP_FORM_TEMPLATE_LIB
    {
        
    /// <summary>
    ///编号
    /// </summary>
    public string TEMPLATE_ID { get; set; }
        
    /// <summary>
    ///名称
    /// </summary>
    public string TEMPLATE_NAME { get; set; }
        
    /// <summary>
    ///说明
    /// </summary>
    public string TEMPLATE_DESC { get; set; }
        
    /// <summary>
    ///表单XML
    /// </summary>
    public byte[] TEMPLATE_XML_STRING { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATED_BY { get; set; }
        
    /// <summary>
    ///创建时间
    /// </summary>
    public System.DateTime CREATED_TIME { get; set; }
    }
}
