//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_EAP_SYS_EMPLOYEE_PD
    /// </summary>
    public partial class T_EAP_SYS_EMPLOYEE_PD
    {
        
    /// <summary>
    ///员工ID
    /// </summary>
    public string EMP_ID { get; set; }
        
    /// <summary>
    ///员工编码
    /// </summary>
    public string EMP_CODE { get; set; }
        
    /// <summary>
    ///员工姓名
    /// </summary>
    public string EMP_NAME { get; set; }
        
    /// <summary>
    ///所属组织
    /// </summary>
    public string ORG_ID { get; set; }
        
    /// <summary>
    ///性别
    /// </summary>
    public decimal SEX { get; set; }
        
    /// <summary>
    ///邮箱
    /// </summary>
    public string EMAIL { get; set; }
        
    /// <summary>
    ///手机
    /// </summary>
    public string MOBILE { get; set; }
        
    /// <summary>
    ///是否有效
    /// </summary>
    public decimal ENABLED { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATED_BY { get; set; }
        
    /// <summary>
    ///创建时间
    /// </summary>
    public System.DateTime CREATED_TIME { get; set; }
        
    /// <summary>
    ///最后修改人
    /// </summary>
    public string LAST_UPDATED_BY { get; set; }
        
    /// <summary>
    ///最后修改时间
    /// </summary>
    public System.DateTime LAST_UPDATED_TIME { get; set; }
        
    /// <summary>
    ///OFFICEPHONE
    /// </summary>
    public string OFFICEPHONE { get; set; }
        
    /// <summary>
    ///HOMEPHONE
    /// </summary>
    public string HOMEPHONE { get; set; }
        
    /// <summary>
    ///WORKSIGNATURE
    /// </summary>
    public string WORKSIGNATURE { get; set; }
        
    /// <summary>
    ///HEADPHOTO
    /// </summary>
    public string HEADPHOTO { get; set; }
    }
}
