//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_Eap_Sys_Org_Priv
    /// </summary>
    public partial class T_EAP_SYS_ORG_PRIV
    {
        
    /// <summary>
    ///表ID
    /// </summary>
    public string TABLE_ID { get; set; }
        
    /// <summary>
    ///组织ID
    /// </summary>
    public string ORG_ID { get; set; }
        
    /// <summary>
    ///对象ID
    /// </summary>
    public string OBJECT_ID { get; set; }
        
    /// <summary>
    ///对象类型
    /// </summary>
    public string OBJECT_TYPE { get; set; }
    }
}
