//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///组织领导
    /// </summary>
    public partial class T_EAP_SYS_ORG_LEADER
    {
        
    /// <summary>
    ///表ID
    /// </summary>
    public string USER_ORG_ID { get; set; }
        
    /// <summary>
    ///用户ID
    /// </summary>
    public string USER_ID { get; set; }
        
    /// <summary>
    ///组织
    /// </summary>
    public string ORG_ID { get; set; }
    }
}
