//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_Eap_RPT_Edit_Template
    /// </summary>
    public partial class T_EAP_RPT_EDIT_TEMPLATE
    {
        
    /// <summary>
    ///编辑型模板ID
    /// </summary>
    public string TEMPLATE_GUID { get; set; }
        
    /// <summary>
    ///模板编号
    /// </summary>
    public string TEMPLATE_CODE { get; set; }
        
    /// <summary>
    ///模板名称
    /// </summary>
    public string TEMPLATE_NAME { get; set; }
        
    /// <summary>
    ///模板内容
    /// </summary>
    public byte[] CONTENT { get; set; }
        
    /// <summary>
    ///是否有效
    /// </summary>
    public decimal ENABLED { get; set; }
        
    /// <summary>
    ///所用到的数据表
    /// </summary>
    public string SQLTEXT { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATED_BY { get; set; }
        
    /// <summary>
    ///创建时间
    /// </summary>
    public System.DateTime CREATED_TIME { get; set; }
        
    /// <summary>
    ///最后修改人
    /// </summary>
    public string LAST_UPDATED_BY { get; set; }
        
    /// <summary>
    ///最后修改时间
    /// </summary>
    public System.DateTime LAST_UPDATED_TIME { get; set; }
    }
}
