//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_Eap_Form_Resource
    /// </summary>
    public partial class T_EAP_FORM_RESOURCE
    {
        
    /// <summary>
    ///编号
    /// </summary>
    public string RESOURCE_ID { get; set; }
        
    /// <summary>
    ///名称
    /// </summary>
    public string RESOURCE_NAME { get; set; }
        
    /// <summary>
    ///大小
    /// </summary>
    public decimal RESOURCE_SIZE { get; set; }
        
    /// <summary>
    ///类型
    /// </summary>
    public string RESOURCE_TYPE { get; set; }
        
    /// <summary>
    ///内容
    /// </summary>
    public byte[] CONTENT { get; set; }
        
    /// <summary>
    ///是否删除
    /// </summary>
    public decimal ISDELETE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATED_BY { get; set; }
        
    /// <summary>
    ///创建时间
    /// </summary>
    public System.DateTime CREATED_TIME { get; set; }
    }
}
