//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_EAP_SYS_CATEGORY
    /// </summary>
    public partial class T_EAP_SYS_CATEGORY
    {
        
    /// <summary>
    ///CATE_ID
    /// </summary>
    public string CATE_ID { get; set; }
        
    /// <summary>
    ///CATE_CODE
    /// </summary>
    public string CATE_CODE { get; set; }
        
    /// <summary>
    ///CATE_SHORTNAME
    /// </summary>
    public string CATE_SHORTNAME { get; set; }
        
    /// <summary>
    ///CATE_NAME
    /// </summary>
    public string CATE_NAME { get; set; }
        
    /// <summary>
    ///PARENT_CATE_ID
    /// </summary>
    public string PARENT_CATE_ID { get; set; }
        
    /// <summary>
    ///CATE_TYPE
    /// </summary>
    public int CATE_TYPE { get; set; }
        
    /// <summary>
    ///CATE_ORDER
    /// </summary>
    public int CATE_ORDER { get; set; }
        
    /// <summary>
    ///CATE_DESC
    /// </summary>
    public string CATE_DESC { get; set; }
        
    /// <summary>
    ///CREATED_BY
    /// </summary>
    public string CREATED_BY { get; set; }
        
    /// <summary>
    ///CREATED_TIME
    /// </summary>
    public System.DateTime CREATED_TIME { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_BY
    /// </summary>
    public string LAST_UPDATED_BY { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_TIME
    /// </summary>
    public System.DateTime LAST_UPDATED_TIME { get; set; }
        
    /// <summary>
    ///CATE_USERID
    /// </summary>
    public string CATE_USERID { get; set; }
    }
}
