//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///表单历史版本表
    /// </summary>
    public partial class T_EAP_FORM_HISTORY
    {
        
    /// <summary>
    ///编号GUID
    /// </summary>
    public string FORM_HISTORY_ID { get; set; }
        
    /// <summary>
    ///编号2
    /// </summary>
    public string FORM_ID { get; set; }
        
    /// <summary>
    ///名称
    /// </summary>
    public string FORM_NAME { get; set; }
        
    /// <summary>
    ///说明
    /// </summary>
    public string FORM_DESC { get; set; }
        
    /// <summary>
    ///表单类型
    /// </summary>
    public decimal IS_BUSINESS { get; set; }
        
    /// <summary>
    ///表单XML
    /// </summary>
    public byte[] XML_STRING { get; set; }
        
    /// <summary>
    ///源数据库
    /// </summary>
    public string DB { get; set; }
        
    /// <summary>
    ///按钮集合串
    /// </summary>
    public string TOOL_BUTTON_STRING { get; set; }
        
    /// <summary>
    ///公共属性
    /// </summary>
    public string PUBLIC_PROPERTIE { get; set; }
        
    /// <summary>
    ///表单布署DLL路径
    /// </summary>
    public string FORM_DLL_PATH { get; set; }
        
    /// <summary>
    ///表单布署类型
    /// </summary>
    public string FORM_TYPE { get; set; }
        
    /// <summary>
    ///表单存为历史的时间
    /// </summary>
    public System.DateTime IMPORTTIME { get; set; }
        
    /// <summary>
    ///表单类别編号
    /// </summary>
    public string CATEGORY_ID { get; set; }
        
    /// <summary>
    ///表单版本号
    /// </summary>
    public string FORM_VERSION { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATED_BY { get; set; }
        
    /// <summary>
    ///创建时间
    /// </summary>
    public System.DateTime CREATED_TIME { get; set; }
        
    /// <summary>
    ///修改人
    /// </summary>
    public string LAST_UPDATED_BY { get; set; }
        
    /// <summary>
    ///修改时间
    /// </summary>
    public System.DateTime LAST_UPDATED_TIME { get; set; }
    }
}
