//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_EAP_SYS_STATION_LEVEL
    /// </summary>
    public partial class T_EAP_SYS_STATION_LEVEL
    {
        
    /// <summary>
    ///级别名称
    /// </summary>
    public string LEVELNAME { get; set; }
        
    /// <summary>
    ///级别值
    /// </summary>
    public decimal STATIONLEVEL { get; set; }
    }
}
