//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///电子签章运行表
    /// </summary>
    public partial class T_EAP_WF_ELECSEAL_RUNTIME
    {
        
    /// <summary>
    ///编号
    /// </summary>
    public string SEAL_ID { get; set; }
        
    /// <summary>
    ///用户编号
    /// </summary>
    public string USER_ID { get; set; }
        
    /// <summary>
    ///签章时间
    /// </summary>
    public System.DateTime SEALTIME { get; set; }
        
    /// <summary>
    ///流程编号
    /// </summary>
    public string PROCESS_GUID { get; set; }
        
    /// <summary>
    ///节点编号
    /// </summary>
    public string NODE_GUID { get; set; }
        
    /// <summary>
    ///动作类型
    /// </summary>
    public decimal ACTIONTYPE { get; set; }
        
    /// <summary>
    ///电子签章校验数据
    /// </summary>
    public string SEALPARAM { get; set; }
    }
}
