//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///系统窗体数据项表
    /// </summary>
    public partial class T_EAP_SYS_FORM_FIELD
    {
        
    /// <summary>
    ///数据项ID
    /// </summary>
    public string FIELD_ID { get; set; }
        
    /// <summary>
    ///窗体ID
    /// </summary>
    public string FORM_ID { get; set; }
        
    /// <summary>
    ///表格控件代码
    /// </summary>
    public string CONTROL_ID { get; set; }
        
    /// <summary>
    ///数据项代号
    /// </summary>
    public string DATA_CODE { get; set; }
        
    /// <summary>
    ///数据项名称
    /// </summary>
    public string DATA_NAME { get; set; }
    }
}
