//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///报表模版表
    /// </summary>
    public partial class T_EAP_WF_RPT_TEMPLATE
    {
        
    /// <summary>
    ///模板编号
    /// </summary>
    public string GUID { get; set; }
        
    /// <summary>
    ///分类类型id
    /// </summary>
    public decimal TYPE { get; set; }
        
    /// <summary>
    ///类型名称
    /// </summary>
    public string TYPENAME { get; set; }
        
    /// <summary>
    ///报表名称
    /// </summary>
    public string NAME { get; set; }
        
    /// <summary>
    ///报表模板内容
    /// </summary>
    public byte[] CONTENT { get; set; }
        
    /// <summary>
    ///是否删除
    /// </summary>
    public decimal ISDELETE { get; set; }
        
    /// <summary>
    ///创建时间
    /// </summary>
    public System.DateTime CREATETIME { get; set; }
        
    /// <summary>
    ///报表模板路径
    /// </summary>
    public string URL { get; set; }
    }
}
