//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_EAP_MD_LIMIT
    /// </summary>
    public partial class T_EAP_MD_LIMIT
    {
        
    /// <summary>
    ///LMT_ID
    /// </summary>
    public string LMT_ID { get; set; }
        
    /// <summary>
    ///TAB_ID
    /// </summary>
    public string TAB_ID { get; set; }
        
    /// <summary>
    ///LMT_NAME
    /// </summary>
    public string LMT_NAME { get; set; }
        
    /// <summary>
    ///LMT_REGEX
    /// </summary>
    public string LMT_REGEX { get; set; }
        
    /// <summary>
    ///LMT_DESC
    /// </summary>
    public string LMT_DESC { get; set; }
        
    /// <summary>
    ///CREATED_BY
    /// </summary>
    public string CREATED_BY { get; set; }
        
    /// <summary>
    ///CREATED_TIME
    /// </summary>
    public System.DateTime CREATED_TIME { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_BY
    /// </summary>
    public string LAST_UPDATED_BY { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_TIME
    /// </summary>
    public System.DateTime LAST_UPDATED_TIME { get; set; }
        
    /// <summary>
    ///LMT_FIELDIDS
    /// </summary>
    public string LMT_FIELDIDS { get; set; }
        
    /// <summary>
    ///LMT_FIELDNAMES
    /// </summary>
    public string LMT_FIELDNAMES { get; set; }
        
    /// <summary>
    ///LMT_CONTENT
    /// </summary>
    public string LMT_CONTENT { get; set; }
        
    /// <summary>
    ///LMT_SIGN
    /// </summary>
    public int LMT_SIGN { get; set; }
    }
}
