//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_IFS_IQS_BU_INVIT_E3S
    /// </summary>
    public partial class T_IFS_IQS_BU_INVIT_E3S
    {
        
    /// <summary>
    ///ID
    /// </summary>
    public string ID { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///客户编号
    /// </summary>
    public string CUS_NO { get; set; }
        
    /// <summary>
    ///车系名称
    /// </summary>
    public System.DateTime CAR_SERIES_NAME { get; set; }
        
    /// <summary>
    ///调查开始日期
    /// </summary>
    public System.DateTime INVEST_START_DATE { get; set; }
        
    /// <summary>
    ///调查结束日期
    /// </summary>
    public string INVEST_END_DATE { get; set; }
        
    /// <summary>
    ///重要度
    /// </summary>
    public string IMPORTANCE { get; set; }
        
    /// <summary>
    ///专营店编码
    /// </summary>
    public string DLR_CODE { get; set; }
        
    /// <summary>
    ///专营店名称
    /// </summary>
    public string DLR_NAME { get; set; }
        
    /// <summary>
    ///联系人
    /// </summary>
    public string DLR_LINK_MAN { get; set; }
        
    /// <summary>
    ///联系电话
    /// </summary>
    public string DLR_LINK_TEL { get; set; }
        
    /// <summary>
    ///联系地址
    /// </summary>
    public string DLR_ADDRESS { get; set; }
        
    /// <summary>
    ///客户描述
    /// </summary>
    public string CUS_DESC { get; set; }
        
    /// <summary>
    ///项目细分名称
    /// </summary>
    public string ITEM_DETAIL_NAME { get; set; }
        
    /// <summary>
    ///项目窗口
    /// </summary>
    public System.DateTime ITEM_WINDOW_MAN { get; set; }
        
    /// <summary>
    ///TCS确认人
    /// </summary>
    public string TCS_SURE_MAN { get; set; }
        
    /// <summary>
    ///TCS确认日期
    /// </summary>
    public System.DateTime TCS_SURE_DATE { get; set; }
        
    /// <summary>
    ///是否关闭
    /// </summary>
    public string CLOSE_FLAG { get; set; }
        
    /// <summary>
    ///处理时间
    /// </summary>
    public System.DateTime HANDLED_TIME { get; set; }
        
    /// <summary>
    ///处理状态标识
    /// </summary>
    public string HANDLE_FLAG { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建时间
    /// </summary>
    public System.DateTime CREATE_TIME { get; set; }
        
    /// <summary>
    ///修改人
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_TIME { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
    }
}
