//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///IQS调查结果反馈表
    /// </summary>
    public partial class T_IQS_BU_FOLLOW_ANSWERS
    {
        
    /// <summary>
    ///项目细分号
    /// </summary>
    public string ITEM_DETAIL_CODE { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///实车确认结果
    /// </summary>
    public string REAL_CONFIRM { get; set; }
        
    /// <summary>
    ///问卷访谈记录
    /// </summary>
    public string ANSWER_REPORT { get; set; }
        
    /// <summary>
    ///问题小结
    /// </summary>
    public string SCORE_BRIFE { get; set; }
        
    /// <summary>
    ///对策方向
    /// </summary>
    public string METHOLD_DIR { get; set; }
        
    /// <summary>
    ///提交标记
    /// </summary>
    public string SUBMIT_FLAG { get; set; }
        
    /// <summary>
    ///调查里程
    /// </summary>
    public decimal INVEST_KM { get; set; }
        
    /// <summary>
    ///车主名称
    /// </summary>
    public string CAR_OWNER_NAME { get; set; }
        
    /// <summary>
    ///驾龄
    /// </summary>
    public decimal DRIVER_TIME_QTY { get; set; }
        
    /// <summary>
    ///学历
    /// </summary>
    public string DEGREE { get; set; }
        
    /// <summary>
    ///职业
    /// </summary>
    public string JOB { get; set; }
        
    /// <summary>
    ///婚否
    /// </summary>
    public string IS_MARRY { get; set; }
        
    /// <summary>
    ///平常乘客数
    /// </summary>
    public decimal PASSEN_NUM { get; set; }
        
    /// <summary>
    ///车辆主要用途
    /// </summary>
    public string CAR_CARUSE { get; set; }
        
    /// <summary>
    ///调查处理人
    /// </summary>
    public string INVEST_DEAL_MAN { get; set; }
        
    /// <summary>
    ///记录人
    /// </summary>
    public string RECORDOR { get; set; }
        
    /// <summary>
    ///修理日期
    /// </summary>
    public System.DateTime REPAIR_DATE { get; set; }
        
    /// <summary>
    ///修理里程
    /// </summary>
    public decimal REPAIR_KM { get; set; }
        
    /// <summary>
    ///是否再发
    /// </summary>
    public string IS_DISC_AGAIN { get; set; }
        
    /// <summary>
    ///处理内容
    /// </summary>
    public string DEAL_FUNC { get; set; }
        
    /// <summary>
    ///首次现象后的处理内容（含自行和专营店）
    /// </summary>
    public string FIR_DEAL_FUNC { get; set; }
        
    /// <summary>
    ///此次处理内容（专营店）
    /// </summary>
    public string NOW_DEAL_FUNC { get; set; }
        
    /// <summary>
    ///处理结果
    /// </summary>
    public string DEAL_RET { get; set; }
        
    /// <summary>
    ///处理结果备注
    /// </summary>
    public string DEAL_REMARK { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///可用标记
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建时间
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///修改人
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///修改时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///FOLLOW_ANSWERS_ID
    /// </summary>
    public string FOLLOW_ANSWERS_ID { get; set; }
        
    /// <summary>
    ///FOLLOW_DATE
    /// </summary>
    public System.DateTime FOLLOW_DATE { get; set; }
        
    /// <summary>
    ///SEX
    /// </summary>
    public string SEX { get; set; }
        
    /// <summary>
    ///AGE
    /// </summary>
    public decimal AGE { get; set; }
        
    /// <summary>
    ///CITY
    /// </summary>
    public string CITY { get; set; }
        
    /// <summary>
    ///DLR_NAME
    /// </summary>
    public string DLR_NAME { get; set; }
        
    /// <summary>
    ///FIRST_FAULT_DATE
    /// </summary>
    public System.DateTime FIRST_FAULT_DATE { get; set; }
        
    /// <summary>
    ///FIRST_FAULT_MILE
    /// </summary>
    public decimal FIRST_FAULT_MILE { get; set; }
        
    /// <summary>
    ///FAULT_FREQ
    /// </summary>
    public string FAULT_FREQ { get; set; }
        
    /// <summary>
    ///IS_REPAIR
    /// </summary>
    public string IS_REPAIR { get; set; }
        
    /// <summary>
    ///CLIENT_FOCUS
    /// </summary>
    public string CLIENT_FOCUS { get; set; }
        
    /// <summary>
    ///PHOTO
    /// </summary>
    public string PHOTO { get; set; }
        
    /// <summary>
    ///客户编号
    /// </summary>
    public string CUS_NO { get; set; }
        
    /// <summary>
    ///不再现
    /// </summary>
    public string NDF { get; set; }
    }
}
