//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///专营店信息表
    /// </summary>
    public partial class T_IQS_BU_DLR_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_IQS_BU_DLR_INFO()
        {
            this.T_IQS_BU_FOLLOW_CLIENT = new HashSet<T_IQS_BU_FOLLOW_CLIENT>();
        }
    
        
    /// <summary>
    ///专营店ID
    /// </summary>
    public string DLR_ID { get; set; }
        
    /// <summary>
    ///专营店编码
    /// </summary>
    public string DLR_CODE { get; set; }
        
    /// <summary>
    ///专营店全称
    /// </summary>
    public string DLR_FULL_NAME { get; set; }
        
    /// <summary>
    ///专营店名称
    /// </summary>
    public string DLR_NAME { get; set; }
        
    /// <summary>
    ///联系人
    /// </summary>
    public string LINK_MAN { get; set; }
        
    /// <summary>
    ///联系电话
    /// </summary>
    public string LINK_TEL { get; set; }
        
    /// <summary>
    ///联系地址
    /// </summary>
    public string ADDR { get; set; }
        
    /// <summary>
    ///省份
    /// </summary>
    public string PROVINCE { get; set; }
        
    /// <summary>
    ///品牌
    /// </summary>
    public string BRAND { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///可用标记
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建时间
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///修改人
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///修改时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///CITY
    /// </summary>
    public string CITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_IQS_BU_FOLLOW_CLIENT> T_IQS_BU_FOLLOW_CLIENT { get; set; }
    }
}
