//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///IQS案件日志
    /// </summary>
    public partial class T_IQS_BU_TPR_LOG
    {
        
    /// <summary>
    ///IQS案件日志ID
    /// </summary>
    public string IQS_TPR_LOG_ID { get; set; }
        
    /// <summary>
    ///步骤
    /// </summary>
    public string STEP { get; set; }
        
    /// <summary>
    ///操作人
    /// </summary>
    public string OPERATOR { get; set; }
        
    /// <summary>
    ///是否代理
    /// </summary>
    public string IS_AGENT { get; set; }
        
    /// <summary>
    ///原定人员
    /// </summary>
    public string ORIGINAL_MAN { get; set; }
        
    /// <summary>
    ///操作结果
    /// </summary>
    public string OPERATION_RESULT { get; set; }
        
    /// <summary>
    ///说明
    /// </summary>
    public string NOTE { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///可用标记
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建时间
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///修改人
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///修改时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///BILL_NO
    /// </summary>
    public string BILL_NO { get; set; }
    }
}
