//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///调查报告接口字段映射明细表
    /// </summary>
    public partial class T_IQS_DB_INVEST_RPT_F_D
    {
        
    /// <summary>
    ///调查报告接口字段映射明细表ID
    /// </summary>
    public string INVEST_RPT_F_D_ID { get; set; }
        
    /// <summary>
    ///调查报表字段表ID
    /// </summary>
    public string INVEST_RPT_F_ID { get; set; }
        
    /// <summary>
    ///源值编码:接口表字段值编码
    /// </summary>
    public string SOUR_VAL_CODE { get; set; }
        
    /// <summary>
    ///源值名称:接口表字段值名称
    /// </summary>
    public string SOUR_VAL_NAME { get; set; }
        
    /// <summary>
    ///目标值编码:业务表字段值编码
    /// </summary>
    public string TAR_VAL_CODE { get; set; }
        
    /// <summary>
    ///目标值名称:业务表字段值名称
    /// </summary>
    public string TAR_VAL_NAME { get; set; }
        
    /// <summary>
    ///排序号
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    
        public virtual T_IQS_DB_INVEST_RPT_F T_IQS_DB_INVEST_RPT_F { get; set; }
    }
}
