//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///车型
    /// </summary>
    public partial class T_MIS_DB_CAR_TYPE
    {
        
    /// <summary>
    ///车型ID
    /// </summary>
    public string CAR_TYPE_ID { get; set; }
        
    /// <summary>
    ///车系编码
    /// </summary>
    public string CAR_SERIES_CODE { get; set; }
        
    /// <summary>
    ///车型编码
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///车型名称
    /// </summary>
    public string CAR_TYPE_NAME { get; set; }
        
    /// <summary>
    ///备注
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///1
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///sys_guid()
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///88888
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///2
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///默认为系统时间；
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///修改人
    ///修改人
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///默认为系统时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
    }
}
