//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_MIS_BU_REPARE_HIS
    /// </summary>
    public partial class T_MIS_BU_REPARE_HIS
    {
        
    /// <summary>
    ///REPARE_DATA_ID
    /// </summary>
    public string REPARE_DATA_ID { get; set; }
        
    /// <summary>
    ///NET_CODE
    /// </summary>
    public string NET_CODE { get; set; }
        
    /// <summary>
    ///GUARANTNO
    /// </summary>
    public string GUARANTNO { get; set; }
        
    /// <summary>
    ///AGREE_NO
    /// </summary>
    public string AGREE_NO { get; set; }
        
    /// <summary>
    ///VIN
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///ENGINE
    /// </summary>
    public string ENGINE { get; set; }
        
    /// <summary>
    ///BUY_CAR_DATE
    /// </summary>
    public string BUY_CAR_DATE { get; set; }
        
    /// <summary>
    ///MILEAGE
    /// </summary>
    public decimal MILEAGE { get; set; }
        
    /// <summary>
    ///LINK_MAN
    /// </summary>
    public string LINK_MAN { get; set; }
        
    /// <summary>
    ///LINK_TEL
    /// </summary>
    public string LINK_TEL { get; set; }
        
    /// <summary>
    ///REPAIR_DATE
    /// </summary>
    public string REPAIR_DATE { get; set; }
        
    /// <summary>
    ///CS_CODE
    /// </summary>
    public string CS_CODE { get; set; }
        
    /// <summary>
    ///CT_CODE
    /// </summary>
    public string CT_CODE { get; set; }
        
    /// <summary>
    ///REPAIR_CODE
    /// </summary>
    public string REPAIR_CODE { get; set; }
        
    /// <summary>
    ///FIX_MILEAGE
    /// </summary>
    public decimal FIX_MILEAGE { get; set; }
        
    /// <summary>
    ///FIX_DATE
    /// </summary>
    public string FIX_DATE { get; set; }
        
    /// <summary>
    ///ASSEMB_CODE
    /// </summary>
    public string ASSEMB_CODE { get; set; }
        
    /// <summary>
    ///REASON
    /// </summary>
    public string REASON { get; set; }
        
    /// <summary>
    ///WORK_FEE
    /// </summary>
    public decimal WORK_FEE { get; set; }
        
    /// <summary>
    ///PART_FEE
    /// </summary>
    public decimal PART_FEE { get; set; }
        
    /// <summary>
    ///OTHE_FEE
    /// </summary>
    public decimal OTHE_FEE { get; set; }
        
    /// <summary>
    ///TOTAL_FEE
    /// </summary>
    public decimal TOTAL_FEE { get; set; }
        
    /// <summary>
    ///IS_AUTO_CHECK
    /// </summary>
    public string IS_AUTO_CHECK { get; set; }
        
    /// <summary>
    ///FINAN_CHECK_TIME
    /// </summary>
    public string FINAN_CHECK_TIME { get; set; }
        
    /// <summary>
    ///PROC_DATE
    /// </summary>
    public string PROC_DATE { get; set; }
        
    /// <summary>
    ///CAR_NO
    /// </summary>
    public string CAR_NO { get; set; }
        
    /// <summary>
    ///CAR_SERIES_NAME
    /// </summary>
    public string CAR_SERIES_NAME { get; set; }
        
    /// <summary>
    ///CAR_TYPE_NAME
    /// </summary>
    public string CAR_TYPE_NAME { get; set; }
        
    /// <summary>
    ///FAULT_PART_CODE
    /// </summary>
    public string FAULT_PART_CODE { get; set; }
        
    /// <summary>
    ///CS_NAME
    /// </summary>
    public string CS_NAME { get; set; }
        
    /// <summary>
    ///CT_NAME
    /// </summary>
    public string CT_NAME { get; set; }
        
    /// <summary>
    ///PROC_IN_MONTH
    /// </summary>
    public string PROC_IN_MONTH { get; set; }
        
    /// <summary>
    ///NET_SHOR_NAME
    /// </summary>
    public string NET_SHOR_NAME { get; set; }
        
    /// <summary>
    ///NET_FULL_NAME
    /// </summary>
    public string NET_FULL_NAME { get; set; }
        
    /// <summary>
    ///BIG_EARE
    /// </summary>
    public string BIG_EARE { get; set; }
        
    /// <summary>
    ///DIFF_DAYS
    /// </summary>
    public decimal DIFF_DAYS { get; set; }
        
    /// <summary>
    ///SALE_DATE
    /// </summary>
    public string SALE_DATE { get; set; }
        
    /// <summary>
    ///REPAIR_IN_MONTH
    /// </summary>
    public string REPAIR_IN_MONTH { get; set; }
        
    /// <summary>
    ///REPIRT_MONTH
    /// </summary>
    public string REPIRT_MONTH { get; set; }
        
    /// <summary>
    ///BUSINESS_CHECK_DATE
    /// </summary>
    public string BUSINESS_CHECK_DATE { get; set; }
        
    /// <summary>
    ///NO_SUPPLY_PFP_CODE
    /// </summary>
    public string NO_SUPPLY_PFP_CODE { get; set; }
        
    /// <summary>
    ///PFP_NAME
    /// </summary>
    public string PFP_NAME { get; set; }
        
    /// <summary>
    ///PFP_QTY
    /// </summary>
    public string PFP_QTY { get; set; }
        
    /// <summary>
    ///MAINTEGERAIN_TYPE_CODE
    /// </summary>
    public string MAINTEGERAIN_TYPE_CODE { get; set; }
        
    /// <summary>
    ///CAR_TYPE_CODE
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///MAINTEGERAIN_STAT_DATE
    /// </summary>
    public string MAINTEGERAIN_STAT_DATE { get; set; }
        
    /// <summary>
    ///CAR_SERIES_CODE
    /// </summary>
    public string CAR_SERIES_CODE { get; set; }
        
    /// <summary>
    ///SUPPLIER_CODE
    /// </summary>
    public string SUPPLIER_CODE { get; set; }
        
    /// <summary>
    ///SUPPLIER_SHORT_NAME
    /// </summary>
    public string SUPPLIER_SHORT_NAME { get; set; }
        
    /// <summary>
    ///COMP_DLR_FEE
    /// </summary>
    public decimal COMP_DLR_FEE { get; set; }
        
    /// <summary>
    ///COMP_DLR_WORK_FEE
    /// </summary>
    public decimal COMP_DLR_WORK_FEE { get; set; }
        
    /// <summary>
    ///COMP_DLR_OTHER_FEE
    /// </summary>
    public decimal COMP_DLR_OTHER_FEE { get; set; }
        
    /// <summary>
    ///PFP_SORT
    /// </summary>
    public string PFP_SORT { get; set; }
        
    /// <summary>
    ///PFP_SID
    /// </summary>
    public string PFP_SID { get; set; }
        
    /// <summary>
    ///OTHE_COEF
    /// </summary>
    public decimal OTHE_COEF { get; set; }
        
    /// <summary>
    ///REMARK
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///BRAND_CODE
    /// </summary>
    public string BRAND_CODE { get; set; }
        
    /// <summary>
    ///DATE_BACK
    /// </summary>
    public string DATE_BACK { get; set; }
        
    /// <summary>
    ///DATE_CLAIM
    /// </summary>
    public string DATE_CLAIM { get; set; }
        
    /// <summary>
    ///DATE_REFUSE
    /// </summary>
    public string DATE_REFUSE { get; set; }
        
    /// <summary>
    ///FLAG_BACK
    /// </summary>
    public decimal FLAG_BACK { get; set; }
        
    /// <summary>
    ///FLAG_REFUSE
    /// </summary>
    public decimal FLAG_REFUSE { get; set; }
        
    /// <summary>
    ///NETBRAND
    /// </summary>
    public string NETBRAND { get; set; }
        
    /// <summary>
    ///PART_COEF
    /// </summary>
    public decimal PART_COEF { get; set; }
        
    /// <summary>
    ///WORK_COEF
    /// </summary>
    public decimal WORK_COEF { get; set; }
        
    /// <summary>
    ///RECALL_CODE
    /// </summary>
    public string RECALL_CODE { get; set; }
        
    /// <summary>
    ///CASE_CODE
    /// </summary>
    public string CASE_CODE { get; set; }
        
    /// <summary>
    ///ORDER_NO
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///IS_ENABLE
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///UPDATE_CONTROL_ID
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///SDP_USER_ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP_ORG_ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///CREATOR
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///CREATED_DATE
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///MODIFIER
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_DATE
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SALE_PRODUCT_MONTH
    /// </summary>
    public decimal SALE_PRODUCT_MONTH { get; set; }
        
    /// <summary>
    ///REPARE_SALE_MONTH
    /// </summary>
    public decimal REPARE_SALE_MONTH { get; set; }
        
    /// <summary>
    ///SNRN_MONTH
    /// </summary>
    public decimal SNRN_MONTH { get; set; }
        
    /// <summary>
    ///PFP
    /// </summary>
    public string PFP { get; set; }
        
    /// <summary>
    ///ALL_MONTH
    /// </summary>
    public decimal ALL_MONTH { get; set; }
        
    /// <summary>
    ///PROVINCE_ID
    /// </summary>
    public string PROVINCE_ID { get; set; }
        
    /// <summary>
    ///PROVINCE_NAME
    /// </summary>
    public string PROVINCE_NAME { get; set; }
        
    /// <summary>
    ///FAULT_PART_NAME
    /// </summary>
    public string FAULT_PART_NAME { get; set; }
        
    /// <summary>
    ///MAINTEGERAIN_TYPE_NAME
    /// </summary>
    public string MAINTEGERAIN_TYPE_NAME { get; set; }
        
    /// <summary>
    ///TXT
    /// </summary>
    public string TXT { get; set; }
    }
}
