//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_PQ_BU_DATAGRID_COL
    /// </summary>
    public partial class T_PQ_BU_DATAGRID_COL
    {
        
    /// <summary>
    ///ID
    /// </summary>
    public int ID { get; set; }
        
    /// <summary>
    ///GRIDCODE
    /// </summary>
    public string GRIDCODE { get; set; }
        
    /// <summary>
    ///CONFIG
    /// </summary>
    public string CONFIG { get; set; }
        
    /// <summary>
    ///EDITDATASQL
    /// </summary>
    public string EDITDATASQL { get; set; }
        
    /// <summary>
    ///CREATEON
    /// </summary>
    public System.DateTime CREATEON { get; set; }
        
    /// <summary>
    ///LASTUPDATEON
    /// </summary>
    public System.DateTime LASTUPDATEON { get; set; }
        
    /// <summary>
    ///CREATEBY
    /// </summary>
    public string CREATEBY { get; set; }
        
    /// <summary>
    ///LASTUPDATEBY
    /// </summary>
    public string LASTUPDATEBY { get; set; }
        
    /// <summary>
    ///ORDERNO
    /// </summary>
    public int ORDERNO { get; set; }
        
    /// <summary>
    ///ISENABLE
    /// </summary>
    public bool ISENABLE { get; set; }
        
    /// <summary>
    ///EXPORT
    /// </summary>
    public bool EXPORT { get; set; }
    
        public virtual T_PQ_BU_DATAGRID T_PQ_BU_DATAGRID { get; set; }
    }
}
