//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_PQ_DB_DATA_AUTH_RULE_TEMP
    /// </summary>
    public partial class T_PQ_DB_DATA_AUTH_RULE_TEMP
    {
        
    /// <summary>
    ///DATA_AUTH_RULE_ID
    /// </summary>
    public string DATA_AUTH_RULE_ID { get; set; }
        
    /// <summary>
    ///USER_GROUP_ID
    /// </summary>
    public string USER_GROUP_ID { get; set; }
        
    /// <summary>
    ///USER_GROUP_NAME
    /// </summary>
    public string USER_GROUP_NAME { get; set; }
        
    /// <summary>
    ///PART_TYPE
    /// </summary>
    public string PART_TYPE { get; set; }
        
    /// <summary>
    ///ORDER_NO
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///IS_ENABLE
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///CREATOR
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///CREATED_DATE
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///MODIFIER
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_DATE
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP_USER_ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP_ORG_ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///UPDATE_CONTROL_ID
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///FACTORY_CODE
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///FACTORY_NAME
    /// </summary>
    public string FACTORY_NAME { get; set; }
    }
}
