//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_PQ_BU_RPT_EMAIL_BAK
    /// </summary>
    public partial class T_PQ_BU_RPT_EMAIL_BAK
    {
        
    /// <summary>
    ///RPT_EMAIL_ID
    /// </summary>
    public string RPT_EMAIL_ID { get; set; }
        
    /// <summary>
    ///RPT_RECEIVER_MAIL
    /// </summary>
    public string RPT_RECEIVER_MAIL { get; set; }
        
    /// <summary>
    ///RPT_URL_PARAM
    /// </summary>
    public string RPT_URL_PARAM { get; set; }
        
    /// <summary>
    ///RPT_PARAM_DES
    /// </summary>
    public string RPT_PARAM_DES { get; set; }
        
    /// <summary>
    ///RPT_FILENAME
    /// </summary>
    public string RPT_FILENAME { get; set; }
        
    /// <summary>
    ///RPT_TITLE
    /// </summary>
    public string RPT_TITLE { get; set; }
        
    /// <summary>
    ///RPT_MAIN_BODY
    /// </summary>
    public string RPT_MAIN_BODY { get; set; }
        
    /// <summary>
    ///RPT_DATE
    /// </summary>
    public System.DateTime RPT_DATE { get; set; }
        
    /// <summary>
    ///ORDER_NO
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///IS_ENABLE
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///CREATOR
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///CREATED_DATE
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///MODIFIER
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_DATE
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP_USER_ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP_ORG_ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///UPDATE_CONTROL_ID
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    }
}
