//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///TMP5
    /// </summary>
    public partial class TMP5
    {
        
    /// <summary>
    ///PART_PROCESS_ID
    /// </summary>
    public string PART_PROCESS_ID { get; set; }
        
    /// <summary>
    ///PART_PROJ_ID
    /// </summary>
    public string PART_PROJ_ID { get; set; }
        
    /// <summary>
    ///FACTORY_CODE
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///PART_SORT
    /// </summary>
    public string PART_SORT { get; set; }
        
    /// <summary>
    ///PART_2D_CODE
    /// </summary>
    public string PART_2D_CODE { get; set; }
        
    /// <summary>
    ///PROD_2D_CODE
    /// </summary>
    public string PROD_2D_CODE { get; set; }
        
    /// <summary>
    ///PROCESS_CODE
    /// </summary>
    public string PROCESS_CODE { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///PROCESS_EQUIP_CODE
    /// </summary>
    public string PROCESS_EQUIP_CODE { get; set; }
        
    /// <summary>
    ///PASS_MAC_TIME
    /// </summary>
    public System.DateTime PASS_MAC_TIME { get; set; }
        
    /// <summary>
    ///PROCESS_STATUS
    /// </summary>
    public string PROCESS_STATUS { get; set; }
        
    /// <summary>
    ///BAD_BIG_TYPE
    /// </summary>
    public string BAD_BIG_TYPE { get; set; }
        
    /// <summary>
    ///BAD_TYPE
    /// </summary>
    public string BAD_TYPE { get; set; }
        
    /// <summary>
    ///MEASURE_LEVEL
    /// </summary>
    public string MEASURE_LEVEL { get; set; }
        
    /// <summary>
    ///PACK_LABEL_CODE
    /// </summary>
    public string PACK_LABEL_CODE { get; set; }
        
    /// <summary>
    ///BAT_BAR_CODE
    /// </summary>
    public string BAT_BAR_CODE { get; set; }
        
    /// <summary>
    ///CHAN_LEAKAGE
    /// </summary>
    public decimal CHAN_LEAKAGE { get; set; }
        
    /// <summary>
    ///OIL_LEAKAGE
    /// </summary>
    public decimal OIL_LEAKAGE { get; set; }
        
    /// <summary>
    ///SPARK_PLUG_LEAKAGE
    /// </summary>
    public decimal SPARK_PLUG_LEAKAGE { get; set; }
        
    /// <summary>
    ///ROCKER_CHAMBER_LEAKAGE
    /// </summary>
    public decimal ROCKER_CHAMBER_LEAKAGE { get; set; }
        
    /// <summary>
    ///CRANKCASE_LEAKAGE
    /// </summary>
    public decimal CRANKCASE_LEAKAGE { get; set; }
        
    /// <summary>
    ///MID_TL_NUM
    /// </summary>
    public int MID_TL_NUM { get; set; }
        
    /// <summary>
    ///FINAL_TL_AMT
    /// </summary>
    public decimal FINAL_TL_AMT { get; set; }
        
    /// <summary>
    ///FINAL_TL_COVER1
    /// </summary>
    public decimal FINAL_TL_COVER1 { get; set; }
        
    /// <summary>
    ///FINAL_TL_COVER2
    /// </summary>
    public decimal FINAL_TL_COVER2 { get; set; }
        
    /// <summary>
    ///FINAL_TL_COVER3
    /// </summary>
    public decimal FINAL_TL_COVER3 { get; set; }
        
    /// <summary>
    ///FINAL_TL_CHAN
    /// </summary>
    public decimal FINAL_TL_CHAN { get; set; }
        
    /// <summary>
    ///FINAL_TL_SCREW
    /// </summary>
    public decimal FINAL_TL_SCREW { get; set; }
        
    /// <summary>
    ///ORDER_NO
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///IS_ENABLE
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///CREATOR
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///CREATED_DATE
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///MODIFIER
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_DATE
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP_USER_ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP_ORG_ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///UPDATE_CONTROL_ID
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS
    /// </summary>
    public string LOGIC_PROCESS { get; set; }
        
    /// <summary>
    ///FACTORY_NAME
    /// </summary>
    public string FACTORY_NAME { get; set; }
        
    /// <summary>
    ///DUTY_DEPT
    /// </summary>
    public string DUTY_DEPT { get; set; }
        
    /// <summary>
    ///STATUS_CHANGE_MAN
    /// </summary>
    public string STATUS_CHANGE_MAN { get; set; }
        
    /// <summary>
    ///CHANGE_TIME
    /// </summary>
    public System.DateTime CHANGE_TIME { get; set; }
        
    /// <summary>
    ///CHANGE_REMARK
    /// </summary>
    public string CHANGE_REMARK { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS_N
    /// </summary>
    public string LOGIC_PROCESS_N { get; set; }
        
    /// <summary>
    ///CHAN_LEAKAGE_STATUS
    /// </summary>
    public string CHAN_LEAKAGE_STATUS { get; set; }
        
    /// <summary>
    ///CHAN_LEAKAGE_DESC
    /// </summary>
    public string CHAN_LEAKAGE_DESC { get; set; }
        
    /// <summary>
    ///OIL_LEAKAGE_STATUS
    /// </summary>
    public string OIL_LEAKAGE_STATUS { get; set; }
        
    /// <summary>
    ///OIL_LEAKAGE_DESC
    /// </summary>
    public string OIL_LEAKAGE_DESC { get; set; }
        
    /// <summary>
    ///CRANKCASE_LEAKAGE_STATUS
    /// </summary>
    public string CRANKCASE_LEAKAGE_STATUS { get; set; }
        
    /// <summary>
    ///CRANKCASE_LEAKAGE_DESC
    /// </summary>
    public string CRANKCASE_LEAKAGE_DESC { get; set; }
    }
}
