//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///V1_T_PQ_DB_KD_FIVE_PART_REL
    /// </summary>
    public partial class V1_T_PQ_DB_KD_FIVE_PART_REL
    {
        
    /// <summary>
    ///所属工厂
    /// </summary>
    public string 所属工厂 { get; set; }
        
    /// <summary>
    ///五位码
    /// </summary>
    public string 五位码 { get; set; }
        
    /// <summary>
    ///部品人员
    /// </summary>
    public string 部品人员 { get; set; }
        
    /// <summary>
    ///FACTORY_CODE
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///FIVE_PART_CODE
    /// </summary>
    public string FIVE_PART_CODE { get; set; }
        
    /// <summary>
    ///EMP_NAME
    /// </summary>
    public string EMP_NAME { get; set; }
        
    /// <summary>
    ///CREATED_DATE
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///KD_FIVE_PART_REL_ID
    /// </summary>
    public string KD_FIVE_PART_REL_ID { get; set; }
        
    /// <summary>
    ///UPDATE_CONTROL_ID
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    }
}
