//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///V1_T_BU_PQ_REJ_JG_APP_U_PART
    /// </summary>
    public partial class V1_T_BU_PQ_REJ_JG_APP_U_PART
    {
        
    /// <summary>
    ///REJ_BILL_CODE
    /// </summary>
    public string REJ_BILL_CODE { get; set; }
        
    /// <summary>
    ///不合格品单号
    /// </summary>
    public string 不合格品单号 { get; set; }
        
    /// <summary>
    ///PART_NO
    /// </summary>
    public string PART_NO { get; set; }
        
    /// <summary>
    ///零件编码
    /// </summary>
    public string 零件编码 { get; set; }
        
    /// <summary>
    ///供应商
    /// </summary>
    public string 供应商 { get; set; }
        
    /// <summary>
    ///数量
    /// </summary>
    public decimal 数量 { get; set; }
        
    /// <summary>
    ///NG数量
    /// </summary>
    public decimal NG数量 { get; set; }
    }
}
