//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///V_PTPQ_ASSECUSTOMINQUIRE03
    /// </summary>
    public partial class V_PTPQ_ASSECUSTOMINQUIRE03
    {
        
    /// <summary>
    ///PART_PROJ_ID
    /// </summary>
    public string PART_PROJ_ID { get; set; }
        
    /// <summary>
    ///FACTORY_CODE
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///FACTORY_NAME
    /// </summary>
    public string FACTORY_NAME { get; set; }
        
    /// <summary>
    ///PART_SORT
    /// </summary>
    public string PART_SORT { get; set; }
        
    /// <summary>
    ///PART_SORT_NAME
    /// </summary>
    public string PART_SORT_NAME { get; set; }
        
    /// <summary>
    ///PART_2D_CODE
    /// </summary>
    public string PART_2D_CODE { get; set; }
        
    /// <summary>
    ///PART_STATUS
    /// </summary>
    public string PART_STATUS { get; set; }
        
    /// <summary>
    ///PART_STATUS_NAME
    /// </summary>
    public string PART_STATUS_NAME { get; set; }
        
    /// <summary>
    ///PACK_LABEL_CODE
    /// </summary>
    public string PACK_LABEL_CODE { get; set; }
        
    /// <summary>
    ///ENGINE_NO
    /// </summary>
    public string ENGINE_NO { get; set; }
        
    /// <summary>
    ///MAC_TYPE
    /// </summary>
    public string MAC_TYPE { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///PRO_LINE_NAME
    /// </summary>
    public string PRO_LINE_NAME { get; set; }
        
    /// <summary>
    ///MOLD_CODE
    /// </summary>
    public string MOLD_CODE { get; set; }
        
    /// <summary>
    ///PART_NO
    /// </summary>
    public string PART_NO { get; set; }
        
    /// <summary>
    ///PART_NAME
    /// </summary>
    public string PART_NAME { get; set; }
        
    /// <summary>
    ///BAD_BIG_TYPE
    /// </summary>
    public string BAD_BIG_TYPE { get; set; }
        
    /// <summary>
    ///BAD_BIG_TYPE_NAME
    /// </summary>
    public string BAD_BIG_TYPE_NAME { get; set; }
        
    /// <summary>
    ///BAD_TYPE
    /// </summary>
    public string BAD_TYPE { get; set; }
        
    /// <summary>
    ///BAD_TYPE_NAME
    /// </summary>
    public string BAD_TYPE_NAME { get; set; }
        
    /// <summary>
    ///LOGIC_STATUS
    /// </summary>
    public short LOGIC_STATUS { get; set; }
        
    /// <summary>
    ///STATUS_CHANGE_NUM
    /// </summary>
    public int STATUS_CHANGE_NUM { get; set; }
        
    /// <summary>
    ///STATUS_CHANGE_SOURCE
    /// </summary>
    public string STATUS_CHANGE_SOURCE { get; set; }
        
    /// <summary>
    ///STATUS_CHANGE_MAN
    /// </summary>
    public string STATUS_CHANGE_MAN { get; set; }
        
    /// <summary>
    ///CHANGE_TIME
    /// </summary>
    public System.DateTime CHANGE_TIME { get; set; }
        
    /// <summary>
    ///CHANGE_BAT
    /// </summary>
    public string CHANGE_BAT { get; set; }
        
    /// <summary>
    ///CHANGE_REMARK
    /// </summary>
    public string CHANGE_REMARK { get; set; }
        
    /// <summary>
    ///DECI_PROCESS
    /// </summary>
    public string DECI_PROCESS { get; set; }
        
    /// <summary>
    ///DUTY_DEPT
    /// </summary>
    public string DUTY_DEPT { get; set; }
        
    /// <summary>
    ///DUTY_DEPT_NAME
    /// </summary>
    public string DUTY_DEPT_NAME { get; set; }
        
    /// <summary>
    ///DECI_LOGIC_PROCESS
    /// </summary>
    public string DECI_LOGIC_PROCESS { get; set; }
        
    /// <summary>
    ///DECI_LOGIC_PROCESS_NAME
    /// </summary>
    public string DECI_LOGIC_PROCESS_NAME { get; set; }
        
    /// <summary>
    ///PART_PROJ_ID100B
    /// </summary>
    public string PART_PROJ_ID100B { get; set; }
        
    /// <summary>
    ///PART_PROCESS_ID100B
    /// </summary>
    public string PART_PROCESS_ID100B { get; set; }
        
    /// <summary>
    ///PROCESS_CODE100B
    /// </summary>
    public string PROCESS_CODE100B { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS100B
    /// </summary>
    public string LOGIC_PROCESS100B { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS_N100B
    /// </summary>
    public string LOGIC_PROCESS_N100B { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE100B
    /// </summary>
    public string PRO_LINE_CODE100B { get; set; }
        
    /// <summary>
    ///PRO_LINE_NAME100B
    /// </summary>
    public string PRO_LINE_NAME100B { get; set; }
        
    /// <summary>
    ///PASS_MAC_TIME100B
    /// </summary>
    public System.DateTime PASS_MAC_TIME100B { get; set; }
        
    /// <summary>
    ///PROCESS_EQUIP_CODE100B
    /// </summary>
    public string PROCESS_EQUIP_CODE100B { get; set; }
        
    /// <summary>
    ///PART_PROJ_ID200B
    /// </summary>
    public string PART_PROJ_ID200B { get; set; }
        
    /// <summary>
    ///PART_PROCESS_ID200B
    /// </summary>
    public string PART_PROCESS_ID200B { get; set; }
        
    /// <summary>
    ///PROCESS_CODE200B
    /// </summary>
    public string PROCESS_CODE200B { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS200B
    /// </summary>
    public string LOGIC_PROCESS200B { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS_N200B
    /// </summary>
    public string LOGIC_PROCESS_N200B { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE200B
    /// </summary>
    public string PRO_LINE_CODE200B { get; set; }
        
    /// <summary>
    ///PRO_LINE_NAME200B
    /// </summary>
    public string PRO_LINE_NAME200B { get; set; }
        
    /// <summary>
    ///PASS_MAC_TIME200B
    /// </summary>
    public System.DateTime PASS_MAC_TIME200B { get; set; }
        
    /// <summary>
    ///PROCESS_EQUIP_CODE200B
    /// </summary>
    public string PROCESS_EQUIP_CODE200B { get; set; }
        
    /// <summary>
    ///PROCESS_STATUS200B
    /// </summary>
    public string PROCESS_STATUS200B { get; set; }
        
    /// <summary>
    ///PROCESS_STATUS_NAME200B
    /// </summary>
    public string PROCESS_STATUS_NAME200B { get; set; }
        
    /// <summary>
    ///CHAN_LEAKAGE200B
    /// </summary>
    public decimal CHAN_LEAKAGE200B { get; set; }
        
    /// <summary>
    ///OIL_LEAKAGE200B
    /// </summary>
    public decimal OIL_LEAKAGE200B { get; set; }
        
    /// <summary>
    ///CRANKCASE_LEAKAGE200B
    /// </summary>
    public decimal CRANKCASE_LEAKAGE200B { get; set; }
        
    /// <summary>
    ///PART_PROJ_ID300B
    /// </summary>
    public string PART_PROJ_ID300B { get; set; }
        
    /// <summary>
    ///PART_PROCESS_ID300B
    /// </summary>
    public string PART_PROCESS_ID300B { get; set; }
        
    /// <summary>
    ///PROCESS_CODE300B
    /// </summary>
    public string PROCESS_CODE300B { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS300B
    /// </summary>
    public string LOGIC_PROCESS300B { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS_N300B
    /// </summary>
    public string LOGIC_PROCESS_N300B { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE300B
    /// </summary>
    public string PRO_LINE_CODE300B { get; set; }
        
    /// <summary>
    ///PRO_LINE_NAME300B
    /// </summary>
    public string PRO_LINE_NAME300B { get; set; }
        
    /// <summary>
    ///PASS_MAC_TIME300B
    /// </summary>
    public System.DateTime PASS_MAC_TIME300B { get; set; }
        
    /// <summary>
    ///PROCESS_EQUIP_CODE300B
    /// </summary>
    public string PROCESS_EQUIP_CODE300B { get; set; }
        
    /// <summary>
    ///MEASURE_LEVEL300B
    /// </summary>
    public string MEASURE_LEVEL300B { get; set; }
        
    /// <summary>
    ///PART_PROJ_ID400B
    /// </summary>
    public string PART_PROJ_ID400B { get; set; }
        
    /// <summary>
    ///PART_PROCESS_ID400B
    /// </summary>
    public string PART_PROCESS_ID400B { get; set; }
        
    /// <summary>
    ///PROCESS_CODE400B
    /// </summary>
    public string PROCESS_CODE400B { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS400B
    /// </summary>
    public string LOGIC_PROCESS400B { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS_N400B
    /// </summary>
    public string LOGIC_PROCESS_N400B { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE400B
    /// </summary>
    public string PRO_LINE_CODE400B { get; set; }
        
    /// <summary>
    ///PRO_LINE_NAME400B
    /// </summary>
    public string PRO_LINE_NAME400B { get; set; }
        
    /// <summary>
    ///PASS_MAC_TIME400B
    /// </summary>
    public System.DateTime PASS_MAC_TIME400B { get; set; }
        
    /// <summary>
    ///PROCESS_EQUIP_CODE400B
    /// </summary>
    public string PROCESS_EQUIP_CODE400B { get; set; }
        
    /// <summary>
    ///MEASURE_LEVEL400B
    /// </summary>
    public string MEASURE_LEVEL400B { get; set; }
        
    /// <summary>
    ///PART_PROJ_ID500B
    /// </summary>
    public string PART_PROJ_ID500B { get; set; }
        
    /// <summary>
    ///PART_PROCESS_ID500B
    /// </summary>
    public string PART_PROCESS_ID500B { get; set; }
        
    /// <summary>
    ///PROCESS_CODE500B
    /// </summary>
    public string PROCESS_CODE500B { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS500B
    /// </summary>
    public string LOGIC_PROCESS500B { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS_N500B
    /// </summary>
    public string LOGIC_PROCESS_N500B { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE500B
    /// </summary>
    public string PRO_LINE_CODE500B { get; set; }
        
    /// <summary>
    ///PRO_LINE_NAME500B
    /// </summary>
    public string PRO_LINE_NAME500B { get; set; }
        
    /// <summary>
    ///PASS_MAC_TIME500B
    /// </summary>
    public System.DateTime PASS_MAC_TIME500B { get; set; }
        
    /// <summary>
    ///PROCESS_EQUIP_CODE500B
    /// </summary>
    public string PROCESS_EQUIP_CODE500B { get; set; }
        
    /// <summary>
    ///PROCESS_STATUS500B
    /// </summary>
    public string PROCESS_STATUS500B { get; set; }
        
    /// <summary>
    ///PROCESS_STATUS_NAME500B
    /// </summary>
    public string PROCESS_STATUS_NAME500B { get; set; }
        
    /// <summary>
    ///FINAL_TL_COVER1500B
    /// </summary>
    public decimal FINAL_TL_COVER1500B { get; set; }
        
    /// <summary>
    ///FINAL_TL_CHAN500B
    /// </summary>
    public decimal FINAL_TL_CHAN500B { get; set; }
        
    /// <summary>
    ///FINAL_TL_SCREW500B
    /// </summary>
    public decimal FINAL_TL_SCREW500B { get; set; }
        
    /// <summary>
    ///PART_PROJ_ID600B
    /// </summary>
    public string PART_PROJ_ID600B { get; set; }
        
    /// <summary>
    ///PART_PROCESS_ID600B
    /// </summary>
    public string PART_PROCESS_ID600B { get; set; }
        
    /// <summary>
    ///PROCESS_CODE600B
    /// </summary>
    public string PROCESS_CODE600B { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS600B
    /// </summary>
    public string LOGIC_PROCESS600B { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS_N600B
    /// </summary>
    public string LOGIC_PROCESS_N600B { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE600B
    /// </summary>
    public string PRO_LINE_CODE600B { get; set; }
        
    /// <summary>
    ///PRO_LINE_NAME600B
    /// </summary>
    public string PRO_LINE_NAME600B { get; set; }
        
    /// <summary>
    ///PASS_MAC_TIME600B
    /// </summary>
    public System.DateTime PASS_MAC_TIME600B { get; set; }
        
    /// <summary>
    ///PROCESS_EQUIP_CODE600B
    /// </summary>
    public string PROCESS_EQUIP_CODE600B { get; set; }
        
    /// <summary>
    ///PACK_LABEL_CODE600B
    /// </summary>
    public string PACK_LABEL_CODE600B { get; set; }
    }
}
