//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateEntity.MQCSBUS
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///V_PTPQ_PART_TYPE_USER
    /// </summary>
    public partial class V_PTPQ_PART_TYPE_USER
    {
        
    /// <summary>
    ///PART_TYPE_CODE
    /// </summary>
    public string PART_TYPE_CODE { get; set; }
        
    /// <summary>
    ///PART_TYPE_NAME
    /// </summary>
    public string PART_TYPE_NAME { get; set; }
        
    /// <summary>
    ///TYPE
    /// </summary>
    public string TYPE { get; set; }
        
    /// <summary>
    ///USER_ID
    /// </summary>
    public string USER_ID { get; set; }
    }
}
